### ISSUE TITLE
Thumbnails Disappearing on Staff Module

### ISSUE THREAD

**Issue by craubenheimer** [live-composer/live-composer-page-builder#1001]
I am creating a staff module on my website, but when I close the live composer the thumbnail images disappear.

It looks like this when I am editing-
![image](https://user-images.githubusercontent.com/53534864/62231761-ae288900-b392-11e9-9061-86fe7f168cc4.png)

Then like this when I save it and close the live composer-
![image](https://user-images.githubusercontent.com/53534864/62231851-d7e1b000-b392-11e9-9acc-11dc37e1d437.png)

Please help!

**Comment by lumberman** [comment]
Hello,
It works fine on my server. Did you use resizing in STYLING > THUMBNAIL > Resize - Height/Width? If so, try to disable it and see if it helps. Probably you have image processing library responsible for resizing missing on your server.

**Comment by lumberman** [comment]
Closing for now, please reopen this ticket if problem not solved following my recommendations.
