### ISSUE TITLE
Accordion text is duplicating across multiple boxes

### ISSUE THREAD

**Issue by EmmaDMAU** [live-composer/live-composer-page-builder#1015]
My accordion content has been overwritten, and is duplicating the copy from one box across all the others. I've include screen-grabs of the issues, I was also seeing a bug error showing -  but am now unable to replicate the error icon and message i was receiving. 

The problem below however still stands.

This suddenly started showing like this in my staging site and now i'm unable to deploy anything to live through fear of my site being overwritten with the incorrect / duplicate copy.

![Capture1](https://user-images.githubusercontent.com/57635379/68606280-0436bd80-04a6-11ea-8809-c8612a619999.JPG)
![Capture2](https://user-images.githubusercontent.com/57635379/68606281-0436bd80-04a6-11ea-979a-f0724a80a738.JPG)
![Capture3](https://user-images.githubusercontent.com/57635379/68606282-04cf5400-04a6-11ea-8369-918b656db084.JPG)

**Comment by lumberman** [comment]
Should be fixed in the latest update 1.5.4
