### ISSUE TITLE
Tabs not working proper

### ISSUE THREAD

**Issue by andyrr-kiel** [live-composer/live-composer-page-builder#1016]
We have running many Website with the live compoer plugin und Theme West pro from athemes. Since WP 5.3 and Composer 1,53 the Tabs no more working. The error report:

Live Composer returned JS error
TypeError: n is null
File "https://domain/wp-content/plugins/live-composer-page-builder/js/dist/editor_backend.min.js?ver=1573115006", line 8, char 111565

Greets Andy

P.S. I downgrade to version 1.5.2 of the plugin - that works!

**Comment by andyrr-kiel** [comment]
> 
> 
> We have running many Website with the live compoer plugin und Theme West pro from athemes. Since WP 5.3 and Composer 1,53 the Tabs no more working. The error report:
> 
> Live Composer returned JS error
> TypeError: n is null
> File "https://domain/wp-content/plugins/live-composer-page-builder/js/dist/editor_backend.min.js?ver=1573115006", line 8, char 111565
> 
> Greets Andy
> 
> P.S. I downgrade to version 1.5.2 of the plugin - that works!



> 
> 
> We have running many Website with the live compoer plugin und Theme West pro from athemes. Since WP 5.3 and Composer 1,53 the Tabs no more working. The error report:
> 
> Live Composer returned JS error
> TypeError: n is null
> File "https://domain/wp-content/plugins/live-composer-page-builder/js/dist/editor_backend.min.js?ver=1573115006", line 8, char 111565
> 
> Greets Andy
> 
> P.S. I downgrade to version 1.5.2 of the plugin - that works!

Stop - Version 1.5.2 is another issue, you can not use as example the shortcode plugin. I downgrade now tp version 1.4.x that i can modify the websites.

Greets Andy

**Comment by andyrr-kiel** [comment]
Okee dokee, here i am with some news. I dont know is it a bug in version 1.5.3 or a feature :-). If i install the tab plugin, and open first the option to change the content, click on save, go now to the tab title, i am able to modify the title. The bug i wrote in the entry post is still there, the problem seems, when i first try to modify the tab title, the panel to change or save the modification, stuck the complete website. I hope you can reproduce und fix it.

Greets Andy

**Comment by livecomposer** [comment]
@lumberman I do believe this is a bug. Getting several tickets about it. WP 5.3+ only.

**Comment by lumberman** [comment]
Should be fixed in the latest update 1.5.4

**Comment by andyrr-kiel** [comment]
It is fixed, thanks for quick reaction!
Greets Andy
