### ISSUE TITLE
Cannot edit Accordion Content

### ISSUE THREAD

**Issue by Christian-Seiler** [live-composer/live-composer-page-builder#1020]
Upon clicking the "Open in WP Editor" Button in the Accordion, nothing happens. JS Console reads: [Info] Live Composer: TinyMCE is undefined. (editor_backend.min.js, line 8)

**Comment by lumberman** [comment]
I can't confirm it after testing on my local machine.

Most likely you have some kind of third-party TinyMCE enhancement plugin installed (like TinyMCE Advanced)?

Try disabling all other plugins and see if it helps?

(I'm closing this ticket but feel free to reopen it if problems isn't solved)
