### ISSUE TITLE
Custom Post Types Not Removeable

### ISSUE THREAD

**Issue by jgajera** [live-composer/live-composer-page-builder#1023]
What's going on? We used to be able to toggle whether we wanted the Testimonials, Projects, Staff, Partners, and Galleries, but now we have to let them clutter our Admin pages, even if we never use them? Can you please add that functionality back in to disable these extra custom post types?

**Comment by lumberman** [comment]
It's in the Feature Control section of the Live Composer Settings https://d.pr/i/FJPN4v
