### ISSUE TITLE
Broken image links in project grid/carousel - A non well formed numeric value encountered

### ISSUE THREAD

**Issue by sangaman** [live-composer/live-composer-page-builder#1024]
Using LiveComposer Version 1.5.5 with latest and php 7.4.2 and WP 5.3.2

Image links are broken in the project grid/carousel, it looks like the code causing the error is called when resizing images. Below is an example of one of the broken image links.

```
https://www.kaabeschools.org/<br /><b>Notice</b>:  A non well formed numeric value encountered in <b>/var/www/wordpress/wp-content/plugins/live-composer-page-builder/includes/other-functions.php</b> on line <b>182</b><br /><br /><b>Notice</b>:  A non well formed numeric value encountered in <b>/var/www/wordpress/wp-content/plugins/live-composer-page-builder/includes/other-functions.php</b> on line <b>185</b><br /><br /><b>Notice</b>:  A non well formed numeric value encountered in <b>/var/www/wordpress/wp-content/plugins/live-composer-page-builder/includes/other-functions.php</b> on line <b>187</b><br />https://www.kaabeschools.org/wp-content/uploads/2015/09/IMG_20191114_101044-500x375.jpg
```

In editor mode, making any change whatsoever to the grid module will cause all images to load properly, but when I reload the page the links are broken again.

**Comment by sangaman** [comment]
It looks like `$new_w` has `px` in it, so it's not purely numeric. I have a temporary fix in place that removes px from the end if it's there.

**Comment by lumberman** [comment]
Thanks for reporting this.
