### ISSUE TITLE
font-size in responsive phone no more work

### ISSUE THREAD

**Issue by andyrr-kiel** [live-composer/live-composer-page-builder#1041]
Hi. This time it seems a bug in the live composer. Will i modify the font-size in the reponsive phone, it did not change the font size. Desktop and tablet seems to work fine.

PHP 7.3.x
WP Version 5.4.1
Theme West Pro from athemes

Greets Andy

**Comment by andyrr-kiel** [comment]
I did investigate a bit more in this problem. The problem exist only in the mobile function, desktop and tablet works proper. Please can you fix this issue!

Greets Andy

**Comment by andyrr-kiel** [comment]
Okee dokee i think i found the problem and i´m not sure is it a theme problem or a bug in the livecomposer, see attachment. Desktop works fine, tablet also, but in the phone mode he stripped the font-size away.

Greets Andy

![lc_desktop](https://user-images.githubusercontent.com/57746015/86896937-0e798c00-c107-11ea-8576-784441883f2a.jpg)

![lc_tablet](https://user-images.githubusercontent.com/57746015/86896961-16d1c700-c107-11ea-9b39-268094e57663.jpg)

![lc_phone](https://user-images.githubusercontent.com/57746015/86896976-1afde480-c107-11ea-90da-d583c915a96e.jpg)

**Comment by livecomposer** [comment]
Hi @andyrr-kiel we have tested this extensively using Live Composer 1.5.8 and WordPress 5.5.3 and cannot reproduce it. Cheers!
