### ISSUE TITLE
Update does not resolve the problem

### ISSUE THREAD

**Issue by Leo-domenic** [live-composer/live-composer-page-builder#1051]
I have followed your instructions and uploaded the update. The problem is still exactly the same. 
I have used the free version of LC so far, because I'm still working on my website and wanted to buy the full version once completed. I had only 2 extensions, not the entire package.

I hope, this will help you to resolve the issue. Thanks again for your efforts.

**Comment by livecomposer** [comment]
Hi @Leo-domenic - please visit https://livecomposerplugin.com and use the Chat feature in the bottom right to send us a message and we'll pick up the conversation there.
