### ISSUE TITLE
JavaScript error in Live Composer mode

### ISSUE THREAD

**Issue by doffine** [live-composer/live-composer-page-builder#1052]
Hey there Live Composer team,

we just want to report a JavaScript error showing up in the console when editing a page in live composer mode. It comes up at least in WordPress 5.5. We noted it after updating WordPress to 5.5, so we cannot say if this happens in earlier WordPress versions, too:

`Uncaught ReferenceError: wpColorPickerL10n is not defined
<anonymous> https://[DOMAIN.TLD]/wp-content/plugins/live-composer-page-builder/js/dist/editor_plugins.min.js?ver=1598375894:21
<anonymous> https://[DOMAIN.TLD]/wp-content/plugins/live-composer-page-builder/js/dist/editor_plugins.min.js?ver=1598375894:21
editor_plugins.min.js:21:460`

Hope this helps that you can solve this problem.

Greetings and thank you very much,
-doffine

**Comment by livecomposer** [comment]
Hi @doffine - thanks for sending. Can you verify which version of Live Composer you were seeing this error with? 1.5.8 fixed several issues that arose due to WP 5.5.

**Comment by livecomposer** [comment]
@doffine thanks for sharing. We don't currently have any other reports through our support channel (or at all) of this particular issue so it may be a conflict with another third party plugin. We will make a note and put it on our list. Cheers.

**Comment by doffine** [comment]
Hey @livecomposer,

it is for sure not a conflict with a third party plugin. You can easily reproduce the problem in a fresh WordPress installation.

Go - let's say - to wpsandbox.net, get you a fresh WordPress instance, only install and activate your plugin, open any page in Live Composer and directly see the above JavaScript error in the browser console.

Cheers,
-doffine
