### ISSUE TITLE
Live composer mode error: "Uncaught ReferenceError: wpColorPickerL10n is not defined"

### ISSUE THREAD

**Issue by doffine** [live-composer/live-composer-page-builder#1053]
Hey @livecomposer,

I'm coming back to https://github.com/live-composer/live-composer-page-builder/issues/1052

Since I am not very familiar with GitHub procedures I don't know if I'm doing right to open another issue here. Please excuse me if this approach is wrong. After you closed the issue above I had written another comment where you haven't answered so far. So I suspect that you don't took notice of it.

You wrote that you hadn't any other report to the...

`Uncaught ReferenceError: wpColorPickerL10n is not defined`

...error in live composer mode and that it could have got something to do with 3rd party plugins.

But we showed you that you can take a fresh WordPress like one of wpsandbox.net without any plugin installed but yours, and the error is there. It is easily reproducible. Meanwhile we retried it with WordPress 5.5.1 and the error is still there.

Please try to reproduce the error on your own. You will see it's not because of 3rd party plugins and it should happen in all WordPress installations >5.5.x

Many greetings,
-doffine

**Comment by bibiangel1989** [comment]
You can insert this code in your file **function.php:**
// Fix bug color picker WordPress 5.5 Update Version
if( is_admin() ){
	add_action( 'wp_default_scripts', 'wp_default_custom_scripts' );
	function wp_default_custom_scripts( $scripts ){
		$scripts->add( 'wp-color-picker', "/wp-admin/js/color-picker$suffix.js", array( 'iris' ), false, 1 );
		did_action( 'init' ) && $scripts->localize(
			'wp-color-picker',
			'wpColorPickerL10n',
			array(
				'clear'            => __( 'Clear' ),
				'clearAriaLabel'   => __( 'Clear color' ),
				'defaultString'    => __( 'Default' ),
				'defaultAriaLabel' => __( 'Select default color' ),
				'pick'             => __( 'Select Color' ),
				'defaultLabel'     => __( 'Color value' ),
			)
		);
	}
}

**Comment by doffine** [comment]
@bibiangel1989, thank you very much for coming back to us.

Last question: Will you fix this in an upcoming update of Live Composer?

Greetings,
-doffine

**Comment by bibiangel1989** [comment]
Sorry, i just a user of LC plugin :)

**Comment by bibiangel1989** [comment]
> @bibiangel1989, thank you very much for coming back to us.
> 
> Last question: Will you fix this in an upcoming update of Live Composer?
> 
> Greetings,
> -doffine

Sorry, i just a user of LC plugin :)

**Comment by doffine** [comment]
@bibiangel1989, ah, hehehe, sorry. Then many thanks for your "3rd-party-help" :-)!

As the manufacturer of this plugin seems to have no ambition to do anything at least for weeks about apparent bugs, we now decided to get rid of this page builder and replace it by another one. There are many powerful other page builders out there that get supported in a good way.

Anyway - many thanks!
-doffine

**Comment by livecomposer** [comment]
Hi @doffine we are alive and well and are assuredly making changes to Live Composer when necessary. Our free product is stable and we will definitely fix bugs when necessary. We have active email plugin support for the paid products at https://livecomposerplugin.com. Cheers and best with your projects.
