### ISSUE TITLE
Headers/Footers function is not working in WordPress ver 5.5.1

### ISSUE THREAD

**Issue by bibiangel1989** [live-composer/live-composer-page-builder#1054]
Hi @livecomposer ,
Currently I am using Live Composer for WP 5.5.1. I cannot find the plugin's Headers / Footers editor function.
[This is photo](https://prnt.sc/uiiboa)
Besides the **Preset** function is also not working ... 
Any solution for this ... 

Thanks for great plugin ... 👍

**Comment by livecomposer** [comment]
Hi @bibiangel1989 the Headers / Footers are under the Appearance menu item. Cheers.
