### ISSUE TITLE
WooCommerce shop productlist is not showing (instead generic search result is shown)

### ISSUE THREAD

**Issue by vicuseb** [live-composer/live-composer-page-builder#1055]
I created the page .../winkel/
Assigned it as primary shopping page
Edited the page in Live Composer and added the product list
However when I go to this page I get the generic search result instead of the product list..

Any hints?

**Comment by bandicootmarketing** [comment]
Hi @vicuseb thanks for reaching out. We don't have any global reports of this issue. If you have purchased the WooCommerce extension within the last year please log into your account and reach out via the Support form there and we'd be happy to help. Outside of the WooCommerce extension, Live Composer is not guaranteed to be compatible with WooCommerce in all instances. Cheers and best!
