### ISSUE TITLE
Not compatible with Wordpress 5.6

### ISSUE THREAD

**Issue by Leo-domenic** [live-composer/live-composer-page-builder#1056]
Hello, today I have installed wordpress 5,6, and since then LC doesn't work anymore. It means that it's not possible to drag & drop any element, or even to modify elements. This is basically the same problem that we already had a few months ago, with the wordpress 5.5 update. I hope this can be useful to find a solution, because I cannot work on my website anymore.

Thanks in advance for your efforts!

**Comment by VR51** [comment]
Chiming in in case this helps you. Try the jQuery Migrate plugin https://wordpress.org/plugins/enable-jquery-migrate-helper/

Alternatively you could temporarily revert to the previous version of WordPress. The WP Downgrade plugin can help you with this https://en-gb.wordpress.org/plugins/wp-downgrade/

**Comment by Leo-domenic** [comment]
Thanks for your reply. The jQuery Migrate plugin didn't help. I have downgraded WordPress to 5.5.3, and it works, but of course this can only be a temporarily solution.
As I wrote, the issue seems to be the same that LC had with the upgrade to 5.5. The LC- team had been very kind to find rapidly a solution, so I hope that I can resume my work on my website as soon as possible.
Thanks.

**Comment by VR51** [comment]
WP 5.6 has a number of compatibility breaking changes. I've held all the websites I manage at 5.5.x until plugin developers release compatibility updates. Usually takes about a week for updates to arrive.

I'm glad you were able to rollback successfully and glad I could help you.

**Comment by livecomposer** [comment]
Hi @Leo-domenic - we have successfully tested LC 1.5.9 with WP 5.6 and have found no issues at all. If you are seeing issues, then it will have to do with your specific setup, and could possibly be a conflict with a third party plugin in use. If you would like premium support to help figure it all out, please purchase any one of the paid products at https://livecomposerplugin.com and we'd be happy to help. Cheers and best.
