### ISSUE TITLE
Publish Changes remains faded and changes can not be made on page. 

### ISSUE THREAD

**Issue by raffeb** [live-composer/live-composer-page-builder#1086]
Hi, 
Have a page where most pages does not seem to make possible to update since the most recent update of the plugin. 
I don't know what makes this happen, but the Publish Changes button remain faded so I can not save any published changes on these pages. It seem to work on some pages though, and I have yet to figure out why some do and others don't. I've noticed other users with similar issues, but the solution suggested for them - like update to the latest version - is not making any difference. 
What can I do?

**Comment by egenslab** [comment]
we have released the latest version. please update the latest plugin.
