### ISSUE TITLE
Contentfield blank with array

### ISSUE THREAD

**Issue by andyrr-kiel** [live-composer/live-composer-page-builder#1115]
Since the last Update 1.5.31 or 1.5.30 the conent is gone and the error is:

Array
Array
Array
Array
Array

So whats up?

Andy

**Comment by nitin-blueastral** [comment]
Hello Andy, 

Sorry for the inconvenience caused. Team is already looking into it on highest priority. Can you please send an email with details on below email address.

Regards,
Nitin

**Comment by andyrr-kiel** [comment]
Hi Nitin

It seems not necessary. The developer make a rollback in a new version 1.5.32 and the error is gone! Thx for quick reaction!

Greets Andy
