### ISSUE TITLE
Live composer TypeError: jQuery(...).sortable is not a function error detected while updated to new version

### ISSUE THREAD

**Issue by ARPSOFT-DEV** [live-composer/live-composer-page-builder#1141]
Hi There,
I Have updated the live composer editor plugin to the newer version i.e Version 1.5.44. But after updation the editor is not working. I am attaching a screenshot of error. Please check and let me know the solution for this
![image](https://github.com/user-attachments/assets/e8d32542-e0de-43ce-bc56-854f0c955a21)
![image](https://github.com/user-attachments/assets/6783dea3-cd1a-43a9-98a1-4085a7c7e010)
![image](https://github.com/user-attachments/assets/847a5d65-14d9-4e42-aed0-e546483371fa)

I am waiting for your response. this is urgent. 

Thank You,

**Comment by rahul-blueastral** [comment]
@ARPSOFT-DEV, Would you like to share temporary WordPress credentials over this email support@livecomposerplugin.com, so that the team can assist you better and quicker? Thank you!

**Comment by ARPSOFT-DEV** [comment]
Hi there,
Here are the credentials to check:-

https://development-work.com/accrue/wp-admin
user: - SukhBhathal
pass:- @***@***.***@***@***.***

Thanks & Regards

**Comment by rahul-blueastral** [comment]
Hello,

Could you please share the details via email at support@livecomposerplugin.com? Also, while sharing the details, please provide the unmasked password. Thank you.

**Comment by ARPSOFT-DEV** [comment]
Hi there,
I have shared the credentials with you. Please check and let me know the
solutions.

Thanks & Regards

**Comment by rahul-blueastral** [comment]
We are closing this ticket as this has been taken care internally on our Support Desk.
