### ISSUE TITLE
Responsiveness Isn't working

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#138]
Hey LC,

Tried the master, and it looks like the responsiveness of elements doesn't work.

I have enabled them (on the about page for example) yet it doesn't work. 

See attached :)

<img width="525" alt="screenshot 2016-08-14 22 49 11" src="https://cloud.githubusercontent.com/assets/21025321/17652343/cfacd6f0-6271-11e6-9ad6-2914a125cf22.png">
<img width="427" alt="screenshot 2016-08-14 22 52 19" src="https://cloud.githubusercontent.com/assets/21025321/17652344/cfccb736-6271-11e6-839c-89925b4b9fe5.png">

**Comment by livecomposer** [comment]
I was testing it for two hours on your website and can't find a reason for that bug. 
All works perfectly on our demo server. Will continue investigation on Monday.

**Comment by Deanphillips** [comment]
Okay :)

**Comment by Deanphillips** [comment]
Hey guys! I uploaded the latest one to Skinnytosuperhero.com and he problem happened there too.

Think it's to do with the Josephine theme?!

**Comment by Deanphillips** [comment]
Updated to Orao and blank theme and still had the same issue :)

**Comment by livecomposer** [comment]
Probably linked with #208, can you please test with latest code update?

**Comment by Deanphillips** [comment]
Still doesn't work :(

**Comment by xdima92x** [comment]
@Deanphillips Hi) please provide a link so Ш can help you. What do you use a module? :)

**Comment by Deanphillips** [comment]
http://thesuperhumanlab.com/about/

Any site on my site really has this, and even new sites I've created since too :)

**Comment by xdima92x** [comment]
@Deanphillips Please check)

**Comment by Deanphillips** [comment]
Any update on this guys? :)

**Comment by Deanphillips** [comment]
<img width="481" alt="screenshot 2016-10-05 23 37 41" src="https://cloud.githubusercontent.com/assets/21025321/19134246/cb1fa124-8b54-11e6-874b-6f360cebaf86.png">
<img width="448" alt="screenshot 2016-10-05 23 37 58" src="https://cloud.githubusercontent.com/assets/21025321/19134247/cb640bb6-8b54-11e6-8195-9feac2616544.png">

**Comment by BobaWebDev** [comment]
Same thing. Is it a known issue and fix?

**Comment by lumberman** [comment]
It was happening only on Deans website.
Slobodan are you able to recreate the bug on your end?

**Comment by Deanphillips** [comment]
It still is @lumberman http://www.thesuperhumanlab.com/about/ :/

**Comment by Deanphillips** [comment]
Works fine on skinnytosuperhero.com now (as I think you debugged it) but it doesn't work on thesuperhumanlab.com (like above) 

I've even tried switching to the blank theme

**Comment by BobaWebDev** [comment]
Several Josephine customers reported the issue and I can also replicate it on my installation ( not the demo, demo runs older version ).

Reverting back to a version before 1.1 fixes the problem. So, some change in 1.1 is causing it. I'm assuming in the switch to media queries, it doesn't generate the code properly. 

![lc-bug](https://cloud.githubusercontent.com/assets/4485586/19647711/b16dfb5e-99ff-11e6-8387-8f73dc1dfc2f.jpg)

**Comment by BobaWebDev** [comment]
Went into the code to see what might be causing it.

In the dslc_generate_custom_css() function:

`if ( isset( $single_option['tab'] ) && 'Phone' === $single_option['tab'] ) {`

It's assuming the 'tab' parameter for an option is Phone, so it does not work if it's phone. Needs to be:

`if ( isset( $single_option['tab'] ) && ( 'Phone' === $single_option['tab'] || 'phone' === $single_option['tab'] ) ) {`

Same for tablet.

The second issue is is:

`if ( isset( $module_settings['css_res_p'] ) &&  'enabled' === $module_settings['css_res_p'] ) {`

But $module_settings only contains values of modified options, so if the default value for css_res_p is enabled, it won't be included in $module_settings so that check would return false as if responsive was disabled.

Same for tablet.

**Comment by Deanphillips** [comment]
Yeah. Josephine is the theme I use

**Comment by Deanphillips** [comment]
Has the above been fixed yet, guys? Just as I'll update my main website to the latest theme (thesuperhumanlab.com) if it's not responsive :)

**Comment by BobaWebDev** [comment]
Hi guys,

Any estimates on when the issue will be fixed?
