### ISSUE TITLE
Cursor is not set to pointer for many of the module option controls

### ISSUE THREAD

**Issue by livecomposer** [live-composer/live-composer-page-builder#139]

**Comment by xdima92x** [comment]
@livecomposer Please check - https://github.com/livecomposer/live-composer-page-builder/tree/issue/139

**Comment by lumberman** [comment]
@xdima92x why are you adding more classes into CSS? How it should help us to maintain code in the long run?

All you need is to create :hover rules with cursor:pointer. Make sure to have all these classes in the SINGLE rule, like:
.element1:hover,
.element2:hover {
cursor:pointer;
}

Please create a new branch /issue/139_v2 and some this problem properly again.

Thank you.

**Comment by xdima92x** [comment]
Hi @lumberman Please check - https://github.com/live-composer/live-composer-page-builder/tree/issue/139_v2
