### ISSUE TITLE
Enter not numeric values 

### ISSUE THREAD

**Issue by elfomaniac** [live-composer/live-composer-page-builder#152]
It is bug or feature?
http://prntscr.com/c6p0ha

**Comment by livecomposer** [comment]
So you can enter only numbers and – (minus symbol), right? We introduced this "invisible" slider, so users can easily test the value needed. In some cases, users need to shift elements with negative margins. We definitely can check the number format in the future, though.

Thank you.

**Comment by elfomaniac** [comment]
http://prntscr.com/c6x77a

I can enter letter "E" and "+" and "-" in between didgits.

**Comment by livecomposer** [comment]
I think E can be used as part of number notation. This is how browsers coded and we will come to this latter if needed. 

Thank you.
