### ISSUE TITLE
Social Element does not save new entries

### ISSUE THREAD

**Issue by Christian-Seiler** [live-composer/live-composer-page-builder#171]
The Social Element does not update when entries like FB, Twitter, Linkedin are added or changed. It only updates deletion and layout changes.

**Comment by livecomposer** [comment]
Just tested in version 1.1.2 and all works as expected. 
Please let me know how do I reproduce this bug on my end.

Thank you.

**Comment by Christian-Seiler** [comment]
I draged the module onto the page, which showed then the three default social media buttons. All three with the # link.
When I delete the # from the YouTube field, the corresponding button disappears as expected. When I add my URL for Facebook, Twitter, Linkedin etc the new buttons don't appear (except I put a # in the field). After Confirm / Publish and opening the settings again, all URL are gone.

**Comment by livecomposer** [comment]
Just followed your steps and all works/saves as expected.

– Can you please open website in private/incognito mode and see if the problem still exists?
– Can you please try to enable default theme for a moment and disable all other plugins, to see if this problem is really in our plugin?

**Comment by Christian-Seiler** [comment]
Did all of your suggestions, didn't change anything.

**Comment by livecomposer** [comment]
Can you please create a temporary access for your WP admin and send it via http://livecomposerplugin.com/support/support-request/ ?

I see no other way to help you.

**Comment by Christian-Seiler** [comment]
It seems to be an issue related to Safari (Mac). I can edit the Title entries on Firefox (Mac) and IE (Win).

**Comment by livecomposer** [comment]
Can't reproduce on Safari (Mac) using the latest version of the code.
