### ISSUE TITLE
Accordion not visible on site.

### ISSUE THREAD

**Issue by panchan68** [live-composer/live-composer-page-builder#176]
I composed several stuffs on my site like accordion and multiple module in one row. 

After i updated everything went mission. Its not visible on the site. but whenever i "activate live composer" its still there just not visible to public. Please help

**Comment by livecomposer** [comment]
- Version 1.1.2 installed?
- Do you get any errors JS errors?

It will be easier to debug your problem if you provide a temporary login to WP Admin via http://livecomposerplugin.com/support/support-request/
