### ISSUE TITLE
Live Composer returned JS error

### ISSUE THREAD

**Issue by Christian-Seiler** [live-composer/live-composer-page-builder#179]
I'm getting the following error detected message when I inserted the Container Module:

```
Live Composer returned JS error
Das Objekt unterstützt die Eigenschaft oder Methode "remove" nicht
 File "http://www.christianseiler.ch/wp-content/plugins/live-composer-page-builder/js/builder.all.min.js?ver=1.1.2", line 1, char 29950
```

**Comment by livecomposer** [comment]
I can't recreate this issue in the latest code update GitHub.
Can you please update your LC to the latest version available on GitHub and check again?
What browser do you use?
