### ISSUE TITLE
Feature Request: Shadows with rows

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#184]
Hey guys,

I'd love the ability to have shadows on rows. 

Right now I've been trying to use CSS Hero to make this happen, and it's pretty poor to be honest 

Thanks :)

**Comment by Deanphillips** [comment]
I'm so excited for this :D

**Comment by xdima92x** [comment]
I'm sorry but it's impossible. We will have many problems with code
