### ISSUE TITLE
LC: Presets

### ISSUE THREAD

**Issue by xdima92x** [live-composer/live-composer-page-builder#197]
Presets does not work. I can not register a new preset. https://www.evernote.com/shard/s554/sh/77106093-559f-4d10-8867-e44c318d26d1/0b7ed29df9a6e36a

**Comment by livecomposer** [comment]
@xdima92x Test again please.
Type a preset name and push Enter. Preset should appear on the left in the list of presets.

**Comment by xdima92x** [comment]
@livecomposer done

**Comment by xdima92x** [comment]
@livecomposer Please check - https://drive.google.com/file/d/0B7nJlmCX4yHuSk82S1FDNm4tNFk/view
