### ISSUE TITLE
Horizontal mouse wheel scroll for functionality and styling panels

### ISSUE THREAD

**Issue by livecomposer** [live-composer/live-composer-page-builder#210]
For now scrolling on functionality and styling panels works by holding shift and scrolling.
We should try to add the standard scrolling if possible.

(Also users complain that modules scrolling is slower in FireFox)

https://wordpress.org/support/topic/horizontal-mouse-wheel-scroll

**Comment by lazlot** [comment]
On a Mac the horizontal scroll bar is only visible when scrolling. This is a major problem with using your GUI. Please fix this ASAP. Thanks.

**Comment by livecomposer** [comment]
@lazlot  just swipe with your touchpad, no need to point and click on scroller. I work on Mac and have 0 issues with it.

Users on Windowns should use SHIFT + Scrolling for now.

**Comment by lazlot** [comment]
Unfortunately I do not have a touchpad.

**Comment by lumberman** [comment]
New page builder UI completely solves this problem.
