### ISSUE TITLE
Default preset for WooCoomerce Shop Grid has a dotted border on Row Seperator

### ISSUE THREAD

**Issue by pezomatic** [live-composer/live-composer-page-builder#212]
I assume that the dotted border as the default styling on the Row Separator is a mistake.

![lc_shop_grid_screencapture_1910](https://cloud.githubusercontent.com/assets/21032002/17830583/32a52790-6695-11e6-8582-ffc89204ab44.png)

**Comment by xdima92x** [comment]
@pezomatic Hi) A quick question: Do you use the LC 1.1.4? If not, please update and say if you again get this mistake.
