### ISSUE TITLE
Can not scroll down in Responsive mode

### ISSUE THREAD

**Issue by elfomaniac** [live-composer/live-composer-page-builder#218]
Can not scroll down in Responsive mode. I need to see what I need to edit.
http://prntscr.com/c8yc2r

**Comment by xdima92x** [comment]
@elfomaniac Hi)
1) Do you use the LC 1.1.4? If not, please update
2) Try do deactivate all the other plugins for a minute and see if LC works as expected?
3) Try to activate a default WP theme for a minute and see if LC works as expected?
