### ISSUE TITLE
Changing BG Color in a duplicated Info Box change color in an original Info Box

### ISSUE THREAD

**Issue by elfomaniac** [live-composer/live-composer-page-builder#219]
Changing BG Color in a duplicated Info Box change color in an original Info Box.

After save all duplicated and original BR Colors are the same.

**Comment by xdima92x** [comment]
@elfomaniac Hi) I tested a BG Color. Is works. You can look [this video](https://drive.google.com/file/d/0B7nJlmCX4yHuOUw2NE4zQ2llaUU/view). Do you use a LC 1.1.4? If not, please update.
