### ISSUE TITLE
Row Error ID and std

### ISSUE THREAD

**Issue by carlsdesign** [live-composer/live-composer-page-builder#221]
Hi, 
there is an error on the Row System. 
PHP 7.08 

**Warning: Illegal string offset 'id' in C:\xampp\htdocs\blabla\wp-content\plugins\ds-live-composer\includes\row-system\inc\options-output.php on line 275
Warning: Illegal string offset 'id' in C:\xampp\htdocs\blabla\wp-content\plugins\ds-live-composer\includes\row-system\inc\options-output.php on line 292**

If i uncheck the border. 

**Warning: Illegal string offset 'id' in C:\xampp\htdocs\blabla\wp-content\plugins\ds-live-composer\includes\row-system\inc\options-output.php on line 207
Warning: Illegal string offset 'id' in C:\xampp\htdocs\blabla\wp-content\plugins\ds-live-composer\includes\row-system\inc\options-output.php on line 212
Warning: Illegal string offset 'id' in C:\xampp\htdocs\blabla\wp-content\plugins\ds-live-composer\includes\row-system\inc\options-output.php on line 214**

Just happen on localhost.

**Comment by xdima92x** [comment]
@carlsdesign Hi) A quick question: Do you use the LC 1.1.4? If not, please update and tell if you will get this error.
