### ISSUE TITLE
Slider (Revolution) Module not showing

### ISSUE THREAD

**Issue by lukeperrie** [live-composer/live-composer-page-builder#229]
One of my sites in a multi-site install, the Slider (Revolution) module is not showing as available on the front end, even though it is enabled via the Features Control.

Please see video: https://cl.ly/hEsB

I have other sites in my multi-site network where the Slider (Revolution) module is working as intended.

**Comment by lukeperrie** [comment]
Any updates on this?

**Comment by livecomposer** [comment]
Can't recreate the problem on local multisite install. Needs more testing/data.

Reference:
- http://forum.muffingroup.com/brandon/discussion/1372/revolution-slider-multisite/p1
- http://forum.muffingroup.com/rocco/discussion/749/multisite-revolution-slider-error/p1
- http://forum.muffingroup.com/brandon/discussion/1198/problem-between-multisite-and-revolution-slider-plugin-/p1
- https://wordpress.org/support/topic/get-the-correct-table-prefix?replies=8

**Comment by lukeperrie** [comment]
I don't think it's a multi-site problem specifically because like I said, it works on my other sites. It's just this site. I'm wondering if there is a database issue or something.

**Comment by lumberman** [comment]
Closing issue as can't recreate it. If you find a step by step guide on how I can get this issue on my end – please let me know.
