### ISSUE TITLE
Chrome URL Bar in bottom left corner blocks titles of modules

### ISSUE THREAD

**Issue by lukeperrie** [live-composer/live-composer-page-builder#230]
Since (1.1) update, when in Chrome, when I go to use the arrows to scroll left or right to see additional modules, the grey URL bar blocks the titles of the left-most 3-5 modules. This only does this now because you guys changed the position of where the module titles are on the screen. They were higher up before so that little grey bar in the bottom left of the screen didn't block anything.

Please see video: https://cl.ly/hCup

And screenshot: https://cl.ly/hErf

**Comment by livecomposer** [comment]
Thanks for reporting this. We get great help form you.
In our plans to add additional controls on the level below the modules list, so this problem will solved by itself.

**Comment by lukeperrie** [comment]
If you do that- the level of controls below will be blocked.

Luke

**Comment by lukeperrie** [comment]
This is not an enhancement. It's a bug. I guarantee it's affecting other users as well. It's VERY annoying when you are trying to scroll through the modules to see which ones you want to choose from and half of them are blocked by that grey bar.

**Comment by lumberman** [comment]
Closing this issue as completely new UI is coming soon.
