### ISSUE TITLE
Error in JavaScript error detected in a third-party plugin

### ISSUE THREAD

**Issue by alemacielsilva** [live-composer/live-composer-page-builder#234]
Live Composer show the message in all time and all pages:

JavaScript error detected in a third-party plugin
Script error.
File "", line 0, char 0

Whats is this, please?

Tks!
Alexandre

**Comment by NGorco** [comment]
Hi! Can you tell how to get this bug?

**Comment by alemacielsilva** [comment]
All time and all pages. Show like a tab at the Lice Composer Editor.

**Comment by livecomposer** [comment]
Alexandre,
Please try to install the latest version of the plugin in development: https://github.com/livecomposer/live-composer-page-builder/archive/master.zip

If it doesn't work, please disable all the other plugins for a minute and check if the problem solved in Live Composer. This way we can tell if there is a problem in our plugin or other plugins cause it.

If nothing helps, please let us know, so we can debug it further. 

Thank you.
