### ISSUE TITLE
Windows row additions bug

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#239]
Hi there,

I can replicate this just on Windows. On Mac is no such an issue.
If you add on empty page multiple rows, the LC is break. 

Check this video:

https://www.dropbox.com/s/h9upkn5d41hzkhn/win-bug1.mp4?dl=0

Tested on Chrome and Opera.

Cheers.

**Comment by livecomposer** [comment]
@NGorco Please try to reproduce this bug on your end.

**Comment by lumberman** [comment]
Can't reproduce in Chrome on Windows.
