### ISSUE TITLE
Make editing field for HTML module bigger or in popup?

### ISSUE THREAD

**Issue by livecomposer** [live-composer/live-composer-page-builder#242]
Currently the small box makes it hard to make edits without having to copy/paste it somewhere else.

https://wordpress.org/support/topic/use-wordpress-editor-for-html-module?replies=2#post-8808108

**Comment by FoldingTheme** [comment]
![html_module](https://user-images.githubusercontent.com/21088706/44451362-43a49000-a5fc-11e8-9f01-e2d40a5d2ff0.png)
