### ISSUE TITLE
Drag&drop doesn't work

### ISSUE THREAD

**Issue by bielu** [live-composer/live-composer-page-builder#247]
Hi,
I have problem because d&d stop working without any reason after update plugin "disable comments".
video you have here:
https://snap.ashampoo.com/fwwYdfvt

**Comment by bielu** [comment]
if you need i can give access to website :)

**Comment by livecomposer** [comment]
Hi there,
I'm sorry for delay answering you.

Can you please check the latest version of the plugin in development: https://github.com/livecomposer/live-composer-page-builder/archive/master.zip ?

If not working, try to disable any other plugins for a minute and see if problem solved. This way we will be sure it's error in our plugin not others.

Thank you.

**Comment by lumberman** [comment]
Closing as it most likely fixed in the latest code.
