### ISSUE TITLE
Masonry grid behaves incorrectly in responsive mode (and other issues)

### ISSUE THREAD

**Issue by kkonst** [live-composer/live-composer-page-builder#252]
1) Masonry grid in Galleries acts strange in responsive mode.
-  doesn't have posts per row setting (as well as projects). 
-  doesn't have column spacing setting
-  doesn't react on row separator height
-  Count number is not centered correctly if masonry has horizontal thumbs in it, as well as vertical (not only in responsive mode). 

2) Also, masonry grid jumps a little width and height-wise just after loading. Why it does that? 
3) Searching for a setting in the Responsive styling is still the hardest thing it the whole plug-in. 
4) On-hover animation seems not working to me in Projects and Galleries.
5) Is it possible to apply OnLoad animation to each item in the grid continuously, not for the whole grid ? Like fade-in one-by one or something?

**Comment by livecomposer** [comment]
Hi there,
a quick question: are we talking about the standard **Galleries** module or **Gallery Images Grid** from a premium extension: https://livecomposerplugin.com/downloads/gallery-images-grid/ ?

**Comment by kkonst** [comment]
@livecomposer Both. But in this case I'm talking especially about the standard Galleries module.

Here's a couple of points about the Gallery Images Grid:
https://github.com/live-composer/live-composer-page-builder/issues/329

**Comment by kkonst** [comment]
@livecomposer @lumberman 

Here's an example of a good masonry grid and how it's loading:
http://themes.laborator.co/#theme=kalium

and it should behave the same way with Thumb+title in case of projects and galleries.

**Comment by lumberman** [comment]
@xdima92x please copy user requests form this issue to a new private issue in https://github.com/lumbermandesigns/lc-gallery/issues and start working on it in your free time.

Close this ticket when you create similar ones in the private repo.
Thank you.
