### ISSUE TITLE
Wont' Display Shortcodes Correctly

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#254]
I'm launching a site in a few days and I'm having a big issue with LC displaying things correctly. 

http://12weekmastery.com/forum/ works fine, but the further I get into it (click on a task/post) it disappears:

http://12weekmastery.com/forum/?view=thread&id=1#postid-1

I turned off LC and it works perfectly fine

**Comment by livecomposer** [comment]
If you add these shortcodes via **HTML** module, please enable the next setting: https://www.evernote.com/l/AAFHEjIdbmZM6KCznm_YYs-VEy6dUP_hDPs

**Comment by ElementalCrisis** [comment]
Sorted related, I've done that for the NeXtGen Gallery shortcode and it works until I go back to edit the page and the box is now filled with the Gallery's HTML instead of the shortcode breaking it.

**Comment by livecomposer** [comment]
@ElementalCrisis this is how NextGen Gallery coded. They replace shortcode with HTML version on the fly (not sure why). Due to the way NextGen coded it needs integration extension to work with LC. I have no plans to integrate it with LC any soon, probably other developers can be interested in this.

**Comment by livecomposer** [comment]
@ElementalCrisis You can still output NextGallery using their tools. Just insert the Gallery in the backend editor as you do for the standard WP website. Once it's done, go to Live Composer and drop THE CONTENT module where you want to have gallery placed. This should do the trick.

**Comment by ElementalCrisis** [comment]
Thanks for the info! I'll give that a try!
