### ISSUE TITLE
FEATURE REQUEST: Shadows with blog module

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#261]
Hey guys,

I'd love to add drop shadows on the blog module, so I can shadows like this for example:

http://backlinko.com/blog

**Comment by livecomposer** [comment]
@xdima92x Can you please improve the POSTS and BLOG modules with the box-shadow controls for the each post block as requested here? 

_(Please add these new features when you work on controls migration.)_

Thank you.

**Comment by Deanphillips** [comment]
Brilliant :) Really excited about this :)

**Comment by xdima92x** [comment]
@livecomposer Please check - https://github.com/livecomposer/live-composer-page-builder/tree/issue/261

**Comment by livecomposer** [comment]
@xdima92x 

1. This control should be under the MAIN tab of the module settings.
2. Inner shadow doesn't work as expected
3. Shadows [gets cropped by outer box](https://www.evernote.com/l/AAEd0WY4sfFOOa2-6m5eZhVP5cNivlKx6_o)
4. Add the same control for all the post-based modules.
5. Update changelog in readme with every push.

Thank you.

**Comment by livecomposer** [comment]
@xdima92x I'm still waiting for you on this task. 

– Please verify if we can get rid of overflow:hidden for the container.
– Find a way to disable inner shadow for this case.
– Apply this setting to all the other post-based controls.

Thank you.

**Comment by xdima92x** [comment]
@livecomposer Please check - https://github.com/livecomposer/live-composer-page-builder/tree/issue/261

**Comment by livecomposer** [comment]
@xdima92x I need you to check how these changes done for POST and BLOG module in 7d113ee. Please, create a new branch /issue/261_ver2 and apply the same code changes to the other post-based modules.

**Comment by xdima92x** [comment]
@livecomposer please check - https://github.com/livecomposer/live-composer-page-builder/tree/_issue/261_ver2

**Comment by alanin93** [comment]
Can you add inner shadow for featured blog images please

**Comment by xdima92x** [comment]
@alanin93 Hi) Please open a new issue for these.

**Comment by lumberman** [comment]
@alanin93 Inner shadow will not work for blog posts. Too much trouble for a simple effect.
