### ISSUE TITLE
WordPress link autocomplete issue

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#264]
Hi again,

Check this screen to see the WordPress link autocomplete feature when the LC is disabled:
https://www.evernote.com/l/AjOTSDzHvFBOmq3GlNyADBqzyVy32AdltcoB/image.png

And this one when the page builder is activated:
https://www.evernote.com/l/AjM_Uy4OIt9CnJvRBdjwbewJXgmUx9Qv6w4B/image.png

Sort of conflict? 

Cheers.

**Comment by livecomposer** [comment]
Not a bug, but enhancement. Will be improved later.

**Comment by FoldingTheme** [comment]
feature disabled.
