### ISSUE TITLE
LC JS error

### ISSUE THREAD

**Issue by alipetarian** [live-composer/live-composer-page-builder#269]
I can not edit content and get this error.

https://wordpress.org/support/topic/js-error-lc-no-trabaja/

[VC can not edit content](https://wordpress.org/support/topic/js-error-lc-no-trabaja/)

**Comment by xdima92x** [comment]
Hi @alipetarian 

a) Open your website for editing in a private/incognito mode. Let me know if it's any different.
b) Try do deactivate all the other plugins for a minute and see if LC works as expected?
c) Try to activate a default WP theme for a minute and see if LC works as expected?

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
