### ISSUE TITLE
Devices issue

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#277]
Hey guys,

I'm having issues in two ways with the "show on" buttons.

1) on some elements, I can't actually pick them/turn them off (see attached - I need to remove it from desktop) 

2) When I remove an element from the desktop version, it actually removes it from the editor (so I can't see the thing at all) 

<img width="423" alt="screenshot 2016-09-08 23 58 28" src="https://cloud.githubusercontent.com/assets/21025321/18369866/5224298c-7620-11e6-97ea-4f311dae4070.png">

**Comment by xdima92x** [comment]
@Deanphillips Hi) 
1) I tested the "show on" buttons. It works. Please [check this screencast](https://drive.google.com/file/d/0B7nJlmCX4yHudEVmZ3g4LXBMcGs/view) for more details.
- Do you use the LC 1.1.4? If not, please update
- Try do deactivate all the other plugins for a minute and see if LC works as expected?
- Try to activate a default WP theme for a minute and see if LC works as expected?
2) When you remove an element from the desktop version, it actually removes it from the production but not the editor.
