### ISSUE TITLE
LC blog and Post modules can't show only 1 post but return 2 posts

### ISSUE THREAD

**Issue by IkeTen** [live-composer/live-composer-page-builder#290]
LC blog module can't show only one post in the and post and blog module. It always shows two when set to one.  Its works in the builder but not in the final category arhive front end. 
1. It's a template: Blog Post Archive Index Templates
2. Settings Used: Grid, one post per page, one post per row and apply page query.
The query returns two posts instead of one which is set.

**Comment by livecomposer** [comment]
Hi Isaac,
What about sticky posts setting?

**Comment by IsaacAdu** [comment]
Hi,
Both sticky posts and pagination are disabled.

**Comment by IsaacAdu** [comment]
I was able to trace the cause of the problem. 
The default WordPress post setting page -- Settings>Reading>Blog pages show at most -- was set to show 10 posts. 
This overrides LC posts and blog module settings. 
I don't know if this is how LC is made to work or it's just a bug.

**Comment by livecomposer** [comment]
@xdima92x Can you please check code related to this functionality and see why it's done like this?

**Comment by IsaacAdu** [comment]
@xdima92x  check ut this screencast, [https://dl.dropboxusercontent.com/u/86934117/Untitled%20Screencast%20(2).webm](url)

**Comment by IsaacAdu** [comment]
I resolved this issue with code provided by @xdima92x . `$dslc_query->set('posts_per_page', $options['amount']);
$dslc_query->query($dslc_query->query_vars);`
I placed it in the 'Do the Query' function of the post and blog module.php as seen in the image attached below.
![skitch](https://cloud.githubusercontent.com/assets/22121640/18510981/1b474bc6-7a79-11e6-85b7-abeb38365b0b.png)

**Comment by xdima92x** [comment]
@livecomposer Please check - https://github.com/livecomposer/live-composer-page-builder/tree/issue/290

**Comment by IsaacAdu** [comment]
@xdima92x  I checked it out, it works great only for the Posts module not blog module module.  The blog module still shows the total number of post in the tag or category.

**Comment by xdima92x** [comment]
@IsaacAdu Hi) You need to use post module for archive pages.

**Comment by IsaacAdu** [comment]
Thanks for the info. It's still a problem if the blog module does not respect query rules a user sets regardless were it is placed, be it on the category archive or the blog pages. Thanks.

**Comment by xdima92x** [comment]
@IsaacAdu  Hi, I am not sure what I understood you. 'the blog module does not respect query' - https://www.evernote.com/shard/s554/sh/6c1168ad-faf1-4f97-85ff-29549252a483/dd228f46d1df6dce is it? Can you show an example or do a screencast?

**Comment by IsaacAdu** [comment]
Oh sorry for not coming clear. I just meant that the blog module still shows all posts i category even when it is set to show only one post.  Meaning the fix does not work for the blog module.
