### ISSUE TITLE
Color picker do not update when copy/paste

### ISSUE THREAD

**Issue by livecomposer** [live-composer/live-composer-page-builder#291]

**Comment by xdima92x** [comment]
@livecomposer I tested a color picker. It works. Please [see a video](https://drive.google.com/file/d/0B7nJlmCX4yHuWEQ5cHFRU1VuRm8/view)

**Comment by xdima92x** [comment]
@livecomposer Please check - https://github.com/livecomposer/live-composer-page-builder/tree/issue/291
