### ISSUE TITLE
SyntaxError: Unknown / Unhandled data type(s): 1

### ISSUE THREAD

**Issue by ElementalCrisis** [live-composer/live-composer-page-builder#292]
For some reason I seem to get the following error when duplicating a textbox three times and setting each duplicates width to 4/12. 

`SyntaxError: Unknown / Unhandled data type(s): 1`

`dslc_unserialize/error() builder.plugins.js:294`
`dslc_unserialize/_unserialize() builder.plugins.js:438`
`dslc_unserialize/_unserialize() builder.plugins.js:410`
`dslc_unserialize() builder.plugins.js:444`
`LiveComposer.Utils.decode() builder.all.min.js:4`
`LiveComposer.Utils.update_module_property_raw() builder.all.min.js:4`
`dslc_module_width_set() builder.all.min.js:1`
`<anonymous> builder.all.min.js:1`
`n.event.dispatch() 1load-scripts.php:3`
`n.event.add/r.handle() load-scripts.php:3`

**Comment by livecomposer** [comment]
Hi @ElementalCrisis,
I can't recreate this problem on my end.

Can you please help me?

1. What browser and OS do you use?
2. What exactly steps I should take to recreate this issue?
3. Do you have this problem in other browsers?
4. What happen if you try to do the same in Incognito Window/Tab?

Thanks for you help!

**Comment by ElementalCrisis** [comment]
Hello,

For some reason I was able to reproduce it was ease last night when I first encountered it, now I can't no matter what I try. Probably something I did on my end that caused the issue though I have no idea what that was. Since then I have restarted my computer once and closed and re-opened FireFox multiple times.

Here's the information you asked for. 

1. Firefox 48.02 X64, Windows 10 Home X64
2.  I add one textbox, added my content in the WP Editor mode, set the width to 4/12 and duplicated it twice. All the textboxes would become grayed out and I would get that error. 
3. Only tried in Firefox, since I can't reproduce either anymore I am unable to say if this is an error happens in other browsers. Tried in Edge and was also unable to reproduce. 
4. Same results as above.

**Comment by talesg** [comment]
Hi @livecomposer,

i was having the same issue in a live site and decided to use a local clean install (WP+LC only) to test it out. 

I discovered that this error start happening after pasting (CTRL+V) text into the editor (inline or modal), for both Infobox and Text Modules. If you paste simple text, is fine. If you paste any text that was originally HTML with properties (for example, copying a paragraph from another page <p class="foo">Text</p>) the issue occurs.

Once text is pasted, the element and their copies are bugged and 2 things happen:
1. They can't be resized ( Issue #298 ).
2. Their style settings are linked together.
3. The opacity of the duplicated item is 0 (it becomes visible only after Publish + Refresh)

-

`error	@	builder.plugins.js?ver=1.1.4:300`

**Comment by ElementalCrisis** [comment]
Interesting, I never thought about that but the text in question had been copy/paste into a text module.

**Comment by ElementalCrisis** [comment]
Yeah, seems once you copy text with HTML properties into a textbox like @talesg mentioned, that textbox's properties becomes unchangeable.

**Comment by livecomposer** [comment]
@talesg what about this bug in the latest update?

I still can't recreate it in the new update following your hint. Can you please check on your end in version 1.1.4?

We fixed some copy/paste bug in the update and I'm wondering if it's linked with the issues you describe.

**Comment by talesg** [comment]
@livecomposer i made a [video](https://dl.dropboxusercontent.com/u/987327/videoc.mp4). 

The paragraph copied is from LC website. A `<h2>` with `<strong>` inside. Using 1.1.4.

Thanks.

**Comment by talesg** [comment]
Hi @livecomposer, @lumberman,

This issue was making duplication of modules and rows impossible, so i had to try finding a fix.
 
I found out a possible solution. It works, but i don't know if it's the best solution.

It is a problem of the unserialize function (dslc_unserialize) in builder.plugin.js. The bug occurs after pasting some special characters such as **'** or **´** . 

-

The solution consists in changing builder.plugins.js, line 264, **var utf8Overhead**, from:
```
   var utf8Overhead = function (chr) {
     // http://locutus.io/php/unserialize:571#comment_95906
     var code = chr.charCodeAt(0)
     var zeroCodes = [
       338,
       339,
       352,
       353,
       376,
       402,
       8211,
       8212,
       8216,
       8217,
       8218,
       8220,
       8221,
       8222,
       8224,
       8225,
       8226,
       8230,
       8240,
       8364,
       8482
     ]
     if (code < 0x0080 || code >= 0x00A0 && code <= 0x00FF || zeroCodes.indexOf(code) !== -1) {
       return 0
     }
     if (code < 0x0800) {
       return 1
     }
     return 2
   }
```

To

```
 var utf8Overhead = function (chr) {
        // http://phpjs.org/functions/unserialize:571#comment_95906
        var code = chr.charCodeAt(0);
        if (code < 0x0080) {
            return 0;
        }
        if (code < 0x0800) {
            return 1;
        }
        return 2;
    };
```

-

To replicate the original issue, just copy and paste some text with a special character like **'** .

For example, this excerpt (from LC Website) causes the problem:

> Don**’**t make any compromises. Speed and performance will remain to be the strong points of your website.

There is the ' of Don**'**t. But if you copy after 'make', the bug doesn't occur. 

Also happens with characters such as **á,í** and so on.

-

I went by trial and error and ultimately found this possible fix by trying the new code (found on [this comment](https://github.com/twostairs/node-socket-laravel-session/issues/1#issuecomment-126772695)).

Also, the same issue was reported here:
https://github.com/kvz/locutus/issues/109
https://github.com/kvz/locutus/issues/257

**Comment by lumberman** [comment]
Thank you.
The code causing issues now removed.

The problem should be fixed in the new update. 

Please try this version https://github.com/live-composer/live-composer-page-builder/archive/master.zip when you have time.

**_Full site backup required before trying any of our code in development._**

**Comment by ElementalCrisis** [comment]
Just tried the Dev version. 

All my presets we're reset and when I try to restore them I get the following error. 

```03:21:50.402 SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 1 column 28 of the JSON data
dslc_generate_section_code/</<()builder.all.min.js:1
.each()load-scripts.php:2
n.prototype.each()load-scripts.php:2
dslc_generate_section_code/<()builder.all.min.js:1
.each()load-scripts.php:2
n.prototype.each()load-scripts.php:2
dslc_generate_section_code()builder.all.min.js:1
dslc_generate_code/<()builder.all.min.js:1
.each()load-scripts.php:2
n.prototype.each()load-scripts.php:2
dslc_generate_code()builder.all.min.js:1
window.previewAreaTinyMCELoaded()builder.all.min.js:4
<anonymous>jmm:2568
1builder.all.min.js:1:6697
