### ISSUE TITLE
Width control overlay

### ISSUE THREAD

**Issue by livecomposer** [live-composer/live-composer-page-builder#297]
[Screenshot with the problem](https://www.evernote.com/l/AAFZEkbPCxhDVYruiHjYNYGJMIO5MIWq5Ig).

**Comment by ElementalCrisis** [comment]
I was also having this problem with the row options not allowing me to select a width for my textbox.

![firefox_2016-09-13_18-41-07](https://cloud.githubusercontent.com/assets/9443295/18497276/b2d42970-79e1-11e6-8bee-d1ad26cfe909.png)

I applied this fix and also had to add the following to get it to work.

```
.dslca-change-width-module-options {
    z-index: 99999;
}

.dslca-modules-section-manage {
    z-index: 9000;
}
```

![firefox_2016-09-13_18-42-15](https://cloud.githubusercontent.com/assets/9443295/18497289/d015dcb8-79e1-11e6-85e7-30fc9a62483a.png)

**Comment by xdima92x** [comment]
@livecomposer please check - https://github.com/livecomposer/live-composer-page-builder/tree/issue/297
