### ISSUE TITLE
JS Error When Changing Item Width

### ISSUE THREAD

**Issue by ElementalCrisis** [live-composer/live-composer-page-builder#298]
I was trying to make a textbox width 6/12 and even though the editor showed it at 6/12, when viewing the page it was still full width. As I wasn't getting any sort of error message in Firefox I switched to Edge and got the following error message. 

Live Composer returned JS error
Exception thrown and not caught
`File "http://localhost/jmm/wp-content/plugins/live-composer-page-builder/js/builder/builder.plugins.js?ver=1.1.4", line 300, char 6`

**Comment by ElementalCrisis** [comment]
Actually seeing this error pop up on just about any item now.

**Comment by livecomposer** [comment]
Does the Chrome return the same problem?

**Comment by livecomposer** [comment]
Can you export the code of the page were you have this issue and send it to me via http://snippi.com ? I try to reproduce this bug on my end but can't.

**Comment by livecomposer** [comment]
Also can you please add this line into your wp-config.php file?
`define( 'SCRIPT_DEBUG', true );`

**Comment by ElementalCrisis** [comment]
Changed `define( 'SCRIPT_DEBUG', false);` to `define( 'SCRIPT_DEBUG', true );`.

Chrome displays this error message.

Live Composer returned JS error
Uncaught SyntaxError: Unknown / Unhandled data type(s): 1
`File "http://localhost/jmm/wp-content/plugins/live-composer-page-builder/js/builder/builder.plugins.js?ver=1.1.4", line 300, char 12`

Here's a video if it in action.

[JS-Bug-Chrome.zip](https://github.com/livecomposer/live-composer-page-builder/files/470771/JS-Bug-Chrome.zip)

Here's the page code
http://snippi.com/s/jogib8g

**Comment by lumberman** [comment]
should be fixed now.
