### ISSUE TITLE
Sync image alt with the one set in WP 

### ISSUE THREAD

**Issue by livecomposer** [live-composer/live-composer-page-builder#302]
Sync image alt and title field values with the ones set in WP

**Comment by xdima92x** [comment]
@livecomposer Please check - https://github.com/livecomposer/live-composer-page-builder/tree/issue/302

**Comment by lumberman** [comment]
@xdima92x please copy user request form this issue and from #252 to a new private issue in https://github.com/lumbermandesigns/lc-gallery/issues and start working on it in your free time.

Thank you.

**Comment by lumberman** [comment]
@xdima92x close this ticket once you copy it to the new repository.

**Comment by lumberman** [comment]
Not ready. Needs a new approach.

**Comment by xdima92x** [comment]
Hi @lumberman Please check this issue - https://github.com/live-composer/live-composer-page-builder/issues/348

**Comment by lumberman** [comment]
@xdima92x you don't sync title / alt values with the ones from WP. In your code, you just replace the values set by the user with values form WordPress. It's not what we are looking for.

If WordPress Image has ALT value it should appear in the module settings > ALT field.
If user set new ALT value it should override the value in WordPress image.

**Comment by xdima92x** [comment]
Hi @lumberman Please check this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/302_v2

**Comment by xdima92x** [comment]
Hi @lumberman please check - https://github.com/live-composer/live-composer-page-builder/tree/issue/302_v2
