### ISSUE TITLE
Image module background colour overlapping issue

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#304]
Hi there,

Please check this screenshot: 
https://www.evernote.com/l/AjPPXP636CxJ-KqUMd-aSvF2TKfosPEDWdYB/image.png

The issue is displayed on both background options (block and image).

Cheers.

**Comment by xdima92x** [comment]
@FoldingTheme Hi) It is a done. You can download a branch 'master'. :)
