### ISSUE TITLE
Can not change the width of the Title box

### ISSUE THREAD

**Issue by thecomputeraide** [live-composer/live-composer-page-builder#306]
I noticed this problem. When i have a Title box with a Text box below I can not change the width of the Title box. Is this me or is it a bug?
![untitled](https://cloud.githubusercontent.com/assets/13575162/18512004/fb033736-7a54-11e6-9145-65fbef015333.png)
![untitled2](https://cloud.githubusercontent.com/assets/13575162/18512006/fda465e6-7a54-11e6-9b3b-f3c1b5689893.png)

**Comment by ElementalCrisis** [comment]
I had a similar issue and posted my temporary solution here https://github.com/livecomposer/live-composer-page-builder/issues/297, I should work for you as well.
