### ISSUE TITLE
Drop Downs do not work when clicking on arrows.

### ISSUE THREAD

**Issue by thecomputeraide** [live-composer/live-composer-page-builder#307]
I found another issue. This one is minor (see image)
![untitled000](https://cloud.githubusercontent.com/assets/13575162/18512041/2cf7872e-7a55-11e6-8278-904618b6b4cc.png)

**Comment by xdima92x** [comment]
@thecomputeraide I tested drop downs. It works.
1) Do you get an errror in the [Error Detected](https://livecomposerplugin.com/blog/live-composer-1-1-released/#js-error)?
2) Try do deactivate all the other plugins for a minute and see if LC works as expected? 
3) Try to activate a default WP theme for a minute and see if LC works as expected? 
4) What module are you using?

**Comment by lumberman** [comment]
Fixed
