### ISSUE TITLE
LC: Archive Template does not work

### ISSUE THREAD

**Issue by xdima92x** [live-composer/live-composer-page-builder#308]
1) Why not button ['Edit Template'](https://www.evernote.com/shard/s554/sh/22a5f52d-9d2d-43a9-a30c-ae718b45a066/459a0e45413a7a35)? 
2) URL + LC does not wok + JS Error - https://www.evernote.com/shard/s554/sh/e68fa4a0-5ddd-408a-a0ac-6005e6e4c93e/4c5b3fe292592000

**Comment by xdima92x** [comment]
@lumberman Please check - https://github.com/livecomposer/live-composer-page-builder/tree/issue/308

**Comment by lumberman** [comment]
#308
