### ISSUE TITLE
Z-index issue for "Navigation" module

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#316]
On the last plugin update, the navigation module has a problem in displaying the submenu items and drop-down which is hidden by the row bellow. 

https://www.evernote.com/l/AjMf1qjvjsRBFpm6hhjcl5cPgOrujATfZ74B/image.png

I was able to fix that adding to the navigation row an ID and setting a big z-index value.

**Comment by xdima92x** [comment]
@lumberman Hi) I can not understand why do you add the property ['z-index:0'](https://www.evernote.com/shard/s554/sh/2dfa0cad-6805-471c-8541-56cc6811ddaf/12cd91efb52f6b68)? I deleted and tested. It works.

**Comment by xdima92x** [comment]
@FoldingTheme @lumberman Please check - https://github.com/livecomposer/live-composer-page-builder/tree/issue/316
