### ISSUE TITLE
Copying elements (creates presets)

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#317]
Hey guys,

I've realised that when I copy an element, it creates presets (doesn't actually mark them as presets though) so when I make a change on the original element, or copied element it applies them to all, which is meaning I'm in a constant loop

D

**Comment by talesg** [comment]
I believe it is a consequence of #292 . Happens after copy+paste special characters.

**Comment by lumberman** [comment]
The problem should be fixed in the new update. 

Please try this version https://github.com/live-composer/live-composer-page-builder/archive/master.zip when you have time.

**_Full site backup required before trying any of our code in development._**
