### ISSUE TITLE
FEATURE REQUEST: Exclude module from main listing

### ISSUE THREAD

**Issue by xdima92x** [live-composer/live-composer-page-builder#324]
https://www.evernote.com/shard/s554/sh/fbdc62dd-1aad-4f53-bc8f-7180c349b7cc/0fa03b00d4e2c173

**Comment by xdima92x** [comment]
@lumberman Hi) Please check - https://github.com/live-composer/live-composer-page-builder/tree/issue/324

**Comment by lumberman** [comment]
@xdima92x See my comment in code.

**Comment by xdima92x** [comment]
@lumberman I changed the code. You can check.
