### ISSUE TITLE
"Inner" box-shadow for blog not there? 

### ISSUE THREAD

**Issue by alanin93** [live-composer/live-composer-page-builder#325]
Hi.

I read in the patch notes that you added "inner" box-shadow effects for projects and blog posts.

The problem is: The "inner" option is only available for regular image modules. But not for blog or project modules.

Am i doing something totally wrong here or no? please let me know whats up.

**Comment by xdima92x** [comment]
Hi @alanin93 The "Inner" box-shadow was deleted because will be many problems with the module.

**Comment by alanin93** [comment]
I fixed it months ago.
Put a little tweak in the source and it worked flawlesd

Den 4. apr. 2017 1.11 PM skrev "Dima" <notifications@github.com>:
