### ISSUE TITLE
Live Composer returned JS error

### ISSUE THREAD

**Issue by zakiyfadhilmuhsin** [live-composer/live-composer-page-builder#327]
Cannot read property 'dslc_carousel' of undefined
File "http://eviterstudio.epizy.com/wp-content/plugins/live-composer-page-builder/js/builder.all.min.js?ver=1.1.4", line 3, char 30070

**Comment by lumberman** [comment]
The problem should be fixed in the new update. 

Please try this version https://github.com/live-composer/live-composer-page-builder/archive/master.zip when you have time.

**_Full site backup required before trying any of our code in development._**
