### ISSUE TITLE
HTML module break when 'textarea' tag is used

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#328]
Hi there,

When an HTML code what contain "textarea" is used in an "HTML module", even the code pass the "Error proof", it breaks the layout. [Check this screencast](https://www.dropbox.com/s/c4fm9sm44auslkv/demo-textarea-html-module.mp4?dl=0). When the page is edited again, the code disappears from the module. [See this screenshot](https://www.evernote.com/l/AjO8CYX1YUFE9Zoe3WCoZE9_wNwioRI3TyQ). 

Cheers.

**Comment by xdima92x** [comment]
Duplicate #573
