### ISSUE TITLE
Gallery Images Grid issue. 

### ISSUE THREAD

**Issue by kkonst** [live-composer/live-composer-page-builder#329]
It takes 15+ seconds for Masonry to load w/ clear cash and at the end of loading it jumps to fill the page width. "Galleries" module does that too and that's annoying. 
Check it out [here](http://kkonst.com) and [here](http://kkonst.com/retouching)

For $9 it seems reasonable to have also:
- faster (using small and light thumbs)  and visually **smoother**  loading (with custom animation, like fade one-by-one, and so on)
- infinite scroll, so it wouldn't have to load 100 images in one try. 
- better way of drug&dropping 100+ images in one Gallery like better structuring; drugging multiple images ; a way of choosing where to load images, to the top or to the bottom.
- a setting for the number of images loading per each next load. 
- at least some styling settings for the lightbox. 
- Windows 10 gestures support.

**Comment by menachemshapiro** [comment]
I'd like to add my voice to this. I'm using the premium gallery module here: https://bananabeachcr.com/weddings   -- Because of the time it takes the gallery module to load all the pictures and therefore the entire page, I've had to limit the amount of pictures I put on the page as well as resize the pictures to smaller than I would like. 

Using thumbnails instead of the full size image in the masonry grid would greatly improve load time. 

Thanks

**Comment by lumberman** [comment]
@xdima92x please copy user request form this issue and from #252 to a new private issue in https://github.com/lumbermandesigns/lc-gallery/issues and start working on it in your free time.

Close this ticket and #252 when you create similar ones in the private repo.
Thank you.

**Comment by menachemshapiro** [comment]
Is there a timeframe for when an updated premium module will be available? When there is an update, how will we (the people who have purchased the module) be notified?

**Comment by kkonst** [comment]
@lumberman @xdima92x 

https://github.com/lumbermandesigns/lc-gallery/issues seems not working.

**Comment by menachemshapiro** [comment]
Is there any update with this? I want to continue using the premium gallery module but I really need the ability to resize the thumbnails.
