### ISSUE TITLE
Module export icon is not working

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#330]
When the DS_LIVE_COMPOSER_DEV_MODE, set it to true, the "export" icon is attached to the module options panel but is not opening any window.

Cheers.

**Comment by lukeperrie** [comment]
Is this fixed in 1.1.4.8?

**Comment by lumberman** [comment]
Fixed version in master now.
Thanks for finding this problem.

**Comment by lukeperrie** [comment]
Ok so this was NOT fixed in 1.1.4.8, correct?

**Comment by lumberman** [comment]
No, it was fixed 14 hours ago as described in this notice: https://cl.ly/0V3n2d2t3H2x
Is there a reason you thought it was fixed in 1.1.4.8?

**Comment by lukeperrie** [comment]
No not at all - just wasn't clear on what you were saying in your message. Thanks so much - I'll grab the latest version today!
