### ISSUE TITLE
Cannot open WP Editor in v1.1.4

### ISSUE THREAD

**Issue by Eliesu** [live-composer/live-composer-page-builder#334]
Uncaught TypeError: Cannot read property 'body' of undefined
File "http://....../wp-includes/js/tinymce/tinymce.min.js?ver=4401-20160726", line 11, char 26961

**Comment by lumberman** [comment]
Should be fixed in the new version. 

Please try this version https://github.com/live-composer/live-composer-page-builder/archive/master.zip when you have time.

**_Full site backup required before trying any of our code in development._**
