### ISSUE TITLE
LC disable WP 4.5 TinyMCE's Inline Link Toolbar

### ISSUE THREAD

**Issue by tristanleboss** [live-composer/live-composer-page-builder#335]
Hello,

When LC is activated, it disables the Inline Link Toolbar of TinyMCE: https://make.wordpress.org/core/2016/03/28/the-editor-in-wordpress-4-5/

Indeed, it reverts the link button to an old popup with fields to enter a link manually.

The culprit is in file ./includes/scripts.php

	public static function add_tinymce_plugins( $plugins ) {

		$plugins['link'] = DS_LIVE_COMPOSER_URL . 'js/tinymce/link.plugin.min.js';
		//$plugins['unlink'] = DS_LIVE_COMPOSER_URL . 'js/tinymce/unlink.plugin.js';
		return $plugins;
	}

Once you comment the first line (the second is already commented in current version), everything goes back to normal.

**Comment by lumberman** [comment]
For now I disable link/unlink buttons for the inline editor.
