### ISSUE TITLE
ERROR internal links in text module

### ISSUE THREAD

**Issue by rosamor333** [live-composer/live-composer-page-builder#337]
Hello

I notice that in txt module, wp content there is no icon for internal links as the old version of live composer has.

I send 2 srcreenshots, in order you see, one of a web I didn´t instal new version, that appears in the menu of tkxt module, and then another where you can see in the new version that is not at the menu...

It´s important for doing links to all modules in the web, could you inform about it

tks, b rgds
Rosa
![captura de pantalla 2016-10-14 10 42 44](https://cloud.githubusercontent.com/assets/22834181/19386894/31734c32-9217-11e6-8441-19c64d62d086.png)
![captura de pantalla 2016-10-14 11 03 39](https://cloud.githubusercontent.com/assets/22834181/19386895/317b6296-9217-11e6-8c20-3347a24777f1.png)

**Comment by lumberman** [comment]
Hi Rosa,
Do you have this editor button in the standard post editing screen?

It looks like a button from the custom plugin. I can't remember seeing this before in my WP. There is no such button in my default WP editor as well.

Thanks for your help.

**Comment by rosamor333** [comment]
Hello again

No, this box is the OPEN IN WP EDITOR that you open when adding text in TEXT MODULE (in live composer). I have one web with the old plugin version, and if you see my first shotscreen, it appears an icon just to insert internal links in an easier way...

In last version plugin, that is the second image, this icon doesn´t appear, and you will have to insert the code in HTML if you want to insert an internal link going to this TEXT MODULE from anywhere you want.

I think it´s missing in new version, but it´s important to work with links in one web.

See my new attached image, the txt module I´m talking about is the WP EDITOR that you open when you are adding text in live composer TXT MODULE.

Tksssss again

![captura de pantalla 2016-10-22 12 10 40](https://cloud.githubusercontent.com/assets/22834181/19618642/c150dd08-9850-11e6-9741-8bfc7df87f02.png)

**Comment by lumberman** [comment]
There is no such button in the standard WP installation without LC plugin active. I believe they removed this button from WP editor by default. Live Composer just follow the functionality you have in the standard WP editor, so I can do nothing about his unfortunately.

<img width="991" alt="screen shot 2016-11-12 at 8 07 38 pm" src="https://cloud.githubusercontent.com/assets/1384471/20243424/b7a903f6-a913-11e6-8cdb-fcec58246ac7.png">
