### ISSUE TITLE
"refresh-on-change" is not working.

### ISSUE THREAD

**Issue by bibiangel1989** [live-composer/live-composer-page-builder#341]
Hi LC team,
Whether you are in the process of developing features that developers can create extensions? When will you be able to release it? 
I'm a developer theme, and I used LC from the early days it appears. Currently, I still use version 1.0.8.4. However, I am trying to use the latest version of the plugin to integrate with my modules. And I met a lot of difficulties with it. I'm wondering about the structural changes in your code. Example: "refresh-on-change" is not working with scripts of my module ( you can see video here: https://youtu.be/73v5kqORU2c ). It only works when the page reloads. And I guess it does not load ajax js as the old version. 
Similar to adding a new icon for the plugin. In older versions are simple: http://prntscr.com/cw5ysa . I just code function merge with "$dslc_var_icons", and enqueue CSS style. But in the new version, it does not recognize my CSS file icon in a customs area: http://prntscr.com/cw5ydm . Although when I add it, still good display in the Front-end view: http://prntscr.com/cw61n8.
Your document is too little supply to the intensive development. Reading your code is very time-consuming, although you write good code. I hope soon to know when you can release version or the documentation for developers. Or any solution for this issue?
All above, great plugin. Thanks, LC team !

**Comment by lumberman** [comment]
@bibiangel1989 Thanks for your involvement!

Live Composer code changes quickly now as we optimize it for performance and moving most of the functionality into JS.

I will answer your questions in details in a few hours.

**Comment by bibiangel1989** [comment]
I've waited a long time, any solution for this issue ??? :)

**Comment by xdima92x** [comment]
Hi @bibiangel1989 Could you update the plugin to 1.2 version and let me know if still have troubles?

**Comment by FoldingTheme** [comment]
#901
