### ISSUE TITLE
Post module "loading more" pagination issue on template

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#342]
Hi there,

When the "Post module" is used on a single post template, the "load more" pagination load the same posts.

https://www.evernote.com/l/AjME42JyYiZDn7f1KgAyf-lqiP_oVzQbYv0

Cheers.

**Comment by lumberman** [comment]
Can't fix due to architecture of the module. In any case it seems like not very logical to have LOAD MORE feature in single post template.

**Comment by xdima92x** [comment]
Please check this - https://github.com/live-composer/live-composer-page-builder/issues/448
