### ISSUE TITLE
Edit Mode - Tablet ( Class )

### ISSUE THREAD

**Issue by xdima92x** [live-composer/live-composer-page-builder#345]
https://www.evernote.com/shard/s554/sh/1d56af28-d389-465f-9a1e-5e461de92027/9af9d532f976d3726770f66195840c43

**Comment by lumberman** [comment]
I can't reproduce this problem. Please, let me know step-by-step instruction on how to get this bug.

Thank you!

**Comment by lumberman** [comment]
@xdima92x I'm waiting for you on this.

**Comment by xdima92x** [comment]
@lumberman Hi :) You can close this problem because I can't reproduce it. Probably I updated the master branch and the bug was gone.
