### ISSUE TITLE
Make sure all the modules with images has alt tags option

### ISSUE THREAD

**Issue by lumberman** [live-composer/live-composer-page-builder#348]
- [ ] Images in Infobox module

23497

**Comment by xdima92x** [comment]
Hi @lumberman Please check - https://github.com/live-composer/live-composer-page-builder/tree/issue/338

**Comment by lumberman** [comment]
No @xdima92x, we need  the ALT and TITLE strings to be taken form the image data in the WordPress

<img width="1115" alt="screen shot 2016-12-03 at 12 42 02 pm" src="https://cloud.githubusercontent.com/assets/1384471/20861785/f1971d26-b955-11e6-8627-433768212515.png">

We need it for all the modules where images used, not only infobox.

**Comment by xdima92x** [comment]
Hi @lumberman Please check this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/348_v2

1) I added the alt and title option for the module InfoBox. You can sync image alt and title field values with the ones set in WP for the module Image and InfoBox. This is the issue - https://github.com/live-composer/live-composer-page-builder/issues/302

2) I checked all the modules where images used. The title string doesn't take from the image data in the WordPress. The list of modules that are fixed:
- Blog
- Posts
- Projects
- Woo Products
- Testimonials
- Partners
- Galleries
- Downloads
- Staff
- Thumbnail
- Gallery Slider
- Project Images Slider

**Comment by xdima92x** [comment]
@xtiger15x Create a new branch
