### ISSUE TITLE
Header/Footer Functionality

### ISSUE THREAD

**Issue by jessicahawkins3344** [live-composer/live-composer-page-builder#354]
I've figured out that when I enable the header and footer - it causes me a whole slew of problems. First, I was trying to only use and call a footer in my theme, but if I don't use the header, the LC assets don't all get enqueued for some reason. And when I do use the header - I am seeing that "Welcome To WordPress heading"... I know this is an error on my part, but what am I missing? I would love to be able to use that feature - I've built 30+ sites with LC and decided I'd like to give it a try!

**Comment by xdima92x** [comment]
Hi @jessicahawkins3344 I'm sorry for kept waiting for so long. Since the plugin had multiple updates let me know if still need assistance.

**Comment by xdima92x** [comment]
If you have more questions about this, please write here.
