### ISSUE TITLE
Custom fonts on post templates aren't working

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#361]
Fonts on other pages all render fine BUT on post template type:

http://design.oliluke.com/boom-test-post-one/

**Comment by lumberman** [comment]
Hey Dean,
Can you please show me the page where fonts are working fine? 

I can't see you load Brandon Grotesque font from any server, local or remote.

**Comment by Deanphillips** [comment]
http://design.oliluke.com/home/

:) @lumberman

**Comment by lumberman** [comment]
You have no call to the adobe TypeKit server from http://design.oliluke.com/boom-test-post-one/ page, so none of the custom fonts were loaded. Please, check the settings you are using to insert custom TypeKit code on the pages and make sure it outputs for all the pages and posts.

Let me know if I can help more with this.

PS: Dean, you should start selling designs via our website. Pages and section templates are looking great when you design it.
