### ISSUE TITLE
The html-paste module doesn't work properly

### ISSUE THREAD

**Issue by viktort8888** [live-composer/live-composer-page-builder#363]
Hello, can you please help me with this issue.
I am trying to paste an HTML code and CSS of a specific search form (here is the link http://codepen.io/nicolasjengler/pen/ZGqjGV).
Unortunately, as a result I get displayed only the search input field and some small search button icon, which looks completely different than the one on the link.
As I have no knowledge in html coding, maybe I do smth wrong with synthaxys? Or, in general, these type of third-party-scripts do not fit the wordpress standards?

Thanks a lot in advance for your reply!

**Comment by lumberman** [comment]
Hi Victor,
Sorry for a late response.

You are not supposed to put JS code into HTML module. For this purpose you should create a module for Live Composer or a shortcode based on code from codepen.

**Comment by viktort8888** [comment]
Hi, thank you for reply.

Seems I inserted the wrong link on codepen, here is the right one http://codepen.io/ChenCody/pen/yOgBwb
with no JS
but still it doesn't work.

**Comment by lumberman** [comment]
Works fine on my end. 

Make sure to wrap CSS with <style></style> tags.
