### ISSUE TITLE
How to create template for pages?

### ISSUE THREAD

**Issue by Dudaevskiy** [live-composer/live-composer-page-builder#364]
Very grateful for Your work! Quite often faced with the change of elements or the size of the page block, in consequence of which it is necessary to alter all pages of your website that you need a lot of time. How to apply teplit LC for pages?

**Comment by Deanphillips** [comment]
Can you explain this more please? I'm confused as to what you're asking :)

Thank you

**Comment by Dudaevskiy** [comment]
Sorry for my English, I write through the online translator. I need a topic (like how to post, staff.....). In order that we could apply the theme live composer for pages.Thank you.

**Comment by lumberman** [comment]
Please, go to **WP Admin > Appearance > Templates** and create a new template for the post types needed. Here is an article in our docs describing how to work with templates: https://livecomposer.help/article/127-post-templates

Let me know if you need more help with that.

**Comment by Dudaevskiy** [comment]
The fact of the matter is that I can create a template for any type of chrome WordPress.

**Comment by lumberman** [comment]
You can save predefined template and load it once you start working on a new page.
https://www.evernote.com/l/AAHXanHtj0tHQIIjLXmTKvNTE0JshH7yOwA

**Comment by Dudaevskiy** [comment]
About this method, I know, the problem is that if you need to change a single element on the site needs on the new to redo all the pages. If it were possible to use LC template to the page (without loading the templates as indicated on your screenshot, on each page in case of changes of elements) the maintenance of the sites would have been much easier.

**Comment by lumberman** [comment]
Good point. We will introduce such feature in the future updates or as separate extension.
