### ISSUE TITLE
The content created in the Visual composer does not work on templates Live Composer

### ISSUE THREAD

**Issue by Dudaevskiy** [live-composer/live-composer-page-builder#367]
Again, I apologize for my English. Faced with the problem, not running content that was created using the plugin Visual Composer for posts (post, staff, download....). That is on those pages to which you have applied the theme Live Composer. Can this be fixed?

**Comment by hvsh** [comment]
No. Thats the problem with page builders. If you disable one page builder and activate another page builder, the content that is generated by the old page builder will become useless.

**Comment by lumberman** [comment]
Please try to use THE CONTENT module when creating templates. If you see no content rendered by this module it will not work.

PS: page-builders (all of them) are very expensive for your server resources. I do not recommend to have more than one installed on your website.
