### ISSUE TITLE
Module icons are not visible when is not an enough height

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#370]
Module icons need to be always visible:
https://www.evernote.com/l/AjMOv4QBhb5O8JS9v-HgE48Zvp6aARhoGdY

**Comment by lumberman** [comment]
I don't have this problem. On my end even with separator height=1px icons appear properly on hover event.

**Comment by xdima92x** [comment]
Hi) I recorded a short video - https://drive.google.com/file/d/0B7nJlmCX4yHuckFoVXhWMm5pN1U/view It works.

**Comment by FoldingTheme** [comment]
@xdima92x yes, I confirm the problem is fixed.
