### ISSUE TITLE
Latest Version Broke My Site

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#372]
Hey guys,

Thought I'd let you know this happened:

http://skinnytosuperhero.com

Thanks

**Comment by Deanphillips** [comment]
And this

http://skinnytosuperhero.com/plf-1/

**Comment by lumberman** [comment]
Hi Dean,
I think you just need to open pages and re-save it (in the latest version of master branch). 

Let me know if it will not help.

Side note: I know you confused by all these bugs, but this update is very important for the future performance and features development. I changed the way page code rendered on the page during the beta testing period. Users who never try the beta release will not have the issues you faced. On the other hand as beta tester you get all the possible bugs on your head. You help us a lot by reporting problems. I really appreciate this.

Please reopen this ticket if problem not solved after re-save.
