### ISSUE TITLE
Feature Request: Add possibility to create template for a particular taxonomy term

### ISSUE THREAD

**Issue by lumberman** [live-composer/live-composer-page-builder#373]
For now you can create template for archives only. Some users want to have a more precise targeting.

> How do I define a template for a single specific category?
> For example:
> Single category 1 = Template 1
> Single category 2 = Template 2
> Single others categories = Template 3
> (all of the same type of post)

See support request on: https://wordpress.org/support/topic/template-for-single-category/#post-8392285

**Comment by PabloDinella** [comment]
I'm in need of it :(

**Comment by jgajera** [comment]
+1 on this feature request

**Comment by FoldingTheme** [comment]
@xdima92x works great. One small thing:

When the templates are disabled, the optionstill exist on category, which may confuse the customers.
![templates_for_cpt_ _seowp_ _wordpress_and_edit_category_ _seowp_ _wordpress_and_edit_template_ _seowp_ _wordpress](https://user-images.githubusercontent.com/21088706/46602023-b6f45980-caf7-11e8-8817-f901ec0e795f.png)
