### ISSUE TITLE
Possibility to wrap sections with custom shortcodes

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#375]
Hey @lumberman 

1) Man, I'm loving how powerful this plugin keeps on getting dude :) 

Just wanted to mention that (in regards to my last message) - when I resaved the pages they're all working now (hopefully they'll be a work around in the future so that won't need to happen - or will it always be like that when updating to this one?!)

2) Anyway 16 months ago I spoke to Slobodan about the ability to add shortcodes around elements (like this https://www.youtube.com/watch?v=EtsJpxFih60) so we can hide/show elements based on certain things.

Right now I can't use LC on my new website as I need to be able to wrap shortcodes around content (we hide content based on shortcodes as it customises the site for people based around this)

I'm able to use Thrive Content Builder to do this, but I don't want to use them at all (I only want to use LC as I think it's 151510% better) 

Can we get the ability to do this please?!

Thank you

**Comment by lumberman** [comment]
Hi again @Deanphillips.

1) This is one of the side effects of beta testing. We try to make sure all bugs fixed before releasing. As our beta tester you can get bugs that regular users will never see. You can stick with official releases it it makes you too much of trouble. I appreciate your help.

2) I'm very interested to make this feature work in LC. This week we release current LC update.  After that I will research on how to make your request into the code. What plugin are you using for content customizations?

**Comment by Deanphillips** [comment]
1) That makes sense and I love beta testing it :)

2) Right now my entire membership site runs in memebrium, which uses
shortcodes to change content. This would also work really well with Thrive
Leads which a lot of LC members use - we would be able to trigger pop ups
with buttons etc :)

Quite a few other plugins I use would be great for this too :)

**Comment by Deanphillips** [comment]
Hey guys!

Is this still coming?

Thank you

**Comment by Deanphillips** [comment]
@lumberman @xdima92x  Any update on this feature?! :)

**Comment by FoldingTheme** [comment]
https://github.com/lumbermandesigns/lc-extensions/issues/15
