### ISSUE TITLE
Remove Dates From Josephine Comments

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#377]
Hey guys,

Can I get a "remove dates" from Josephine please?! Right now I'm turning down the font size to zero

Also the responsive design of the comment form module is bad too 

<img width="439" alt="screenshot 2016-11-09 11 15 42" src="https://cloud.githubusercontent.com/assets/21025321/20136661/e793d742-a66d-11e6-9ed9-673beaf50aa1.png">

**Comment by lumberman** [comment]
Moved request to Orao GitHub Issues: https://github.com/live-composer/lc-orao/issues/8
