### ISSUE TITLE
Load in a "Text module" the user page backend content

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#382]
On the initial page builder activation, load the user content from the WordPress page editor in a "Text module". This way the first time plugin users avoid the confusions regarding the "white pages" or "missing content".

**Comment by lumberman** [comment]
@xdima92x please talk to @FoldingTheme about this idea and come with solution on how we can implement it.

**Comment by xdima92x** [comment]
Hi @FoldingTheme and @lumberman Please check - https://github.com/live-composer/live-composer-page-builder/tree/issue/382 is it? It is a work when you activate the plugin.

**Comment by lumberman** [comment]
No @xdima92x, I need a code to run on first page edit in the Live Composer.

It should check if the page has any dslc_code. If no code found it should create a page with:
– Text module with current page title inside.
– Text module with current page content inside.

If there is no content in LC, the current theme should render the page as normal by default. I think we can improve Blank and Orao themes to have default rendering if there is no LC content found.
