### ISSUE TITLE
IE 11 is not rending images and animations are not working

### ISSUE THREAD

**Issue by mozalan** [live-composer/live-composer-page-builder#385]
Don't know why but previous issue about this matter and all of its comments are now deleted, couldn't find them... **Problem still exists and required urgent attention.** Many PC / Notebook / Laptop users are still on "Windows 7" and specially in the United Kingdom, most people are using "Internet Explorer 11" for their everyday browser experience. 

Please let's get it sorted ASAP.

Many thanks...

Gosh M.

**Comment by lumberman** [comment]
Hi Gosh,

I closed the previous topic as it was related to animations that are fully fixed now in branch #336.
Images will be fixed this week as well.

@xdima92x please create a new branch for this issue and find a solution for images problem in IE. Thank you!

**Comment by lumberman** [comment]
PS: animations will be disabled in IE 11 and below forever. Page will show content properly without any animations. They have bug in the browser and I will not invest our time fixing It (it's fixed in Edge).

**Comment by mozalan** [comment]
Most important thing is to make images rendered correctly in IE11, don't even worry about the below versions, just 11 to show images correctly, will do fine. Unfortunately in the UK, 99% of customers are asking & checking their websites with "Windows 7" operating system, where they use Internet Explorer 11... I'm stuck and don't know what to do about it.

**Comment by xdima92x** [comment]
Hi @mozalan Please test this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/336

**Comment by xdima92x** [comment]
@mozalan 
Hi) Please, follow the next steps:
1. Delete your current LC
2. Download this LC and install -> https://github.com/live-composer/live-composer-page-builder/tree/issue/336
3. Clear a cache in your IE

**Comment by mozalan** [comment]
Have done so, images are not rendered correctly - still there is an issue with the menu padding as well with this version (#336) - could you please check it on Windows 7 IE11 (I've got few laptops with that and VMWare installed, same in all of them..)

**Comment by xdima92x** [comment]
1) Can you give your URL site? Can you make screenshot or screencast? I tested images on my site and it works in the IE11
2) 'Still there is an issue with the menu padding as well with this version' - please open new issue for these.

**Comment by xdima92x** [comment]
@mozalan Please check this brach - https://github.com/live-composer/live-composer-page-builder/tree/issue/385

**Comment by mozalan** [comment]
sheffieldextensions.co.uk is the address.

**Comment by xdima92x** [comment]
Hi @mozalan I checked your site. Are you sure you have installed this LC - https://github.com/live-composer/live-composer-page-builder/tree/issue/385 ? I can't  find this LC in your code. Please delete an old LC and install a new.

**Comment by mozalan** [comment]
I have installed that but it broke the header section, changed navigation padding etc, I had to revert. 

Please use Virtual Machine to check it yourself, you'll see that header is forced to have a different padding to the one you'll set.

**Comment by xdima92x** [comment]
Hi @mozalan When you installed this branch you have a problem with rendering images in IE 11? If you have new bugs with the header section, changed navigation padding etc, please open the new issue for these. If you confirm that the problem with rendering images solved – I close the issue.

**Comment by lumberman** [comment]
@xdima92x keep calm please :)

**Comment by lumberman** [comment]
In master now

**Comment by Dudaevskiy** [comment]
+1
