### ISSUE TITLE
Gallery Slider module captions

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#387]
Add the captions feature for the "gallery slider module" (enable / disable).

**Comment by lumberman** [comment]
@xdima92x Please take care about this task.

**Comment by xdima92x** [comment]
Hi @lumberman Please check - https://github.com/live-composer/live-composer-page-builder/tree/issue/387 Need I add a caption for the module project slider? If yes, need I create a new issue for the module project slider?

**Comment by FoldingTheme** [comment]
Hi @xdima92x .
Is talk about the Gallery image caption. [See this screenshot](https://www.evernote.com/l/AjMKYRXdLBZNnog6yNty_1myAyiypXPTshE) for more details. It should be displayed over the slider image. Each gallery image may have its own captions.

**Comment by xdima92x** [comment]
Hi @lumberman  and @FoldingTheme Please check - https://github.com/live-composer/live-composer-page-builder/tree/issue/387 What do you think I need to add a caption for the module project slider?
