### ISSUE TITLE
The animation when the mouse is not working when animating in Live Composer

### ISSUE THREAD

**Issue by Dudaevskiy** [live-composer/live-composer-page-builder#390]
Hello friends, there is a great plugin https://github.com/IanLunn/Hover which allows you to create great animations when you hover over objects. But when using animation when hovering (that is, I specify in the element styles Live Composer class of this plugin) with simultaneous use of Live animation Composer plugin https://github.com/IanLunn/Hover not working. Would it be possible to fix the plugin (or include it in the Live Composer )?

**Comment by lumberman** [comment]
Hi there,
Yes we have this feature request in our roadmap. Most likely it will be introduced with new Live Composer UI update in a few months.

**Comment by FoldingTheme** [comment]
https://github.com/lumbermandesigns/lc-extensions/issues/56
