### ISSUE TITLE
Will there be implemented the animation of not only the unit as a whole and of its separate objects?

### ISSUE THREAD

**Issue by Dudaevskiy** [live-composer/live-composer-page-builder#391]
Will there be implemented the animation of not only the unit as a whole and of its separate objects?

**Comment by lumberman** [comment]
Thanks for this idea. Yes, we can do this, but for a moment animations is not our priority. We will be back to this request after stability and performance issues fully solved.

Thanks for understanding.

**Comment by xdima92x** [comment]
https://github.com/lumbermandesigns/lc-extensions/issues/56
