### ISSUE TITLE
Add video embed module

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#393]
This way we can help users to avoid the wrong usage of the "HTML module" and add a better and easier video insertion experience.

**Comment by xdima92x** [comment]
Hi) Please check this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/393

**Comment by FoldingTheme** [comment]
Great job! Please check this screenshot: https://www.evernote.com/l/AjOjCbH1smRJWb4XGebkmhTPbW2nHhm0r4s

**Comment by xdima92x** [comment]
Hi @FoldingTheme and @lumberman :) Please check this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/393
