### ISSUE TITLE
Missing Thai font

### ISSUE THREAD

**Issue by angeltrendy** [live-composer/live-composer-page-builder#400]
Please add all beautiful Thai Google font for people in Thailand using your theme. We need to use it
Please see the fonts in google site as following.

https://fonts.google.com/?subset=thai

Thank you in advance.

**Comment by lumberman** [comment]
NOTE FOR A CODER: Make sure to add a  new setting to enable Thai fonts via LC settings. Do not include it by default for everyone. 
( LC Settings > Settings > Performance > Font Subsets )

**Comment by angeltrendy** [comment]
No Thai Font subsets to select in check box provided.

Best regards,
*Don Nawatpakorn*
*angeltrendy*
63/8 Moo 8, Lat Krabang 16,
Racha Thawa, Bang Phli,
Samut Prakan 10540
mobile: +669 1779 5648
email: don@angeltrendy.com

email disclaimer
----------------

This email and any files transmitted with it are confidential and intended
solely for the use of the individual or entity to whom they are addressed.
If you have received this email in error please notify the system manager.
This message contains confidential information and is intended only for the
individual named. If you are not the named addressee you should not
disseminate, distribute or copy this e-mail. Please notify the sender
immediately by e-mail if you have received this e-mail by mistake and
delete this e-mail from your system. If you are not the intended recipient
you are notified that disclosing, copying, distributing or taking any
action in reliance on the contents of this information is strictly
prohibited.

**Comment by lumberman** [comment]
Yes, I know. It was a note for our developer when he back to add these fonts in our code for you. Sorry for this confusion.

**Comment by xdima92x** [comment]
Hi @lumberman Please check - https://github.com/live-composer/live-composer-page-builder/tree/issue/400 I'm not sure but is it? I added all Thai google font and setting font subsets. But I don't understand how to work setting - font subsets

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/400
