### ISSUE TITLE
Masonry animation preloader

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#402]
Add a preloader option for posts / blog elements, in special when are used animated options (Masonry, grid,etc). This way the layout will be displayed nicely while is loaded.

Short video with the issue: https://www.dropbox.com/s/kp4b8szalrnjz9x/demo-masonry-loading-issue.mp4

**Comment by xdima92x** [comment]
The video does not work. Maybe we will add it later. At this moment we work on other improvements for Live Composer
