### ISSUE TITLE
If you come to edit template from the post LC should send you back when closed.

### ISSUE THREAD

**Issue by lumberman** [live-composer/live-composer-page-builder#404]
Post View > Edit Template > Live Composer > Close > Post View (not Template View)

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/404

**Comment by xdima92x** [comment]
Dima - https://www.evernote.com/shard/s554/sh/6c83e73c-7acf-41b5-8f13-f3c43e30fa4f/65a09474cafaad14 don't work a properly
