### ISSUE TITLE
URGENT: Tablet Styling not working, on ANY of my LC sites!

### ISSUE THREAD

**Issue by jessicahawkins3344** [live-composer/live-composer-page-builder#406]
I don't know what has happened here, but responsive tablet styles are not working on ANY of my sites that I use LC which is pretty much all - this is BAD - phone styles are working fine. What's the isssue??????

**Comment by jessicahawkins3344** [comment]
Update - the changes are happening - but not being reloaded live in the editor when on tablet styling... any idea?

**Comment by jessicahawkins3344** [comment]
Additional issue - enabling DEV_MODE makes the icon to grab defaults appear in editor, but no modal opens giving you the defaults to create your new defaults functions with.

**Comment by ElementalCrisis** [comment]
Can you post a link?

**Comment by lumberman** [comment]
Most likely #138
What theme are you using?

**Comment by jessicahawkins3344** [comment]
LC Blank, and my own theme - so it isn't theme specific... 

The responsive tablet styles are saving and publishing, but when editing them in LC you cannot see the styles you set for tablet styles in real time. You have to exit tablet styles and test to see if you are satisfied with the way tablet looks by resizing your window, rather than it happening live like on normal styling or phone.

**Comment by lumberman** [comment]
Please try the latest version from the master branch https://github.com/live-composer/live-composer-page-builder/archive/master.zip

( fully backup website > delete current plugin > upload new zip )

Thank you.

**Comment by jessicahawkins3344** [comment]
This is working in the master branch, branch v1.1.4 is here I was seeing issues.
