### ISSUE TITLE
404 Error page does not work!

### ISSUE THREAD

**Issue by alinzm** [live-composer/live-composer-page-builder#413]
I used live composer page builder Version 1.1.4 and Adventure tours theme on my WordPress site for [Wegoiran.com](http://www.wegoiran.com). When I active live composer, I will have no 404 error anymore. What is the problem? Has anyone an idea or same problem?

**Comment by lumberman** [comment]
Can you please try latest code from the master branch https://github.com/live-composer/live-composer-page-builder/archive/master.zip ?

**Comment by xdima92x** [comment]
Hi @alinzm I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
