### ISSUE TITLE
Video Embed Module Ignores Height and Width upon Publish and Disable Editor

### ISSUE THREAD

**Issue by lukeperrie** [live-composer/live-composer-page-builder#414]
The Video Embed module is "forgetting" the height and width settings upon publish and Disable Editor.

See video: https://cl.ly/iCf0

**Comment by lumberman** [comment]
Video Embed Module is using standard WP function passing parameters to it https://codex.wordpress.org/Function_Reference/wp_oembed_get We do nothing with output just render this function. 

I checked on my end and video do not lose the settings. Can you please confirm that you are using Video Embed plugin Version: 1.0.2 and latest LC?

Thank you.

**Comment by lukeperrie** [comment]
Hey @lumberman - we are using LC 1.1.4 and we were using Video Embed 1.0. But even after I have updated to video embed 1.0.2 and re-added the module to the page - it's still losing the size setting:

See video: https://cl.ly/iGW2

**Comment by lukeperrie** [comment]
@lumberman scratch this - sorry - tied it to a mod we made locally. So sorry!
