### ISSUE TITLE
Dev Mode:  Get Defaults not working

### ISSUE THREAD

**Issue by jessicahawkins3344** [live-composer/live-composer-page-builder#415]
get defaults button not working in dev mode active

**Comment by lumberman** [comment]
Just tested in master https://github.com/live-composer/live-composer-page-builder/archive/master.zip 
Works well on my end. Please, check the latest version in master branch and let me know if it's still broken for you. If needed reopen this ticket.

Thank you!

**Comment by jessicahawkins3344** [comment]
Confirming - does work on master, but not in official WP version 1.1.4 - I was waiting to update on live sites to avoid potential bugs, but needed that feature.
