### ISSUE TITLE
Accessibility issue (blind readers)

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#416]
The "Title" of images are not rendered when the browsers doesn't load the images (settings). Need to improve the content accessibility.

**Comment by lumberman** [comment]
@xdima92x please take a look at this task and create a branch with fix.

**Comment by xdima92x** [comment]
Hi @FoldingTheme and @lumberman Please read this article - http://www.wpbeginner.com/beginners-guide/image-alt-text-vs-image-title-in-wordpress-whats-the-difference/ I think it is not a bug.
