### ISSUE TITLE
Module Padding

### ISSUE THREAD

**Issue by monowebdesign** [live-composer/live-composer-page-builder#417]
Feature request - Would it be possible to further define the padding controls so we can set the top / bottom & left / right padding rather than just having vertical & horizontal?
Thanks

**Comment by lumberman** [comment]
We already added more paddings in the development version. Please try it https://github.com/live-composer/live-composer-page-builder/archive/master.zip 

Make sure to create a full site backup before installing.

Let me know if in any other modules you need these top/right/bottom/left controls.

**Comment by xdima92x** [comment]
Hi @monowebdesign I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
