### ISSUE TITLE
[Fix] Background Video for iOS and Android

### ISSUE THREAD

**Issue by senning** [live-composer/live-composer-page-builder#418]
Hi there,
I was having trouble with the row background video on mobile devices. Specifically, on most mobile devices the video would not play (and in some cases the video would start and then die to a black screen).

I created a fix which allowed the video to work on all mobile devices which support the autoplay+mute standard (new iOS and Android versions), doesn't interfere with the background image on devices that don't, and shouldn't interfere at all with desktop browsers. I've attached the patch here - let me know if you'd prefer a pull request and I'll try to create one.

[mobile-bg-video.patch.zip](https://github.com/live-composer/live-composer-page-builder/files/614468/mobile-bg-video.patch.zip)

**Comment by lumberman** [comment]
Thanks for your help.

Can you please kindly make a pull request?
Did you test it on real mobile devices? Can you share your results?

**Comment by xdima92x** [comment]
@senning Hi, thanks for your addition. Unfortunately, this branch has conflicts - https://github.com/live-composer/live-composer-page-builder/pull/421
