### ISSUE TITLE
Woo Products module allow product type selections

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#420]
t 24562

Study the possibility to add the product type selection feature, in the "Woo Products module", in the same way the "Posts module" provides the ability to choose between custom posts. With such a feature the extension will become more versatile and compatible with premium Woocommerce plugins what create different product types (ex: https://codecanyon.net/item/rnb-woocommerce-rental-booking-system/14835145)

**Comment by xdima92x** [comment]
Hi @FoldingTheme I added this issue here - [WooCommerce integration module.](https://livecomposerplugin.com/downloads/woocommerce-page-builder/)

**Comment by xdima92x** [comment]
I fixed - https://github.com/live-composer/live-composer-page-builder
