### ISSUE TITLE
Woo Products module - hide ratings and sale numbers

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#425]
Add possibility to hide the products rating or sales numbers. This allows the shop's owners to have a more control over the products presentation.

**Comment by lumberman** [comment]
@xdima92x add this as feature request to [WooCommerce integration module](https://livecomposerplugin.com/downloads/woocommerce-page-builder/). We will not do this in default LC as this module will be completely removed in the future versions.

@xdima92x Once it's done (ticket moved to WOO repo), please, close this ticket.

**Comment by xdima92x** [comment]
Hi @lumberman okay
