### ISSUE TITLE
Fatal Error on plugin activation

### ISSUE THREAD

**Issue by bpyfrom** [live-composer/live-composer-page-builder#426]
**Fatal error: Class 'DSLC_Html' not found in C:\ptv-ws\wordpress\wp-content\plugins\live-composer-page-builder\includes\functions.php on line 141**

I have tried multiple things. I deactivated all other plugins and I even install earlier versions from Github. The Error persists.

**Comment by lumberman** [comment]
Hi,
Thanks for you interest in Live Composer and taking time to report this issue.

Can you confirm that you have /modules/html/ folder inside the [Live Composer plugin](http://livecomposerplugin.com) folder?

Can you please try the latest version from the master branch https://github.com/live-composer/live-composer-page-builder/archive/master.zip ?

If nothing helps, I suspect it is somehow related to the fact that you are running it on windows. I have no windows machine to test it, but probably there is something to do with folder/file permissions set in your local server?

**Comment by bpyfrom** [comment]
I have verified the html folder and installed the latest version. I also did some further trouble shooting. The problem persists.

This issue presents with the Google App Engine Launcher. I also installed a Bitnami Word Press local installation and the plugin worked fine. Other plugins for GAEL install and activate without an issue. There must be an issue with the configuration files as specified by Google and how your plugin is setup.

**Comment by lumberman** [comment]
Thanks for this data. Since you are the only user from 30K+ other users who reported this problem, I suspect not many of the rest use Google App Engine Launcher. We will ignore this problem for now as all the over virtual servers work well (Mamp, Wamp, VV, VVV, ...). Please, use alternative virtual server solution for your development. 

Sorry for not able to help with this.
