### ISSUE TITLE
[Fix] Image components don't respect max-width on IE

### ISSUE THREAD

**Issue by senning** [live-composer/live-composer-page-builder#427]
IE <= 11 doesn't constrain images to column width, possibly because it interprets .dslc-image's width:auto to mean it should expand to fit the content. Adding a max-width: 100% on .dslc-image as well fixes this issue.

**Comment by lumberman** [comment]
Hi there,
I believe it's fixed in the master branch: https://github.com/live-composer/live-composer-page-builder/archive/master.zip If not please, reopen this ticket.
