### ISSUE TITLE
Template base note clarification

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#429]
Clarify the template note base. [See this screenshot](https://www.evernote.com/l/AjOlqgOG3A1AS6Mk5xpLvN7HH2TCIA86ZD0). Since the note is applied to the "single" posts, there it should be a more clear specification about this, otherwise, this can lead to confusions about theme archive design usage (archive.php).

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/435
