### ISSUE TITLE
The WordPress/Site Address warning in 1.1.4 is broken and needs better display logic

### ISSUE THREAD

**Issue by cyruscollier** [live-composer/live-composer-page-builder#430]
If you setup WordPress to be in a subdirectory of the home url and do it properly (using `WP_HOME`, `WP_SITEURL` and modifying `index.php`), there should be no need for Live Composer to display a warning, as front-end editing works just fine in this configuration. The logic for when to display this warning should be more sophisticated than a simple string compare between `WP_HOME` and `WP_SITEURL`, and it should address specific incorrect configurations which may lead to cookie domain issues.. Additionally, the warning cannot be permanently dismissed, and the link contained in the warning when outside the setting page incorrectly points to `admin.php?page=dslc_getting_started`, which doesn't exist.

**Comment by lumberman** [comment]
Great points.
For now please hide this notice with custom css if it bugs you.
We will improve this notice logic in a the next versions.

PS: I never get why some WP developers prefer subfolder over subdomain for web development. Can you please share with me why you are installing WP in subfolder?

**Comment by cyruscollier** [comment]
Great question. The main reason is because Composer becoming much more commonly used in WordPress projects to maintain dependencies. This usually includes WP plugins and core. Plugin management is done using https://wpackagist.org and core is usually done using https://github.com/johnpbloch/wordpress. Composer dependencies need to be in their own directory so it can be deleted and re-installed clean every time. 

So, for example, most of my WP projects over the past few years have had a structure similar to this:
```
/wp/ (core only)
/wp-content/ (everything else)
/composer.json
/wp-config.php
/index.php (copied from core with require() path modified to /wp/)
```

In addition to making everything work with Composer, it's also a lot cleaner to work in the project without all the core files in the root, especially if you start adding a bunch of extra project config files like `phpunit.xml`, `phpspec.yml`, `.travis.yml`, etc.

**Comment by xdima92x** [comment]
Please update to the latest version of Live Composer.
