### ISSUE TITLE
H1 is missing from front-end formats options

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#434]
Text module:

https://www.evernote.com/l/Ajkg3BsfFIlBUqemuKR4eF8Qcm26GLl4Qb0

In the module content editor, the heading is in place.

**Comment by xdima92x** [comment]
Hi @FoldingTheme and @lumberman Please check this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/434
