### ISSUE TITLE
Archive template ignoring the theme archive design

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#435]
Analyse the possibility to provide the option to use the theme archive.php file instead of the one from LC. Or, at least to be in the same way [the LC templates work for single posts](https://www.evernote.com/l/Ajn_bQ5ed2BIH73k4od3KZmd5c79bLODBAQ).

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/435

**Comment by xdima92x** [comment]
Dima - https://www.evernote.com/shard/s554/sh/1096cd45-5200-4a8b-821d-54858f9906a2/8597aa5246cf98ea
