### ISSUE TITLE
Info module responsive custom styles issues (master)

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#437]
On master release, the responsive styles filed is missing from the "Info box module". [See this screenshot](https://www.evernote.com/l/AjmW1rxcCPtKibdwjdk4hfe2fj6J890HXTM).

**Comment by lumberman** [comment]
Just scroll to the left.

**Comment by FoldingTheme** [comment]
There was no scrolling issue. :) 
The options simply were missing. However, I reinstalled the WP and it seems the options are back. Will keep on eye on this.
