### ISSUE TITLE
Show/Hide Dependency

### ISSUE THREAD

**Issue by xdima92x** [live-composer/live-composer-page-builder#439]
I read this article - https://livecomposer.help/article/193-conditional-visibility-for-module-options-show-hide-dependency And I get an error - https://www.evernote.com/shard/s554/sh/63d3b039-115e-4802-9f50-d3824d51ae78/6a8986d3d4c296af

**Comment by xdima92x** [comment]
Hi @lumberman Please check this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/439

**Comment by lumberman** [comment]
Fixed as commit to the master branch.
