### ISSUE TITLE
Double vertical scrollbars [master]

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#440]
On Chrome, Firefox, Safari, etc, the workspace have double vertical scrollbars. [See this screenshot](https://www.evernote.com/l/Ajl8LqH1bmZKxokO5Cf4hydA4JkxQVPfuaU) for more details.

**Comment by xdima92x** [comment]
Hi @FoldingTheme I recorded a short video for you - https://drive.google.com/file/d/0B7nJlmCX4yHuYUJTS28zWlFpUUk/view I don't see the double vertical scrollbars in the workspace. I tested on Chrome, Firefox, Safari. Can you please try the latest code from the master branch https://github.com/live-composer/live-composer-page-builder/archive/master.zip and say if you have double vertical scrollbars?

**Comment by FoldingTheme** [comment]
@xdima92x thanks. Yes, the problem remain. Please check this screencast: https://www.dropbox.com/s/sbnfx1do95wu5n5/bug-double-scrollbar.mp4

Try to use a lower resolution or browser window size.

Cheers.

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/440

**Comment by FoldingTheme** [comment]
@xdima92x the problem is fixed.
