### ISSUE TITLE
Site won't load anything now

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#441]
Hey guys,

http://design.oliluke.com

^^ just updated to the latest (and one before that from the 6th) and nothing is working, weirdly

**Comment by Deanphillips** [comment]
@lumberman Is it new code again?!

**Comment by Deanphillips** [comment]
I used a back up as the site was needed for today :)

**Comment by xdima92x** [comment]
Hi @Deanphillips Can you please try the latest code from the master branch https://github.com/live-composer/live-composer-page-builder/archive/master.zip and say if the site works?

**Comment by xdima92x** [comment]
Hi @Deanphillips I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
