### ISSUE TITLE
Reporting a bug in the accordion module

### ISSUE THREAD

**Issue by gold5814** [live-composer/live-composer-page-builder#442]
The accordion module can not be edited.

**Comment by xdima92x** [comment]
Hi @gold5814 Where do you cannot edit? Can you more details describe the problem? I downloaded the latest code from the master branch - https://github.com/live-composer/live-composer-page-builder/archive/master.zip and it works. I recorded a short video for you - https://drive.google.com/file/d/0B7nJlmCX4yHuMEp5UTNwYUpqX28/view

**Comment by xdima92x** [comment]
Hi @gold5814 I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
