### ISSUE TITLE
Fonts not displaying 

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#443]
![15540417_10154373821037955_1700744787_o](https://cloud.githubusercontent.com/assets/21025321/21136673/7207f1cc-c11e-11e6-967c-da9fd735892b.png)
Hey guys.

A friend has been helping me with this site (Reviewing it) and there's issues with Fonts not loading.

http://design.oliluke.com/how-to-turn-leads-into-high-ticket-sales-without-running-predictable-yawn-automated-webinars/

On my mac it loads perfectly, but on his (in chrome) it's showing Georgia for many areas (see attached)

Thanks

**Comment by xdima92x** [comment]
Hi @Deanphillips I saw your site. Are you sure to use font family - Georgia -https://www.evernote.com/shard/s554/sh/2a17f7a0-ba84-47a4-9a79-5982ebaaf3b6/b510544147f4ab21? Can you please try the latest code from the master branch https://github.com/live-composer/live-composer-page-builder/archive/master.zip? I tested it works - https://www.evernote.com/shard/s554/sh/7feb408a-ad83-4f60-b23e-34f7d15952eb/5065460015265acf

**Comment by Deanphillips** [comment]
Sorry the font was actually meant to be "Brandon Grotesque"

http://oliluke.com

But it doesn't seem to be working in all places (even when selected) :)

**Comment by xdima92x** [comment]
Hi @Deanphillips The Live Composer doesn't have this font 'Brandon Grotesque'. I have checked your site - http://oliluke.com I'm not sure but you have added the font 'Brandon Grotesque' are manual. Please check this [screenshot for more details.](https://www.evernote.com/shard/s554/sh/3c5816e6-fb30-4edf-8ffc-12a84e52b145/4784099de0a4d77e) And I have checked the site - http://design.oliluke.com/how-to-turn-leads-into-high-ticket-sales-without-running-predictable-yawn-automated-webinars/ I didn't find this style. It seems out of this, the font doesn't work.

**Comment by xdima92x** [comment]
Hi @Deanphillips I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
