### ISSUE TITLE
jQuery "hooks"

### ISSUE THREAD

**Issue by Rayken** [live-composer/live-composer-page-builder#447]
I'm trying to trigger something to happen with another library when one inserts a row. How? I just want to make sure that I do the stuff *after* LC has added the row completely. Specifically it's re-initializing another script once the row has been inserted. As is, I'm listening for "click" events on the ```.dslca-add-modules-section-hook``` class, however that results in my code running "before" LC is finished which in turn results in a bug (I have to press twice and.. yeah you get the idea it's behind, being fired too early). 

How can I let LC do its thing then do my thing? The documentation is somewhat lacking for developers and though I've been trying to look at the source code I can't seem to find a good way of doing it. There's the WP hook ```wp_ajax_dslc-ajax-add-modules-section``` being fired but I'd rather want to listen to an event in jQuery if possible.

**Comment by Quaked** [comment]
So for now I've set a timeout for 2 seconds to make sure my rebuild/re-init of the other library happens after LC has added the row. It's not optimal but it works, but if there's a hook or bind I can use I'd really want to use that.

Better yet, is there something I can listen to where it would make sense to update the DOM? Like, adding/importing/deleting, any of these as far as rows go I'd wanna trigger this re-init. Is there anything available?

**Comment by xdima92x** [comment]
At this moment you can use your solution. The Live Composer doesn't have hooks for jQuery
