### ISSUE TITLE
Duplicate posts on random grid and masonry grid

### ISSUE THREAD

**Issue by delorimier** [live-composer/live-composer-page-builder#448]
Random order feature for post module displays duplicate posts on grid and masonry-grid.

**Comment by xdima92x** [comment]
Hi @delorimier I have tested the module 'Post'. I don't have duplicate posts when I select the order by 'random'. I recorded a short video for you. Could you make a screenshot or screencast? Do you have duplicate posts in your WP Admin?

**Comment by delorimier** [comment]
Thanks for that video. I forgot to add that problem appears with pagination (load more).

**Comment by delorimier** [comment]
No duplicate posts in WP Admin. Here is a screenshot after clicking twice on load more for 2 fresh rows.

![double](https://cloud.githubusercontent.com/assets/11297575/21894209/569a219e-d8ac-11e6-8431-b17abc35c7bb.PNG)

**Comment by xdima92x** [comment]
Hi @delorimier It's not a bug of Live Composer. Research on the internet also shows this error. You can use this solution:
- http://stackoverflow.com/questions/19092249/order-random-without-duplicates-on-pages
- http://wordpress.stackexchange.com/questions/31647/is-it-possible-to-paginate-posts-correctly-that-are-random-ordered

Let me know the results, please :)

**Comment by delorimier** [comment]
I see, thank you. I wonder why WordPress hasn't fixed this obvious problem.

I used the posts_orderby filter found [here](https://hugh.blog/2013/08/22/wordpress-random-post-order-with-correct-pagination/), and inserted inside my custom LC posts module, to run only if $options['orderby'] == 'rand'. Seems to work fine, no pagination repeats when random selected. 

Thanks again. I guess the code should also check if pagination is on, but all my rand loops are paged, so no need for me.
