### ISSUE TITLE
new version completely broke site

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#449]
Hey guys,

I updated a site to the latest version and the following errors happened:

https://www.dropbox.com/s/3dup0fcipu0v84j/Screenshot%202016-12-21%2013.10.18.png?dl=0

https://www.dropbox.com/s/5cbo9jjrlg3p4r1/Screenshot%202016-12-21%2013.09.59.png?dl=0

Thanks

**Comment by Deanphillips** [comment]
And fonts haven't been working for a while neither (for example some fonts load in some places but don't in others)

(and the embed code is on the site too)

<img width="1427" alt="screenshot 2016-12-21 13 07 19" src="https://cloud.githubusercontent.com/assets/21025321/21390791/836f31c4-c780-11e6-9a9c-147fe0eaaa01.png">
![screen shot 2016-12-21 at 13 07 24](https://cloud.githubusercontent.com/assets/21025321/21390801/90f70128-c780-11e6-9e16-6ee5b8cf0b81.png)

**Comment by Deanphillips** [comment]
![screen shot 2016-12-21 at 13 07 24](https://cloud.githubusercontent.com/assets/21025321/21390822/ad8939d2-c780-11e6-96b4-1530cf377b16.png)

**Comment by xdima92x** [comment]
Hi @Deanphillips Could you re-save ( click on the button publish changes ) this page? Let us know the results, please. When you add a new module 'text', do you have this error? https://www.dropbox.com/s/3dup0fcipu0v84j/Screenshot%202016-12-21%2013.10.18.png?dl=0

**Comment by xdima92x** [comment]
Hi @Deanphillips I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
