### ISSUE TITLE
Blog Element - Cannot View All Categories

### ISSUE THREAD

**Issue by Friscopolice** [live-composer/live-composer-page-builder#458]
![1](https://cloud.githubusercontent.com/assets/6260521/21467578/33b8b9ae-c9b8-11e6-9450-794c1c6eee7f.PNG)

When using the blog element, you are unable to view all categories. I currently have five post categories on my blog but the page builder only lists two.

**Comment by xdima92x** [comment]
Hi @Friscopolice I tested the module 'Blog'. It works - https://www.evernote.com/shard/s554/sh/ef3811a7-4481-4e60-ada6-a5e767d0d466/48bef93d04432f4c What version LC?

**Comment by Friscopolice** [comment]
Version 1.2

**Comment by xdima92x** [comment]
Hi @Friscopolice I tested the module 'Blog'. It works. I recorded a short vide for you - https://drive.google.com/file/d/0B7nJlmCX4yHuMGlpUjlZYURUYVk/view Maybe you don't add categories in posts - https://www.evernote.com/shard/s554/sh/593d9eba-89fa-4471-b579-f280461d63bc/e0d2fd7b7642e1c3 Could you open a ticket - https://livecomposerplugin.com/support/support-request/ and send login details on Wordpress for testing?
