### ISSUE TITLE
Google Map overlaps border radius

### ISSUE THREAD

**Issue by mozalan** [live-composer/live-composer-page-builder#459]
Hi, when trying to add border width to the Google Maps element, map itself overlaps the border in corners. Please check the screenshot, I have tried all the settings and it still does the same.
![radius does not work](https://cloud.githubusercontent.com/assets/20672449/21469184/5b5fa774-ca35-11e6-9986-9dfb1722ec8b.PNG)

**Comment by xdima92x** [comment]
Hi @mozalan How did you added Google Maps via module 'HTML' or plugin - https://livecomposerplugin.com/downloads/google-maps-add-on/ ?

**Comment by mozalan** [comment]
Hi Dima, I've added it via ELEMENTS BAR, LiveComposer Extension (GoogleMaps)

**Comment by xdima92x** [comment]
I copied your request from this issue to a new private issue in https://github.com/lumbermandesigns/lc-googlemaps/issues. The problem will be fixed in the next update.
