### ISSUE TITLE
Box Shadow on hover turned on after update

### ISSUE THREAD

**Issue by jakg88** [live-composer/live-composer-page-builder#463]
Hello, 

After the recent update, all my text boxes, which didn't have any shadows (on hover), now have changed and have the box shadows on hover. 

How can I switch it off without modifying every element on each page? 

Thank you

**Comment by mozalan** [comment]
Hi Jack,

Do you have the screen shot or a URL so we can check it?

**Comment by xdima92x** [comment]
Hi @jakg88 Yes, you need to manually change element on each page or you can delete the box-shadow. Please [read this article](http://stackoverflow.com/questions/18765264/how-do-i-remove-a-box-shadow-effect-from-an-element-when-another-element-is-hove) for more details.

**Comment by xdima92x** [comment]
Hi, can you please try the latest code from the master branch https://github.com/live-composer/live-composer-page-builder/archive/master.zip ?

**Comment by xdima92x** [comment]
Hi @jakg88 I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
