### ISSUE TITLE
After update to 1.2, no borders in Gallery Grid Extension 

### ISSUE THREAD

**Issue by menachemshapiro** [live-composer/live-composer-page-builder#464]
I just updated to LC 1.2, and the borders disappeared in the Gallery Grid paid extension, on my webpage here: https://bananabeachcr.com/weddings

Let me know if you need any more information from me.

**Comment by xdima92x** [comment]
I copied your request from this issue to a new private issue in https://github.com/lumbermandesigns/lc-gallery/issues. The problem will be fixed in the next update.

**Comment by xdima92x** [comment]
Hi @menachemshapiro Just try re-save the page?

**Comment by menachemshapiro** [comment]
I just did, no difference.The border is still not showing up.

**Comment by menachemshapiro** [comment]
I played around with it a little, and I found the solution. The "Borders" section was greyed out. However, just clicking the switch in the top right-hand corner did nothing. Even though it said it was enabled, the borders still didn't show up. I had to uncheck and check one of the border sides, and then the border showed up.

**Comment by xdima92x** [comment]
I recorded a short video for you  - https://drive.google.com/file/d/0B7nJlmCX4yHueHFVR3ZyS0pETFU/view It works.

1. Open your website for editing in a private/incognito mode. Let me know if it's any different.
2. Try do deactivate all the other plugins for a minute and see if LC works as expected?
3. Try to activate a default WP theme for a minute and see if LC works as expected?
4. Do you get an error when to activate debugging mode ( define('WP_DEBUG', true); ) in the file wp-config.php? Please check this screenshot for more details.
5. Do you have borders when again you will add the module?
