### ISSUE TITLE
LC 1.2 -- links in text module lost colors

### ISSUE THREAD

**Issue by menachemshapiro** [live-composer/live-composer-page-builder#465]
Using LC Blank theme. 

When I updated to 1.2, links in the text modules lost their colors. They are now the same color as the regular text. 

In the style options for links they are set to inherit. When I manually change the colors from inherit to the colors I want, they successfully change.

**Comment by xdima92x** [comment]
Hi @menachemshapiro  Could you re-save ( click on the button publish changes ) and update this page? Let me know the results, please.

**Comment by menachemshapiro** [comment]
The first thing I did when I updated to 1.2 was to edit all the pages and publish them, so that the new code formats would take effect. That is when the link colors disappeared, and were set to inherit.

Once I went in and manually changed them, then published the page, the colors stayed the way I wanted them to. 

I went now and made another edit (just a random edit, I did not change the style) and then published, like you asked, and the colors stayed the way I set them. I did it on this page: https://bananabeachcr.com/directions

This just seems like a bug in the conversion process to the JSON format, as opposed to a bug in LC itself, although I could be wrong. If it helps, I have a backup created with Updraft plus from before the upgrade. If you let me know which files to extract, I can do so and send them to you, so that you can compare them with the updated one.

Let me know if you need anything else.

**Comment by xdima92x** [comment]
Hi :) I'm not sure but you need to re-save ( click on the button publish changes ) each page. I checked the module 'text' in LC 1.2 and it works.

**Comment by xdima92x** [comment]
Can you please try to update the latest version of Live Composer? I have tested this version. It works.

**Comment by xdima92x** [comment]
Hi @menachemshapiro I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
