### ISSUE TITLE
bool(false) show after footer

### ISSUE THREAD

**Issue by Giascar** [live-composer/live-composer-page-builder#470]
After the last update (ver. 1.2), bool(false) show after footer, as you can see at the bottom of my site: [www.urkin.it](http://www.urkin.it)

I tried to disable all plugin (in Wordpress and in my browser too) but the issue is still present.

**Comment by xdima92x** [comment]
Hi @Giascar I'm not sure but you are using the function [var_dump](http://php.net/manual/en/function.var-dump.php). Please open your theme and find this function. You can use a combination keyboard 'Ctrl + F' in your text editor. Let me know if you resolved your problem.

**Comment by Giascar** [comment]
Hi @xdima92x thanks for your reply. I searched in every php file of my theme but the function is not present. I'm using Orao theme and I have changed it only through Live Composer.

The bool(false) also appears if I visualize only header or footer standalone. The text disappears when I'm in edit mode with Live Composer.

**Comment by xdima92x** [comment]
Hi @Giascar No problem!  I'm glad you decided the problem :)
