### ISSUE TITLE
Js error

### ISSUE THREAD

**Issue by khemraj1431** [live-composer/live-composer-page-builder#471]
Hello
I am using live composer and getting following error...can u pls help me out?

Live Composer returned JS error
SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 1 column 7476 of the JSON data
File "http://www.drsufis.com/wp-content/plugins/live-composer-page-builder/js/builder.all.min.js?ver=1.2", line 1, char 5214

**Comment by xdima92x** [comment]
This bug is in the old version of Live Composer. In new version we don't use builder.all.min.js

**Comment by khemraj1431** [comment]
I installed it 10 days ago ...still get that error

**Comment by xdima92x** [comment]
Please changed this string 'define( 'SCRIPT_DEBUG', false );' in the wp-config.php - https://www.evernote.com/shard/s554/sh/bcf58d45-ece4-44f6-9208-fd42e451032f/6c1b22eb2c815d59 Let me know the results please :)

**Comment by xdima92x** [comment]
Please changed this string 'define( 'SCRIPT_DEBUG', true );' in the wp-config.php - https://www.evernote.com/shard/s554/sh/4b4a6be3-b3c4-4eca-88a0-1949b872076b/0297a216a5eba61f Let me know the results please :)

**Comment by khemraj1431** [comment]
dont have anyting like that in my wp-config.

<?php
define('WP_CACHE', false); // Added by WP Rocket
/**
 * The base configuration for WordPress
 *
 * The wp-config.php creation script uses this file during the
 * installation. You don't have to use the web site, you can
 * copy this file to "wp-config.php" and fill in the values.
 *
 * This file contains the following configurations:
 *
 * * MySQL settings
 * * Secret keys
 * * Database table prefix
 * * ABSPATH
 *
 * @link https://codex.wordpress.org/Editing_wp-config.php
 *
 * @package WordPress
 */

// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define('DB_NAME', 'ss_dbname_gd12k5kh35');

/** MySQL database username */
define('DB_USER', 'tFU8w4HQlDQ56WE');

/** MySQL database password */
define('DB_PASSWORD', 'hKTT0Uht5lTD0vB2');

/** MySQL hostname */
define('DB_HOST', 'marketingmadscom.ipagemysql.com');

/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');

/**#@+
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */
define('AUTH_KEY', 'K[z>Xvr)gZmOtP^F%jBmhnzD^(Z[+*n+)+s{(we?yYENTWT]O=Nwbr?n=*]Nqn}jzQFpX]>Tbc//N[ixlRI{?%YV{yP*JdVTuig-TBGQD/$f{doB@%oE=O<b|ZE^O/K}');
define('SECURE_AUTH_KEY', ';sZ]{ep=Ddxu*;JmLGs!&Bi%dEM%<qQIyM;wQjo*HVrAecfom-lwfe}bV>CoOx_Y{N+k;Pcbk[vGTQQQn&GuX<AEbjQs<abJ(=<Z*LxT}Zt=a_cOqU/_XfOJ(p^FOsXy');
define('LOGGED_IN_KEY', 'T{symYnV+<;rT+oeWur%pf-oLBNKq<bC{GHyp<qSlc>{GUk^-Sw/L@iyqWvFMqkvybw]Eh=D$ig^ho[=^DO[yZ]+g/onLMy^{d|>p%dBH<keRCG&?W%)uA(Ckv&QkmGN');
define('NONCE_KEY', 'J(-P<[Rk-XtZfzEJ^m&dwly&<(>|T-[;/!XIPLrHnh%cZ$EsOpf([T]-Tgjffo|XhuroOWgCw@P[Kh;c{^$mv{$tVe|>XJqnI<u]TItbk;@&!R<!=zeFP%k]m}L?ns%N');
define('AUTH_SALT', '@PrLW*)bsoWmUXuE}R(m|zGRZnLCGMDr]GAHAR^W*{/iPS/dr}XKvUacp!h<jxWas)O<yw|!K}Lkp@I%]AfR!(hi=Fv<a<w(gqnaUgYM@Cs+RYVznstK[-MS?^C-nj$s');
define('SECURE_AUTH_SALT', 'bqKPqn;M%M%soLlTaa>RiCLS<xVtHwG[=hRh}K{bel@BM$oP|!WW-ar<fnksD>(cEKLmpE/ru<O{jxG/SPu)-GibV%f*){yVYZ*G|X<wp?_HqBzGeK&lw+I<XdzulJ>A');
define('LOGGED_IN_SALT', 'Q!VQz|kLqrqxdo|?Ro?oo&F*_qrN__W;_jvlMRn%CU+QJpErV^%FAAjj*;wJeJBksgaPC}y&UoQ|fmHryWo$!{heM>**Pzkiqs(&x}U?Zn?L;*Wrol_o{E&xqM)^hj>G');
define('NONCE_SALT', '$orWwn+Axa--jIfRixBwTgP*RS([f$Uou!v<ntP)-dCrS}M=bVNmtY_foDVzsqH@GLlbQMD=s<}BNDfF{HKpjGAcXqish(^]gCwZ>k>y]cIm@c%rusoL$Mo!_c!EDH(?');

/**#@-*/

/**
 * WordPress Database Table prefix.
 *
 * You can have multiple installations in one database if you give each
 * a unique prefix. Only numbers, letters, and underscores please!
 */
$table_prefix = 'wp_jfdi_';

/**
 * For developers: WordPress debugging mode.
 *
 * Change this to true to enable the display of notices during development.
 * It is strongly recommended that plugin and theme developers use WP_DEBUG
 * in their development environments.
 *
 * For information on other constants that can be used for debugging,
 * visit the Codex.
 *
 * @link https://codex.wordpress.org/Debugging_in_WordPress
 */
define('WP_DEBUG', false);

/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');


this is all i have in my wp config

**Comment by khemraj1431** [comment]
Theres nothing script debug in my php...following is the code all i have there.

`<?php
define('WP_CACHE', false); // Added by WP Rocket
/**
 * The base configuration for WordPress
 *
 * The wp-config.php creation script uses this file during the
 * installation. You don't have to use the web site, you can
 * copy this file to "wp-config.php" and fill in the values.
 *
 * This file contains the following configurations:
 *
 * * MySQL settings
 * * Secret keys
 * * Database table prefix
 * * ABSPATH
 *
 * @link https://codex.wordpress.org/Editing_wp-config.php
 *
 * @package WordPress
 */

// ** MySQL settings - You can get this info from your web host ** //
/** The name of the database for WordPress */
define('DB_NAME', 'ss_dbname_gd12k5kh35');

/** MySQL database username */
define('DB_USER', 'tFU8w4HQlDQ56WE');

/** MySQL database password */
define('DB_PASSWORD', 'hKTT0Uht5lTD0vB2');

/** MySQL hostname */
define('DB_HOST', 'marketingmadscom.ipagemysql.com');

/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');

/**#@+
 * Authentication Unique Keys and Salts.
 *
 * Change these to different unique phrases!
 * You can generate these using the {@link https://api.wordpress.org/secret-key/1.1/salt/ WordPress.org secret-key service}
 * You can change these at any point in time to invalidate all existing cookies. This will force all users to have to log in again.
 *
 * @since 2.6.0
 */
define('AUTH_KEY', 'K[z>Xvr)gZmOtP^F%jBmhnzD^(Z[+*n+)+s{(we?yYENTWT]O=Nwbr?n=*]Nqn}jzQFpX]>Tbc//N[ixlRI{?%YV{yP*JdVTuig-TBGQD/$f{doB@%oE=O<b|ZE^O/K}');
define('SECURE_AUTH_KEY', ';sZ]{ep=Ddxu*;JmLGs!&Bi%dEM%<qQIyM;wQjo*HVrAecfom-lwfe}bV>CoOx_Y{N+k;Pcbk[vGTQQQn&GuX<AEbjQs<abJ(=<Z*LxT}Zt=a_cOqU/_XfOJ(p^FOsXy');
define('LOGGED_IN_KEY', 'T{symYnV+<;rT+oeWur%pf-oLBNKq<bC{GHyp<qSlc>{GUk^-Sw/L@iyqWvFMqkvybw]Eh=D$ig^ho[=^DO[yZ]+g/onLMy^{d|>p%dBH<keRCG&?W%)uA(Ckv&QkmGN');
define('NONCE_KEY', 'J(-P<[Rk-XtZfzEJ^m&dwly&<(>|T-[;/!XIPLrHnh%cZ$EsOpf([T]-Tgjffo|XhuroOWgCw@P[Kh;c{^$mv{$tVe|>XJqnI<u]TItbk;@&!R<!=zeFP%k]m}L?ns%N');
define('AUTH_SALT', '@PrLW*)bsoWmUXuE}R(m|zGRZnLCGMDr]GAHAR^W*{/iPS/dr}XKvUacp!h<jxWas)O<yw|!K}Lkp@I%]AfR!(hi=Fv<a<w(gqnaUgYM@Cs+RYVznstK[-MS?^C-nj$s');
define('SECURE_AUTH_SALT', 'bqKPqn;M%M%soLlTaa>RiCLS<xVtHwG[=hRh}K{bel@BM$oP|!WW-ar<fnksD>(cEKLmpE/ru<O{jxG/SPu)-GibV%f*){yVYZ*G|X<wp?_HqBzGeK&lw+I<XdzulJ>A');
define('LOGGED_IN_SALT', 'Q!VQz|kLqrqxdo|?Ro?oo&F*_qrN__W;_jvlMRn%CU+QJpErV^%FAAjj*;wJeJBksgaPC}y&UoQ|fmHryWo$!{heM>**Pzkiqs(&x}U?Zn?L;*Wrol_o{E&xqM)^hj>G');
define('NONCE_SALT', '$orWwn+Axa--jIfRixBwTgP*RS([f$Uou!v<ntP)-dCrS}M=bVNmtY_foDVzsqH@GLlbQMD=s<}BNDfF{HKpjGAcXqish(^]gCwZ>k>y]cIm@c%rusoL$Mo!_c!EDH(?');

/**#@-*/

/**
 * WordPress Database Table prefix.
 *
 * You can have multiple installations in one database if you give each
 * a unique prefix. Only numbers, letters, and underscores please!
 */
$table_prefix = 'wp_jfdi_';

/**
 * For developers: WordPress debugging mode.
 *
 * Change this to true to enable the display of notices during development.
 * It is strongly recommended that plugin and theme developers use WP_DEBUG
 * in their development environments.
 *
 * For information on other constants that can be used for debugging,
 * visit the Codex.
 *
 * @link https://codex.wordpress.org/Debugging_in_WordPress
 */
define('WP_DEBUG', false);

/* That's all, stop editing! Happy blogging. */

/** Absolute path to the WordPress directory. */
if ( !defined('ABSPATH') )
	define('ABSPATH', dirname(__FILE__) . '/');

/** Sets up WordPress vars and included files. */
require_once(ABSPATH . 'wp-settings.php');
`

**Comment by xdima92x** [comment]
Could you add this code - define( 'SCRIPT_DEBUG', true ); after define('WP_DEBUG', false); ?

**Comment by khemraj1431** [comment]
comes Parse error: syntax error, unexpected 'if' (T_IF) in /hermes/bosnaweb24a/b1238/ipg.marketingmadscom/drsufis/wp-config.php on line 87

**Comment by khemraj1431** [comment]
changed..let me see again...basically this problem comes when i use contact form 7 or any other contact form plugin

**Comment by xdima92x** [comment]
okay, but now you don't have this error - 
Live Composer returned JS error
SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 1 column 7476 of the JSON data
File "http://www.drsufis.com/wp-content/plugins/live-composer-page-builder/js/builder.all.min.js?ver=1.2", line 1, char 5214

Correct?

**Comment by khemraj1431** [comment]
hold on...installing contact form 7..let me see if it shows that again

**Comment by xdima92x** [comment]
Okay, I will be waiting :)

**Comment by khemraj1431** [comment]
perfect..now no red spider appearing...so it will not conflict with third party plugins anymore right ?

**Comment by xdima92x** [comment]
I'm sure but I think no :)

**Comment by khemraj1431** [comment]
Thanks..still if I get any error  I will Ping u

**Comment by xdima92x** [comment]
okay, have a great day)
