### ISSUE TITLE
After update blank pages

### ISSUE THREAD

**Issue by allancbrito** [live-composer/live-composer-page-builder#474]
After I updated the plugin all pages of site show a blank page!

Any ideas?

**Comment by xdima92x** [comment]
Hi @allancbrito Please, follow the next steps:
1) Try do deactivate all the other plugins for a minute and see if LC works as expected?
2) Try to activate a default WP theme for a minute and see if LC works as expected?
3) Do you get an error when to activate debugging mode ( define('WP_DEBUG', true); ) in the file wp-config.php? Please [check this screenshot](https://www.evernote.com/shard/s554/sh/dd7d14d3-ecbd-4726-82d5-2bdabbdeb194/332217dc34a982cb) for more details.
Let me know the results, please :)

**Comment by menachemshapiro** [comment]
check which version of php your server is running. It has to be at least version 5.3

**Comment by xdima92x** [comment]
Hi @allancbrito I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
