### ISSUE TITLE
How to sort by custm field

### ISSUE THREAD

**Issue by Ciao121** [live-composer/live-composer-page-builder#476]
Is there a way to sort Posts Element by a custom post's field?
Or any suggestion on how to do it?

Thank you!!

**Comment by Ciao121** [comment]
If someone need to do this and can't wait the feature to be implemented here's how I did it (hardcoding):

in modules/posts/module.php:

AFTER:
```
array(
	'label' => __( 'Comment Count', 'live-composer-page-builder' ),
	'value' => 'comment_count',
	),
```
ADD:
```
array(
	'label' => __( 'Custom Field', 'live-composer-page-builder' ),
	'value' => 'custom_field',
	),
```
REPLACE
```
$args = array(
	'paged' => $paged,
	'post_type' => $post_type,
	'posts_per_page' => $options['amount'],
	'order' => $options['order'],
	'orderby' => $options['orderby'],
);
```
WITH
```
if ($options['orderby']=='custom_field'){
	$args = array(
		'paged' => $paged,
		'post_type' => $post_type,
		'posts_per_page' => $options['amount'],
		'meta_key' => 'YOUR META_KEY HERE',
		'orderby' =>'meta_value_num',
	);
}else{
	$args = array(
		'paged' => $paged,
		'post_type' => $post_type,
		'posts_per_page' => $options['amount'],
		'order' => $options['order'],
		'orderby' => $options['orderby'],
	);
}
```
Now you'll find a "Custom field" option in the "Order by" post's field. Selecting it will sort post with the meta key you used in 'YOUR META_KEY HERE'.
Probably there's a better way to do i. but that's my way.

**Comment by xdima92x** [comment]
Hi @Ciao121 It's a good point. We will improve the sort in the next versions. :)

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/476

**Comment by ben-zahora** [comment]
Hi Ciao,
Thank you for your tip! It's super. Now I have the sorting of project-type posts that I display as events. I includes two ACF fields in the project posts; The start date of the event and the end date of the event. Thanks to your code, I can sort projects by date of starts date. In addition, I've added another useful code that hides posts that have an end date lower than the current date. It can be useful:

REPLACE

<div class="<?php echo $element_class . $columns_class . $extra_class; ?> " data-cats="<?php echo $project_cats_data; ?>">

WITH

<div class="<?php echo $element_class . $columns_class . $extra_class; ?> your-custom-switchclass 
                <?php 	
                  $date_curr = time();
                  $date_to = strtotime(get_field('your-custom-field-to-end-date'));
                  if($date_curr > $date_to)
                  {
                    echo 'your-custom-class-to-hide-element';
                  }
                ?>" data-cats="<?php echo $project_cats_data; ?>">

**Comment by xdima92x** [comment]
At this moment, we can't include in the Live Composer because we have other plans about the plugin. Maybe we add this later but you can use this way.
