### ISSUE TITLE
IE Fixed Background Images Not Working Correctly

### ISSUE THREAD

**Issue by jgajera** [live-composer/live-composer-page-builder#477]
Hey guys,
I'm using Windows 10 and IE 11. Fixed and parallax backgrounds set on row modules (orange modules) are not behaving correctly in IE. Edge works fine. The images are jumping and bouncing on scroll with mousewheel and keyboard.

Video of issue: 
https://youtu.be/_IU7tNbYK8A

**Comment by xdima92x** [comment]
Hi @jgajera It's a not bug of LC. Research on the internet also shows that this bug. Please check this link and let me know if this helps in any way:
https://coderwall.com/p/hlqqia/ie-fix-for-jumpy-fixed-bacground

**Comment by jgajera** [comment]
Hey Dima,
I ended up not using any parallax or fixed BG images on that site because
all of their employees still run IE on their computers (ew!). I tried
several methods - not sure if I tried the one you linked, but I've
bookmarked it for future reference. When it happens again, I'll try the
linked method and report back.

Thanks!
Janki

**Comment by xdima92x** [comment]
Ok) You are welcome
