### ISSUE TITLE
W3 Total Cache Error Disabling LC

### ISSUE THREAD

**Issue by jgajera** [live-composer/live-composer-page-builder#478]
**Error message:**
`Fatal error: Unknown: Cannot use output buffering in output buffering display handlers in Unknown on line 0`

Error shows up when you click "Edit in Live Composer" from page itself and from the WP Edit Page window.

**Comment by xdima92x** [comment]
Hi @jgajera Research on the internet also shows that this error can be related to insufficient PHP and/or WordPress memory but WordPress can’t show the actual error message related to lack of memory due to caching or buffering.

**Comment by jgajera** [comment]
Hey @xdima92x I apologize, I thought it was an LC problem because my whole site was built with LC. If I find this has to do with LC, I'll reply back again. Thanks for your help!
