### ISSUE TITLE
JS Error in pop up

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#479]
t 25184

Live Composer returned JS error
TypeError: undefined is not an object (evaluating 'a.html().trim')
File "http://.../wp-content/plugins/live-composer-page-builder/js/builder.all.min.js?ver=1.2", line 4, char 19294

**Comment by xdima92x** [comment]
Hi Vlad) Please check this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/479
