### ISSUE TITLE
Disable all default styling

### ISSUE THREAD

**Issue by klickagent** [live-composer/live-composer-page-builder#483]
Is there a way to disable the default styling of the modules?
I would like to build a theme which can be edited afterwards by the user via live composer. Unfortunately all the settings are already set (eg. default font-familiy is set to Lato in the Infobox module). They cannot be unset through the init options in the theme (or did I simply not find it?).
<img width="230" alt="screen shot 2017-01-13 at 19 25 41" src="https://cloud.githubusercontent.com/assets/1005929/21940772/1fb5d1d0-d9c6-11e6-8d53-a618fc22df4f.png">

If I manually remove the std value in the code of the module of Infobox I achieve what I want. But this will only last until I am updating Live composer the next time:
<img width="228" alt="screen shot 2017-01-13 at 19 28 01" src="https://cloud.githubusercontent.com/assets/1005929/21940859/6bb3c862-d9c6-11e6-9202-0c96756f7efb.png">

Thanks for your help.

**Comment by xdima92x** [comment]
Hi @klickagent You can use this code - http://snippi.com/s/t55blir Let me know the results, please if it helped :)

**Comment by klickagent** [comment]
Oh. My bad. That's working like a charm. And I can also reset all values by just passing `$new_defaults = false;`. Perfect. Thanks a lot!

**Comment by klickagent** [comment]
That is working perfectly.
