### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#484]
t 25294

PHP Fatal error:  Call to undefined function  json_last_error() in /home2/geoffcol/public_html/sound-design/wp-content/plugins/live-composer-page-builder/includes/display-functions.php on line 907

https://www.evernote.com/l/Ajm0hpkoZAhAC5PoaeTzEb60wHnNARH6Hlw

**Comment by xdima92x** [comment]
Hi) What version of PHP are you running? json_last_error() was added in 5.3.0. You need to update your PHP.
