### ISSUE TITLE
JavaScript error (thickbox)

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#485]
t 25084

JavaScript error detected in a third-party plugin 
Uncaught ReferenceError: thickboxL10n is not defined 
File "http://.../wp-includes/js/thickbox/thickbox.js?ver=3.1-20121105", line 9, char 23

**Comment by xdima92x** [comment]
Hi) Research on the internet also shows that this error. It's not a bug in the Live Composer. Maybe the error is coming from a third-party plugin. Please disable all the third-party plugins one by one until you find the one causing the troubles. Maybe clear your cache.

**Comment by FoldingTheme** [comment]
@xdima92x wp-includes/js/thickbox/thickbox.js is a WordPress core file.
