### ISSUE TITLE
Text Element / Mobile responsive part is MISSING font controls

### ISSUE THREAD

**Issue by mozalan** [live-composer/live-composer-page-builder#486]
When editing "Text Element" and enabling "Renponsive", both: Tablet & Mobile sections are missing the font choice & style controls.

![mobile responsive section no font controls](https://cloud.githubusercontent.com/assets/20672449/22019395/5d8ec09c-dcab-11e6-8153-9d66109a7b82.PNG)

**Comment by xdima92x** [comment]
Hi :) You can select font family in the section 'styling'. I'm sorry but I don't understand what it is style controls? What do you mean?

**Comment by xdima92x** [comment]
Hi @mozalan I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
