### ISSUE TITLE
Some troubles with newest version

### ISSUE THREAD

**Issue by adelahomutova** [live-composer/live-composer-page-builder#487]
Hi!
I just updated my Live Composer to version 1.2 and I find some troubles:

1. I have grey 1px solid border around content of tabs even though there wasn't any before I updated this plugin. All borders are set to width: 0 and border-color #fff (I have white background on my page).

2. When I activate live composer and edit one part of page (it doesn't matter if it's tabs, text, HTML....), I can't edit another part before I refresh whole page. I can't click on any part of page content.

Is anything wrong with my installation or it's a bug?

Thanks :)

**Comment by MasterPayne** [comment]
It's a bug.

My TABS element also won't disable borders no matter how many times I adjust the values to 0. Looks good while in Edit mode, but in live mode the grey border reappears. Doesn't matter if the tabs are aligned left or on top.

I don't think they test all variables before publishing an update.

**Comment by lumberman** [comment]
@adelahomutova please try to update Live Composer to version 1.2.1. We have some borders functionality fixed there.

@MasterPayne there is no way for us to test all the possible variations at this point. Thank you for showing this problem.

@xdima92x please check border settings for tabs and accordion modules. Make sure it's fixed and tested asap. Thank you!

**Comment by adelahomutova** [comment]
I've updated my Live composer but I still have same troubles - borders and I cannot edit more parts without refreshing page.

**Comment by xdima92x** [comment]
Hi @adelahomutova Could you record a video?

**Comment by adelahomutova** [comment]
Here is the video - sorry for bad quality, it's forbidden to record anything in our office with cameras or PC software.
You can see, that even though I set white border (on white background) and 0 border width, there is grey border when I turn live composer off. And the second problem - after I edit one part, I can't edit another without refreshing the page.
https://drive.google.com/file/d/0B8omqaP58Bo-dVp3ZFN2SnVpVGM/view?usp=sharing

And I have another problem - in modules.css is set too high value of z-index here: #dslc-content .dslc-navigation - it will cover almost every menu bar when scrolling.

**Comment by xdima92x** [comment]
Hi @adelahomutova 

1) Borders Color - Please test this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/487_v2
2) You getting the error detected in your video. Can you copy a message and send me? 

Please, follow the next steps:
a) Open your website for editing in a private/incognito mode. Let me know if it's any different.
b) Try do deactivate all the other plugins for a minute and see if LC works as expected? This way we can tell if any other plugins cause the issue.
c) Try to activate a default WP theme for a minute and see if LC works as expected? This way we can tell if there is a problem with your theme.

3) 'In modules.css is set too high value of z-index here: #dslc-content .dslc-navigation - it will cover almost every menu bar when scrolling.' - Please open new issue for this.
