### ISSUE TITLE
Mouse Scroll Does Not Work on Requirements Elements

### ISSUE THREAD

**Issue by arte-dg** [live-composer/live-composer-page-builder#497]
I'm putting together the new layout of my blog using the livecompouser plugin, but by inserting some codes like google ads or Disqus' comments the mause on top of these elements does not work at all.

See example in this link: http://desenvolvedorweb.net/saia-do-zero-03-instalando-o-xampp/

see this video: https://www.facebook.com/douglasgasparalves/videos/1219347374822871/

Does anyone know the reason?

**Comment by xdima92x** [comment]
Hi @arte-dg Please, see this link - https://www.facebook.com/groups/livecomposer/permalink/1657716147588498/
