### ISSUE TITLE
404 Template Not Working - PHP Issue

### ISSUE THREAD

**Issue by jessicahawkins3344** [live-composer/live-composer-page-builder#502]
After creating a 404 template under Appearances -> Templates, and then testing by going to a page that doesn't exist... the template is not displayed and I have this error

    
    Warning: array_key_exists(): The first argument should be either a string or an integer in     /srv/www/jsquared/htdocs/web/app/plugins/live-composer-page-builder/includes/post-templates.php on line 70

    Warning: array_key_exists(): The first argument should be either a string or an integer in /srv/www/jsquared/htdocs/web/app/plugins/live-composer-page-builder/includes/post-templates.php on line 71

**Comment by xdima92x** [comment]
Hi @jessicahawkins3344  Can you please try latest Live Composer? It works. I recorded a short video - https://drive.google.com/file/d/0B7nJlmCX4yHueVRLbnZ2NEVVVW8/view
