### ISSUE TITLE
Inline editor: wrong button hover colors

### ISSUE THREAD

**Issue by lumberman** [live-composer/live-composer-page-builder#503]
https://www.evernote.com/l/AAEkCZO1MdBKIKZcgdn0AcYDNYeYQPWVkoo

**Comment by xdima92x** [comment]
Hi @lumberman I tested this issue but I don't have this problem. I recorded a short video - https://drive.google.com/file/d/0B7nJlmCX4yHuWndoT0RIMmVKd0k/view
