### ISSUE TITLE
Issues with color picker and ideas on how to improve

### ISSUE THREAD

**Issue by lumberman** [live-composer/live-composer-page-builder#506]
I would have attached an image, but... 

Using the TEXT module H1 as an example, scroll to the right to the end, under "Text Shadow" color picker. Clicking on "Select Color" causes the whole "Text Shadow" box to expand. And the color picker alpha slider is missing. Also, compared to the Font color picker at the other end, the Hex color box appears to be transposed above. 

Gotta ask, what was wrong with the original color picker? It worked fine. In fact it worked great. I could copy/paste hex codes with ease. I could even manually enter something like "rgb 255, 150, 0" hit ENTER and it would translate into hex perfectly. This new color picker is just clunky. I have to double-click or click + CTRL-A to select all the data or click and use my keyboard arrow keys to adjust a single value. Sometimes it won't even capture a complete entry or show a correct color sample. 

Also, what's the point of having random color choices just above the Apply button? All of them have an alpha of "0!"

**Comment by CreativeSau** [comment]
Experienced the same issue, which drove me crazy. Found the issue lying at line 22 of builder.plugins.js.

The condition parameter `&& r.match(/^[0-9a-fA-F]{3}$/)` is screwing everything up, removing it fixes the input issue.

**Comment by FoldingTheme** [comment]
no problem with the last plugin version
