### ISSUE TITLE
Minifying CSS & JS

### ISSUE THREAD

**Issue by jessicahawkins3344** [live-composer/live-composer-page-builder#507]
Is there a reason why the plugin css files and js files aren't minified? They always come up in performance test or page speed tests, and I was just wondering why that isn't done for production?

**Comment by jgajera** [comment]
+1

**Comment by ryanhilton** [comment]
Yeah, that's not a bad idea. Also, for extra compression, you could gzip the output, via htaccess.

**Comment by lumberman** [comment]
We removed compression and minimization to get better error reports. We will introduce it back once no new JS errors reported. You can compress, minimize any js/css files on your website with W3 Total Cache plugin.

Sorry for this inconvenience.
