### ISSUE TITLE
problem with asociate template to dynamic pages

### ISSUE THREAD

**Issue by ben-zahora** [live-composer/live-composer-page-builder#510]
I've "Js Suppor Ticket" plugin installed in my site. The plugin has a front-end api on specific page with specific URL e.g. .../support. The page is produced by Live Composer: module html inserting shortcodes. Until this moment is every fine. But if user click on his front-end message under JS Support module, web goes to page url under the parent page, e.g: ../support/my-tickets. The URL is created dynamicaly with Js support Ticket (or other) plugin. With older Live composer every works good, but in 1.2 version is the page clean, and button "create template" was shown in left bottom corner. Isn't no solution, because Js Support Ticket's not be in Live composer template list. This may do problems with all child dynamicaly created pages in general. Solution may be in introduction of inheritance parent's template.

**Comment by xdima92x** [comment]
Hi @ben-zahora Could you record a video about this problem for more details?

**Comment by xdima92x** [comment]
Hi @ben-zahora I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
