### ISSUE TITLE
Cannot change Blog Title to H2, H3 or H4 for SEO purpose

### ISSUE THREAD

**Issue by friedcoffee** [live-composer/live-composer-page-builder#525]
For SEO purposes, it's a benefit to use the various header tags within limits. For this purpose in the blog element, there should be an option to use the titles as H2 or H3.

**Comment by xdima92x** [comment]
Hi @friedcoffee The Blog module already use the titles as h2. If I am missing something, please elaborate more, send a screenshot, e.t.c.
