### ISSUE TITLE
SEO issue in the blog section

### ISSUE THREAD

**Issue by friedcoffee** [live-composer/live-composer-page-builder#527]
When we use the blog section with Prev/Next or numbered tabs, Google indexes the next tabs as page1, page2 which is not a good thing for SEO

**Comment by lumberman** [comment]
Please, provide more details and why it's bad.
How it can be better?

**Comment by friedcoffee** [comment]
I have a site, [Friedcoffee](www.friedcoffee.com), and the front page is designed using Live Composer. I have 8 main sections for which I need to use H2 tags. The page also has a blog section in which the titles of posts consume the H2 tags which I don't want as they are less important section than the main ones above. SEO hierarchy simply says that H1 is the most important and than H2, after that H3 and so on. Many SEO tools also recommend to use H2 headings below 10 as they will confuse the search crawlers less and direct them to important sections for more importance.

**Comment by xdima92x** [comment]
Hi @friedcoffee You can read these issues #564 and #525. I hope that helps.
