### ISSUE TITLE
Find and elegant way to have icons in navigation...

### ISSUE THREAD

**Issue by lumberman** [live-composer/live-composer-page-builder#529]
Find and elegant way to have icons in navigation module for menu items.
Probably by using menu item class option via JS?
+ Styling controls in the module settings

**Comment by jgajera** [comment]
@lumberman does it work if you install FontAwesome script, add CSS classes onto menu items, and add "fa fa-email" to the CSS class?

**Comment by FoldingTheme** [comment]
the feature is now in Mega Menu extension.
