### ISSUE TITLE
Shortcodes Ultimate conflict

### ISSUE THREAD

**Issue by mozalan** [live-composer/live-composer-page-builder#532]
Once it's installed, LiveComposer is not responding to edits. Elements drag & drop won't work as well.

This plugin is widely used by many, could you please check this out and find a solution for it? - many thanks in advance.

**Comment by mozalan** [comment]
Hey Dima, has it been solved now?

**Comment by xdima92x** [comment]
Hi @mozalan I'm sorry, not yet. We can't promise to fix any soon.

**Comment by xdima92x** [comment]
Hi Goshgar Mammadov) I recorded a short video for you - https://drive.google.com/file/d/0B7nJlmCX4yHuUDNZQzlPRE9EeFE/view It works. 
1) Try do deactivate all the other plugins for a minute and see if LC works as expected with Shortcodes Ultimate?
2) Try to activate a LC theme for a minute and see if LC works as expected with Shortcodes Ultimate?

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.

**Comment by Halopend** [comment]
I've been having the same issue, here is a copy of the error code:

:  Uncaught Error: Call to undefined function is_plugin_active() in /var/www/html/wp-content/plugins/shortcodes-ultimate/inc/core/tools.php:252
Stack trace:
#0 /var/www/html/wp-content/plugins/shortcodes-ultimate/inc/core/generator.php(94): su_addon_active(Array)
#1 /var/www/html/wp-includes/class-wp-hook.php(286): Su_Generator::popup('')
#2 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook-&gt;apply_filters(NULL, Array)
#3 /var/www/html/wp-includes/plugin.php(453): WP_Hook-&gt;do_action(Array)
#4 /var/www/html/wp-includes/general-template.php(2630): do_action('wp_footer')
#5 /var/www/html/wp-content/themes/astra/footer.php(32): wp_footer()
#6 /var/www/html/wp-includes/template.php(688): require_once('/var/www/html/w...')
#7 /var/www/html/wp-includes/template.php(647): load_template('/var/www/html/w...', true)
#8 /var/www/html/wp-includes/general-template.php(76): locate_template(Array, true)
#9 /var/www/html/wp-content/themes/astra/page.php(58): get_footer()
#10 /var/www/html/wp-includes/template-loader.php(7 in <b>/var/www/html/wp-content/plugins/shortcodes-ultimate/inc/core/tools.php</b> on line 252)

**Comment by fishfree** [comment]
I have the same issue!. @xdima92x please reopen this issue.

**Comment by xdima92x** [comment]
Please update to the latest version of Live Composer and use the module 'Shortcode'.
