### ISSUE TITLE
A serious bug to be resolved related to URL

### ISSUE THREAD

**Issue by friedcoffee** [live-composer/live-composer-page-builder#544]
Few days ago, I was getting strange 404 errors like http://sitename.com/page2/%post-id% not found and that were not just one it was like page2, page3, page4 also. I thought it was some indexing error and ignored. Today while tweaking the loading button on the live composer, I checked a strange thing...
When I go to page 2 in the blog or page 3 and, the URL above become http://sitename.com/page2 or page3. Now when I click to any section from that page, it goes to http://sitename/page2/%post-id% instead of going to http://sitename.com/%post-id%. 
I guess this should be checked. It's only working fine when using Load more button. With other options, it's strange.

**Comment by xdima92x** [comment]
Hi @friedcoffee The permalinks are a Wordpress Core feature. Please go to Wordpress Admin -> Settings -> Permalinks -> and try with post name option.
