### ISSUE TITLE
Arabic Google Fonts

### ISSUE THREAD

**Issue by HYBargouth** [live-composer/live-composer-page-builder#545]
Please include Arabic Google-fonts names in the (ds-live-composer.php) file.  I already did it manually through editing the file on my cPanel file manager, but I was told that any update the plugin will erase all modifications.

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/400

**Comment by HYBargouth** [comment]
Great job guys. Thumbs up.
