### ISSUE TITLE
Background image of Navigation Element

### ISSUE THREAD

**Issue by xdima92x** [live-composer/live-composer-page-builder#547]
I tried to put in a navigation background image, but it is not stretching the entire width. only the selected portion with the menu items.

https://www.evernote.com/shard/s554/sh/6021838a-cdf4-4aa8-8135-58b05902c2d3/6ccf2d82aa6cf19c

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/547

**Comment by lumberman** [comment]
- [ ] Did you create visual tests for all the cases?
- [ ] Did you check if code from the previous versions do not break?
