### ISSUE TITLE
Plugin Load Time

### ISSUE THREAD

**Issue by friedcoffee** [live-composer/live-composer-page-builder#551]
Plugin load time is taking a larger portion. The area in red is the load time for Live Composer
![load time](https://cloud.githubusercontent.com/assets/23068420/22677656/62f74db8-ed1a-11e6-9bf9-cfd2e2220366.jpg)

**Comment by friedcoffee** [comment]
I also feel like some bugs occur when JS and CSS are minified through W3 Total Cache plugin. Is it fully compatible with it?

**Comment by xdima92x** [comment]
Hi @friedcoffee The page builder drives almost all the content of the website, so is normal to take a large consumption percentage. However, there are two other plugins who do small jobs and take more than LC. On the other hand, not the percentage is important (40%), but the general time of loading. 40% of 1 minute loading time is something, and 40% from 10 minutes, is another thing. :)
