### ISSUE TITLE
Module InfoBox - Icon as a picture

### ISSUE THREAD

**Issue by xdima92x** [live-composer/live-composer-page-builder#553]

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/553

**Comment by lumberman** [comment]
@xdima92x  

- [ ] Can you place now the image in the same places as icon (top/right)?
- [ ] Did you create visual tests for all the cases?
- [ ] Did you check if code from the previous versions do not break?
