### ISSUE TITLE
Backed Content in WP Editor

### ISSUE THREAD

**Issue by xdima92x** [live-composer/live-composer-page-builder#554]
https://www.evernote.com/shard/s554/sh/6b34d00b-b866-4750-90e6-096a74ba5f80/4c818b4e8a274543

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/554

**Comment by lumberman** [comment]
1. The line has a wrong style: https://cl.ly/0l0o2n1a0X1u Make it look as on original screenshot https://www.evernote.com/shard/s554/sh/6b34d00b-b866-4750-90e6-096a74ba5f80/4c818b4e8a274543

2. Change 'Open in Live Composer' to 'Open it in Live Composer'

3. When Page Builder tab is active, no need to show this line: https://cl.ly/0n2C2B2k0S36
