### ISSUE TITLE
Woo Products Carousel Bug - Shows part of previous image

### ISSUE THREAD

**Issue by Silcarus** [live-composer/live-composer-page-builder#555]
https://drive.google.com/file/d/0B22SOQDbIwDKLWxLZlVVZlVTMjQ/view

The right side of the previous image appears on the left. This only happens on phone view.

**Comment by jgajera** [comment]
+1 seeing the same thing (only on phone as well) for Testimonials carousel - may be an issue on all carousels.

https://www.facebook.com/groups/livecomposer/permalink/1687931267900319/

**Comment by jgajera** [comment]
Any updates here? I've been trying to fix it on my own, but I can't figure out what's wrong with it.

**Comment by jgajera** [comment]
figured it out: .dslc-carousel-item: margin-left must be set to 0px, may have to use media query for just mobiles

**Comment by Silcarus** [comment]
I wonder if this will be fixed in LC.
Thanks for figuring out the issue, @jgajera

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/issues/555

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/555
