### ISSUE TITLE
Editor Messages can't be dismissed

### ISSUE THREAD

**Issue by senning** [live-composer/live-composer-page-builder#556]
The [Editor Message bar](https://github.com/live-composer/live-composer-page-builder/issues/533) (currently hard-coded to promote WooCommerce integration) can't be dismissed - the hide button is hidden, and even when shown it doesn't do anything. It also does not appear to check whether WooCommerce integration is actually installed. This is annoying for most users, but makes it impossible to recommend as a plugin for clients.

**Comment by xdima92x** [comment]
Hi @senning If you update the last 1.2.7 plugin version you can hide a panel - https://www.evernote.com/shard/s554/sh/b8b616c2-929f-40c7-9d21-cca78816408c/2d593b0f15fc7fe5

**Comment by xdima92x** [comment]
If you have more questions about this, please write here.
