### ISSUE TITLE
Remove ads embedded at bottom of UI

### ISSUE THREAD

**Issue by MasterPayne** [live-composer/live-composer-page-builder#558]
I get u gotta make some money off this aside from support but really, I'm already hurting for screen real estate and can't believe you couldn't leave ads in the dashboard.

How do I remove the ads at the bottom of the UI please?

**Comment by Quaked** [comment]
I have to agree. I updated LC and all of a sudden there's ads in it. Keep it in the admin dashboard please. Having it in editing mode for "non-admins" or editors is just in the way of the already cluttered edit mode.

For now I'm stuck with having to do this:
```PHP
add_action('admin_head', 'lc_admin_ad_fix');
function my_custom_fonts() { echo '<style>.dslca-container{margin-bottom:0 !important;}.dslca_editor_messages_section {display:none !important;}</style>'; }
```

But that might remove "important" messages as well.

**Comment by MasterPayne** [comment]
Who knew it could get worse...just updated to v1.2.4, stupidly hoping the ad was removed, except now it's broken!
C'mon guys! There soooo much more that needs to be improved and added, why instead devote coding time to nonsensical 'features' that in this case just cheapen the experience.
Sadly i gotta give props to Quaked for his 'fix.' thx bro!

**Comment by mozalan** [comment]
Supporting above... Ads are okay to be displayed in a dashboard but "editing mode" are not helping anybody... especially new users who has no or very little experience with editing..

**Comment by Quaked** [comment]
Unfortunately I got fed up and dropped LC for Elementor. All the "premium" stuff and CPT's enabled by default and the entire direction this seems to be going made my choice easy in the end.

**Comment by MasterPayne** [comment]
Quaked I get your frustration, and you might already be gone so this might be pointless, but for me 2 points:

1. I'm willing to give them a chance to right this ship - get rid of the ads and I'm ok.
2. I tried Elementor, but it works no different for the most part than all the other WP dashboard editors - they don't allow you to really build out a whole site, just page by page.

LC has them beat because it's still the only one that is front-end and I can build a whole site from header/nav to footer. Elementor you gotta use a theme, style that theme header/nav + footer and then use something like Elementor to build the inner content stuff. what's the difference between this and something like Visual Composer? Even something like Beaverbuilder which looks a lot like Elementor is behind LC too because you again have to work around another theme.

Just my opinion ;)

**Comment by Quaked** [comment]
As a developer and having had a look at elementor a bit more thoroughly all I can say it's in my favor for what I need it to do. "Front-end" editing is just a matter of adding a button much like LC. But as said, primarily for the developer aspects more than the user. I make themes so for this end it suits me better. That's all. I was finding myself having to figure out how to modify LC and tweak it in one way or another whereas Elementor is very straight forward without "bloat".

I guess it boils down to taste and end-use :) I might go LC in the future if they rethink as well.

**Comment by xdima92x** [comment]
Hi guys) If you update the last 1.2.7 plugin version you can hide a panel - https://www.evernote.com/shard/s554/sh/b8b616c2-929f-40c7-9d21-cca78816408c/2d593b0f15fc7fe5

**Comment by xdima92x** [comment]
If you have more questions about this, please write here.
