### ISSUE TITLE
Error Detected!!! Tablet version doesn't work in version 1.2.3 

### ISSUE THREAD

**Issue by DaviDH15** [live-composer/live-composer-page-builder#559]
Hello!

Developers, please check tablet version. 
Here is a screenshot: http://prnt.sc/e6gbyx

Thanks

**Comment by xdima92x** [comment]
Hi @DaviDH15 I tested Live Composer with the theme LC Blank and Orao. It's not a problem LC. Please check your CSS code.

**Comment by xdima92x** [comment]
Hi @DaviDH15  I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
