### ISSUE TITLE
Row vertical content alignment 

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#562]
t 25512

Consider adding the vertical alignment feature for the row content.
On the fullscreen layout, the content is top aligned and the vertical padding is not an appropriate solution.

Ex: https://www.evernote.com/l/AjnmRgHro_1Ahq94SiRMmZai81L3QVaRFDo

**Comment by xdima92x** [comment]
You use the module 'Separator' for row vertical content alginment in the Live Composer
