### ISSUE TITLE
Customizable Containers

### ISSUE THREAD

**Issue by jtwebguy** [live-composer/live-composer-page-builder#563]
Would love to be able to customize containers. Is this being worked on? If not i would like to help.

**Comment by lumberman** [comment]
We are working on new generation of the page builder were rows and columns has the same functionality and styling as module. There are not plans to make it possible in the current generation of the Live Composer. 

We are open for any code customizations if you make it well coded and tested.

**Comment by xdima92x** [comment]
If you have more questions about this, please write here.
