### ISSUE TITLE
Subpages getting indexed despite the Setting

### ISSUE THREAD

**Issue by friedcoffee** [live-composer/live-composer-page-builder#564]
In the use of blog module, subpages like **%sitename%/%category%/page/2** are getting indexed by Google causing duplicate content issues. 
![subpage](https://cloud.githubusercontent.com/assets/23068420/22869942/1d7eef08-f1c9-11e6-87e8-37825f5e9989.jpg)
I am using Yoast and have deindexed the subpage settings.

**Comment by xdima92x** [comment]
Hi @friedcoffee The pagination is a WordPress core feature. If you are looking to exclude the low value pages from Google indexing, this article may be helpful: http://orbitingweb.com/blog/wp-archive-noindex/
