### ISSUE TITLE
After update from version 1.2.3 to 1.2.4, problem with CSS in menu bar

### ISSUE THREAD

**Issue by AlainMelsens** [live-composer/live-composer-page-builder#585]
Hello,
After doing the update from version 1.2.3 to 1.2.4 I have a CSS problem in the menu.
With version 1.2.4 the background from the menu bar is automatically extended (longer) and this is not what I want.
![lc version124 menu wrong](https://cloud.githubusercontent.com/assets/25772012/22933993/9e449282-f2cd-11e6-9eae-3301b65098c1.jpg)

See the good layout in the menu with version 1.2.3.:
![lc version123 menu ok](https://cloud.githubusercontent.com/assets/25772012/22934005/a5b69d9e-f2cd-11e6-9725-846480bb804a.jpg)

Please, can you change this back as the version 1.2.3?
This was happening automatically after doing the update, without changing anything in LC Header.
Thanks in advance.
Alain Melsens

**Comment by xdima92x** [comment]
Hi @AlainMelsens In the version 1.2.3 was a bug. The background was a short and BG Image of settings worked not a correctly - https://www.evernote.com/shard/s554/sh/27ce75ac-6c6c-41e5-9d1c-db688cf965e0/49c676f9c4dbb398 If you want to use a short of background you can add this CSS - https://www.evernote.com/shard/s554/sh/fe901e37-d42b-478e-ba77-7d23ff707e16/b01089dc9503780c

**Comment by AlainMelsens** [comment]
Thank you verry much for this quick reply. And your explanation is good, because I have resolved the problem also fast.
Again, thank you so much. I'm glad that I can work with the latest version of LC.
