### ISSUE TITLE
Better update descriptions

### ISSUE THREAD

**Issue by MasterPayne** [live-composer/live-composer-page-builder#586]
Can we get even a brief description of what was updated? I'm noticing in past 3 update you post like "Bug fixes: See closed issues for milestone 1.2.x on GitHub"

I follow link and every entry read "**No description provided**." And i see title of "Editor Messages 2 #557." What is that saying to me?

How can we provide feedback if we don't know what's new???

**Comment by xdima92x** [comment]
Hi @MasterPayne Thanks) We will improve a description in the next release.
