### ISSUE TITLE
Live Composer configuration notice

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#587]
t 25825

https://www.evernote.com/l/AjlxHEwk-PNNIr0kzwnSaMsoEGUVT_Skfqc

The link to "read more" leat to this page: 

https://www.evernote.com/l/Ajl_4_CZ4z1ERLPBJh90NHcOQSxjjB_pKvc

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/587
