### ISSUE TITLE
Gallery elements button

### ISSUE THREAD

**Issue by CLD3sign** [live-composer/live-composer-page-builder#590]
Hi! 

Is it possible to add a couple of functions to the gallery elements button?

First option to open in a new tab. Especially when there are multiple galleries on a page.

Second option, is it possible to add a function for a gallery's content to open with the gallery's lightbox and be positioned either under or next to the lightbox?

Thanks.

![screen shot 2017-02-16 at 18 31 38](https://cloud.githubusercontent.com/assets/25828712/23037675/32a8abd6-f47f-11e6-99a1-f1b5fa1d727a.png)

**Comment by xdima92x** [comment]
Done
