### ISSUE TITLE
Mobile menu zoom issue

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#592]
On iPhone, when the mobile menu (burger icon) is clicked, a zoom effect is applied to the page. The page remain in "zoom" after closing the menu. [Check this screencast](https://www.dropbox.com/s/siitjzosa2j3aq7/demo-mobile-menu-zoom-issue.mp4). 

On android mobiles, there is no such issues.

**Comment by lumberman** [comment]
@xdima92x This should fix it: http://stackoverflow.com/questions/4472891/how-can-i-disable-zoom-on-a-mobile-web-page
