### ISSUE TITLE
White Space after upgrade to the latest WP & LC

### ISSUE THREAD

**Issue by mozalan** [live-composer/live-composer-page-builder#594]
When going to "EDIT WITH LIVE COMPOSER" you can see everything is there and working with effects etc, but as soon as you publish and come out of it, it displays white space where elements suppose to be shown. I have checked PHP version, is the latest "7" and WordPress is up to date, have disabled all other plugins except just LC - to no avail. Website is using "AVADA theme" and it was perfectly fine before upgrading from LC Version 1.1.4 to Version 1.2.4.

Please check below screen cast:

https://youtu.be/t2WxY1is9tI

**Comment by mozalan** [comment]
Tried version 1.2.5... still the same. Everything work on EDIT mode, but once published, gets disappeared... Tried different PHP version to no avail.

Any comment?... at all?

**Comment by xdima92x** [comment]
Hi @mozalan
1) Try to activate a default WP theme or LC Blank them for a minute and see if LC works as expected?
2) Did you try to re-save a current page?

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
