### ISSUE TITLE
problem when there are multiple modules with same preset on the same page

### ISSUE THREAD

**Issue by menachemshapiro** [live-composer/live-composer-page-builder#595]
Please take a look at this page: https://bananabeachcr.com/packages

I'm trying to setup multiple identical groups of images and text boxes. I used one preset for all the images and another preset for all the text boxes. There are 11 in all.

Whenever I make a change to one of the text boxes, all the other text boxes reload.It takes forever, and then when publishing the page it often runs out. 

Is there a solution for this?

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/595
