### ISSUE TITLE
Page Editor is blank page, published webpage still loads, but can't edit it.

### ISSUE THREAD

**Issue by menachemshapiro** [live-composer/live-composer-page-builder#596]
Related to: #595 

---------
When trying to edit the page mentioned in the issue linked to above ( https://bananabeachcr.com/packages ), it was taking a long time to publish and timing out. I tried saving as a draft, but that did not complete. The spinner just kept spinning. I tried refreshing the page, but now the page editor will not load properly, it just shows a blank page. I am able to see the published page if I go directly to it, but when I try to edit it in Live Composer it does not load.

I have attached the dlsc_code for the page. It is 280k, which seems large, but I don't know if that is causing the problem.

[dlsc_code.txt](https://github.com/live-composer/live-composer-page-builder/files/786331/dlsc_code.txt)

Any way to recover the page without losing all my data and having to recreate the page?

**Comment by FoldingTheme** [comment]
t  25956

**Comment by menachemshapiro** [comment]
To fix this, I had to raise some of the limits to wordpress and php. I don't know if I had to raise them as high as I did, but here's what I raised them to:
PHP:
max_input_vars = 10000;
max_execution_time = 36000;
-----
Wordpress (in wp-config.php):
define('WP_MEMORY_LIMIT', '96M');
