### ISSUE TITLE
Support for Custom Fields in LC modules

### ISSUE THREAD

**Issue by IkeTen** [live-composer/live-composer-page-builder#597]
Support for custom fields and popular custom fields plugins in Live Composer modules. 
Using custom fields in LC is not very easy, using field shortcodes have their limits. Support for custom fields in LC modules will be a game changer. Thanks

**Comment by IkeTen** [comment]
@lumberman  @xdima92x  can custom fields be supported by default in LC?

**Comment by xdima92x** [comment]
Hi @IkeTen There will be a new plug-in in April and you can use a custom fields.

**Comment by IkeTen** [comment]
@xdima92x thanks for the info. Looking forward to it.
