### ISSUE TITLE
Post_Grid Thumbnail Not Appearing for Blog Posts

### ISSUE THREAD

**Issue by KevinCos07** [live-composer/live-composer-page-builder#601]
Hi,

I am currently working on a blog with Live composer plugin. The Post_Based functionality which displays posts in a grid format. It is not able to pull the thumbnail from the blog post for some reason. Can you please help me with the same. Queries:-

Does the plugin uses image within the blog post and resizes the same into a thumbnail?
Do we need to store the images in the galleries for some reason?

Kindly help me if you have any guide for the same

Regards
Kevin

**Comment by xdima92x** [comment]
Hi @KevinCos07 I recorded a short video - https://drive.google.com/file/d/0B7nJlmCX4yHudHF5WjNCNnNtcjA/view The module 'Blog' can pull the thumbnail from the blog post. Did you add the thumbnail in your post?

**Comment by xdima92x** [comment]
Hi @KevinCos07 I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
