### ISSUE TITLE
Menu subnav box cannot be moved down - overlapping issue

### ISSUE THREAD

**Issue by mozalan** [live-composer/live-composer-page-builder#602]
When adding subnav items to the menu, it doesn't allow the background box to be moved down, padding only pushes the writing - items, not the box itself. Please see from the screen shot.
![subnav container padding](https://cloud.githubusercontent.com/assets/20672449/23255761/ac7bbed2-f9b4-11e6-8957-72e045ab3d21.jpg)

**Comment by mozalan** [comment]
no update yet?

**Comment by xdima92x** [comment]
Hi @mozalan Can you check - https://github.com/live-composer/live-composer-page-builder/issues/602 ?

**Comment by xdima92x** [comment]
Hi @mozalan Could you record a screencast? I cannot recreate this bug. I recorded a short video - https://drive.google.com/file/d/0B7nJlmCX4yHuOVJiZ3loS3pnSVU/view I have used the theme 'LC Blank'. Maybe do you have a problem in your CSS?

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
