### ISSUE TITLE
Info box module issue on IE11

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#623]
t: 26180
The images are not displayed correctly on IE.
https://www.evernote.com/l/AjlQHc39udRPJI4J9GYBAXeJvE9jNYw-Zig

**Comment by mozalan** [comment]
It's been reported few times before, unfortunately no solution has been provided for this one, I did manage to get it to work before with a set of rules for browsers but it failed again, once the LC got updated and those rules didn't apply anymore. This must be resolved urgently, many users still on "Windiows 7" and using IE11...

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/623
