### ISSUE TITLE
Gallery Slider Mobile vs Desktop - URL Issue

### ISSUE THREAD

**Issue by jgajera** [live-composer/live-composer-page-builder#624]
Gallery slider on mobile links to gallery, not custom URL (you can also click on the photo in mobile)

Same slider on desktop links to custom URL (clicking on photo does not lead to any URL)

**Comment by xdima92x** [comment]
Hi @jgajera This is an option https://www.evernote.com/shard/s554/sh/52cdee4f-f261-44f2-a925-e80445a336ca/81937288564c48e9 only for the module 'Galleries'.

**Comment by jgajera** [comment]
I know it's an option in the Gallery. I have inserted the custom URL there. It is a bug on the mobile view. Watch this video - I have the custom URL set. On desktop - it behaves correctly. On mobile - it goes to gallery-view, not the custom URL. https://youtu.be/72iLrtvg69s

**Comment by xdima92x** [comment]
Hi @jgajera It is a not bug because the module 'Gallery Sliders' doesn't use this option. You need to use the module 'Gallery'. I recorded a short video - https://drive.google.com/file/d/0B7nJlmCX4yHuNWtqeHBYelJuTzQ/view

**Comment by xdima92x** [comment]
If you have more questions about this, please write here.

**Comment by jgajera** [comment]
I used 303 redirects to fix the issue on my own. Your video didn't take
into account what my video showed. The mobile click-through link is not the
custom URL. Thanks anyway.
