### ISSUE TITLE
Getting error when I try to publish footer

### ISSUE THREAD

**Issue by rasolaw** [live-composer/live-composer-page-builder#625]
tested on multiple browsers (Firefox, Chrome, Safari)
![screen shot 2017-03-07 at 9 04 08 pm](https://cloud.githubusercontent.com/assets/10764549/23651448/ad03e162-0379-11e7-901e-30bbd77983bb.png)

**Comment by rasolaw** [comment]
Same happens with the header...
![screen shot 2017-03-07 at 9 11 28 pm](https://cloud.githubusercontent.com/assets/10764549/23651774/b0c0e9b6-037a-11e7-9815-0d52986f783b.png)

**Comment by rasolaw** [comment]
Tried to create a new header/footer and same error

**Comment by xdima92x** [comment]
Hi @rasolaw 

a) Open your website for editing in a private/incognito mode. Let me know if it's any different.
b) Try do deactivate all the other plugins for a minute and see if LC works as expected? 
c) Try to activate a default WP theme for a minute and see if LC works as expected?

**Comment by rasolaw** [comment]
Hi there,

Tried all three options and I still get the error message.

Warm regards,

Rafael Orellana

||  +61 487 900 833
||  www.linkedin.com/in/rafaelorellana
||  raf@chivo.com.au

**Comment by xdima92x** [comment]
Hi @rasolaw 
1) What kind of hosting or server do you have? Maybe is a problem in your hosting.
2) What Version of PHP Are You Using?

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.

**Comment by rasolaw** [comment]
fixed itself with recent plugin update...

Warm regards,

Rafael Orellana

||  +61 487 900 833
||  www.linkedin.com/in/rafaelorellana
||  raf@chivo.com.au
