### ISSUE TITLE
Projects Categories

### ISSUE THREAD

**Issue by Kleytinho** [live-composer/live-composer-page-builder#631]
I need a litle help...

I used this code for single.php:

`	      

	        if ( is_singular('post') ) {

	           get_template_part( 'loop-single', 'single' ); 

	        } elseif ( 'dslc_projects' == get_post_type() ) {

	        	get_template_part( 'loop-project', 'single' );

	        }
            
 `

If post(normal), ok
elseif post_type=dslc_projects, ok

I would like to use the same idea for category.php:

if normal category, loop from this category
if project category, loop from this category project

Thank you for now...

**Comment by xdima92x** [comment]
Hi @Kleytinho You can create projects (archive) - https://www.evernote.com/shard/s554/sh/c101d63b-4386-4604-a88f-2c5540acab89/b1fcfc363d99cc65

**Comment by xdima92x** [comment]
Hi @Kleytinho If you have more questions about this, please write here.
