### ISSUE TITLE
SyntaxError: JSON.parse

### ISSUE THREAD

**Issue by mdemori** [live-composer/live-composer-page-builder#632]
Hi, 

**my configuration:**

- Linux
- Apache webserver
- PHP 5.6.30
- WP 4.7.3
- Theme Awaken (https://it.wordpress.org/themes/awaken/)
- Currently active plugins
  redux-framework
all-in-one-schemaorg-rich-snippets
category-image-header
categorytinymce
contact-form-7-honeypot
contact-form-7
debug-bar-actions-and-filters-addon
debug-bar
duplicate-post
enhanced-tooltipglossary
facebook-social-stream
hide-category
hide-featured-image
instagram-feed
lc-module-video-embed
list-category-posts
live-composer-page-builder
shareaholic
spam-honeypot
tinymce-advanced
wordfence
wordpress-seo
wp-optimize
youtube-embed-plus
nextgen-gallery

when i try to edit a page, i receive the below error inside the "red bug" icon:

```
Live Composer returned JS error
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 6316 of the JSON data
File "http://devmachine01.test/wp-content/plugins/live-composer-page-builder/js/builder/builder.codegeneration.functions.js?ver=1.2.5", line 264, char 23
```

I immediately realized that the problem is related to an strange `<p>` tag that is inserted at the end of the JSON string located inside the hidden text area that contain the code that will be rendered as component by LiveComposer (dslca-section-code class text areas).

After almost 3 hours of digging inside the code, i cant' find the real problem source.
After finding where the dslca-section-code section is created i check the code and to verify what happen i saved the result in a file before sending it to the browser to check if the code is filled with some strange characters or with an unexpected newline but the json seem clean.

So, as a first step i immediately disabled `wpautop` filter using below code inside my child theme functions.php

```
remove_filter( 'the_content', 'wpautop' );
remove_filter( 'the_excerpt', 'wpautop' );
```
but this change don't solve the problem, then I used fiddler to check if the code is create server side with this unexpected paragraph tags and the paragraph is already there directly from the server, take a look at below screenshot

![fiddler](https://cloud.githubusercontent.com/assets/2266315/23843568/1f2d063c-07bd-11e7-8250-4e90f6946be9.png)

The next test has been disabling each plugin one by one but also this solution seem that don't solve the problem.

After another hour of debugging without finding any problem on server side, and with a really urgent needed to fix this problem,  I  final code a quick and dirty solution as a js client side fix  inside the **builder.codegeneration.functions.js**:

```
// Get current JSON.
modulesSectionJsonString = modulesSection.find('.dslca-section-code').val();
if(modulesSectionJsonString != undefined){
    modulesSectionJsonString = modulesSectionJsonString.substr(0, modulesSectionJsonString.lastIndexOf('}')+1));
  	modulesSectionJson = JSON.parse(modulesSectionJsonString);
  }else{
  	return false;
  }

```

I know that is a really bad solution but I'm really stuck with this problem and i can't understand where the problem is created, probably is some filter that has been placed from one of my plugin but i can't understand why even disabling all plugins the problem is still here.

My next step is to rebuild the dev machine with a clean WP installation to check if the problem will disappear (the problem is obviously also on production machine) but is time consuming task so, before taking this action, someone has any suggestion? 

Below you will find full output from  application messages on browser console with error on with both SCRIPT_DEBUG and  dslcDebug set to true

```
JQMIGRATE: Migrate is installed with logging active, version 1.4.1  jquery-migrate.js:23:2
dslc_ui_animations  builder.animations.functions.js:17:20
JQMIGRATE: jQuery.fn.load() is deprecated  jquery-migrate.js:45:4
console.trace():  jquery-migrate.js:47
	migrateWarn http://devmachine01.test/wp-includes/js/jquery/jquery-migrate.js:47:5
	jQuery.fn[name] http://devmachine01.test/wp-includes/js/jquery/jquery-migrate.js:560:3
	scrollerPlugin http://devmachine01.test/wp-content/plugins/live-composer-page-builder/js/builder/builder.scroller.functions.js:80:3
	<anonymous> http://devmachine01.test/wp-content/plugins/live-composer-page-builder/js/builder/builder.scroller.functions.js:90:2
	n.Callbacks/i http://devmachine01.test/wp-includes/js/jquery/jquery.js:2:27444
	n.Callbacks/j.fireWith http://devmachine01.test/wp-includes/js/jquery/jquery.js:2:28213
	.ready http://devmachine01.test/wp-includes/js/jquery/jquery.js:2:30004
	K http://devmachine01.test/wp-includes/js/jquery/jquery.js:2:30366
dslc_module_options_box_shadow  builder.settings.panel.functions.js:1456:19
dslc_module_options_text_shadow  builder.settings.panel.functions.js:1488:19
JQMIGRATE: Migrate is installed with logging active, version 1.4.1  jquery-migrate.js:23:2
JQMIGRATE: jQuery.fn.load() is deprecated  jquery-migrate.js:45:4
console.trace():  jquery-migrate.js:47
	migrateWarn http://devmachine01.test/wp-includes/js/jquery/jquery-migrate.js:47:5
	jQuery.fn[name] http://devmachine01.test/wp-includes/js/jquery/jquery-migrate.js:560:3
	<anonymous> http://devmachine01.test/wp-content/plugins/live-composer-page-builder/js/frontend/main.js:1111:1
dslc_drag_and_drop  builder.uigeneral.functions.js:455:19
dslc_generate_code  builder.codegeneration.functions.js:135:19
dslc_generate_section_code  builder.codegeneration.functions.js:223:19
dslc_generate_section_code  builder.codegeneration.functions.js:223:19
SyntaxError: JSON.parse: unexpected non-whitespace character after JSON data at line 1 column 6316 of the JSON data[Learn More]  builder.codegeneration.functions.js:264:23
	dslc_generate_section_code http://devmachine01.test/wp-content/plugins/live-composer-page-builder/js/builder/builder.codegeneration.functions.js:264:23
	dslc_generate_code/< http://devmachine01.test/wp-content/plugins/live-composer-page-builder/js/builder/builder.codegeneration.functions.js:190:24
	.each http://devmachine01.test/wp-includes/js/jquery/jquery.js:2:2879
	n.prototype.each http://devmachine01.test/wp-includes/js/jquery/jquery.js:2:844
	dslc_generate_code http://devmachine01.test/wp-content/plugins/live-composer-page-builder/js/builder/builder.codegeneration.functions.js:186:2
	window.previewAreaTinyMCELoaded http://devmachine01.test/wp-content/plugins/live-composer-page-builder/js/builder/builder.uigeneral.functions.js:86:3
	<anonymous> http://devmachine01.test/:2183:4
YT API ready  ytprefs.js:226:29
```

**Comment by xdima92x** [comment]
Hi @mdemori 
1. Try do deactivate all the other plugins for a minute and see if LC works as expected?
2. Try to activate a default WP theme or LC Blank for a minute and see if LC works as expected?

I use LC 1.2.7 and LC Blank. I don't have this bug - https://www.evernote.com/shard/s554/sh/462fddb3-7c41-4ca7-a102-48367e39c9e7/313b80c001032949

**Comment by mdemori** [comment]
hi @xdima92x 

Sorry for a so late reply but I'm become crazy with this issue! the problem is create by "enhanced-tooltipglossary" aka "CM Tooltip Glossary".
The most big problem for debugging this issue has been that the the error is completely random, sometime the plugin change links inside the JSON (adding some sort of escaping with "/" )  and sometime add some <br /> as already explained in my first message.

Now i will contact the plugin creator and asking for a solution.

thank you for your support.
