### ISSUE TITLE
Video Background Options

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#644]
Hey guys,

Can we please get youtube/vimeo as backgrounds in rows please?

For loading purposes, data size etc I think it's needed and most other builders offer it,

Thanks :)

**Comment by jgajera** [comment]
+1 and adding functionality of having it muted/loop/other video properties would be nice also.

**Comment by mozalan** [comment]
Backing up above, there are lots of functionalities could be added to LC and I don't really understand why it takes so long to get them added to the builder, most of these features requested long time ago and still not availabe, please dedicate more effort into it and make all your users happy 👍

**Comment by xdima92x** [comment]
https://github.com/live-composer/lc-extensions/issues/73
