### ISSUE TITLE
Shortcode Module not displaying styling options

### ISSUE THREAD

**Issue by menachemshapiro** [live-composer/live-composer-page-builder#646]
I don't think the stylings are working properly for the shortcode module. I set the stylings, and until I hit "confirm" the stylings show up (such as background color, border color, border radius, box shadow). As soon as I hit confirm, the styling disappears. I hit save and refresh the page, no stylings. 

You can see the page here: https://bananabeachcr.com/test

If it matters, the shortcode I'm using is from NextGen Gallery.
---
Here's the row code, and it looks like the styling settings are in the code, but they are not displaying on the page.

---------------------------------------------
`[{"element_type":"row","columns_spacing":"spacing","custom_class":"","show_on":"desktop tablet phone","section_instance_id":"2df388e1dfe","custom_id":"","type":"full","bg_color":"","bg_image_thumb":"disabled","bg_image":"","bg_image_repeat":"repeat","bg_image_position":"left top","bg_image_attachment":"scroll","bg_image_size":"auto","bg_video":"","bg_video_overlay_color":"#000000","bg_video_overlay_opacity":"0","border_color":"","border_width":"0","border_style":"solid","border":"top right bottom left","margin_h":"0","margin_b":"0","padding":"80","padding_h":"0","content":[{"element_type":"module_area","last":"no","first":"yes","size":"6","content":[{"css_show_on":"desktop tablet phone","content":"[ngg_images source=\\\"galleries\\\" container_ids=\\\"2\\\" display_type=\\\"photocrati-nextgen_pro_mosaic\\\" row_height=\\\"150\\\" margins=\\\"5\\\" last_row=\\\"nojustify\\\" lazy_load_enable=\\\"1\\\" lazy_load_initial=\\\"3\\\" lazy_load_batch=\\\"7\\\" captions_enabled=\\\"0\\\" captions_display_sharing=\\\"1\\\" captions_display_title=\\\"1\\\" captions_display_description=\\\"1\\\" captions_animation=\\\"slideup\\\" order_by=\\\"sortorder\\\" order_direction=\\\"ASC\\\" returns=\\\"included\\\" maximum_entity_count=\\\"500\\\"]","error_proof_mode":"active","css_custom":"disabled","css_main_bg_color":"#babad8","css_main_border_color":"#babad8","css_main_border_width":"7","css_main_border_trbl":"top right bottom left ","css_main_border_radius_top":"15","css_main_border_radius_bottom":"15","css_margin_bottom":"0","css_min_height":"0","css_main_padding_vertical":"0","css_main_padding_horizontal":"0","css_main_box_shadow":"0px 0px 25px 0.5px #000000","css_main_font_size":"13","css_main_font_weight":"400","css_main_font_family":"Open Sans","css_main_font_style":"normal","css_main_line_height":"22","css_main_margin_bottom":"25","css_main_text_align":"left","css_h1_font_size":"25","css_h1_font_weight":"400","css_h1_font_family":"Open Sans","css_h1_font_style":"normal","css_h1_line_height":"35","css_h1_margin_bottom":"15","css_h1_text_align":"left","css_h2_font_size":"23","css_h2_font_weight":"400","css_h2_font_family":"Open Sans","css_h2_font_style":"normal","css_h2_line_height":"33","css_h2_margin_bottom":"15","css_h2_text_align":"left","css_h3_font_size":"21","css_h3_font_weight":"400","css_h3_font_family":"Open Sans","css_h3_font_style":"normal","css_h3_line_height":"31","css_h3_margin_bottom":"15","css_h3_text_align":"left","css_h4_font_size":"19","css_h4_font_weight":"400","css_h4_font_family":"Open Sans","css_h4_font_style":"normal","css_h4_line_height":"29","css_h4_margin_bottom":"15","css_h4_text_align":"left","css_h5_font_size":"17","css_h5_font_weight":"400","css_h5_font_family":"Open Sans","css_h5_font_style":"normal","css_h5_line_height":"27","css_h5_margin_bottom":"15","css_h5_text_align":"left","css_h6_font_size":"15","css_h6_font_weight":"400","css_h6_font_family":"Open Sans","css_h6_font_style":"normal","css_h6_line_height":"25","css_h6_margin_bottom":"15","css_h6_text_align":"left","css_li_font_size":"13","css_li_font_weight":"400","css_li_font_family":"Open Sans","css_li_line_height":"22","css_ul_margin_bottom":"25","css_ul_margin_left":"25","css_ul_style":"disc","css_ol_style":"decimal","css_ul_li_margin_bottom":"10","css_li_border_width":"0","css_li_border_trbl":"top right bottom left","css_li_border_radius_top":"0","css_li_border_radius_bottom":"0","css_li_padding_vertical":"0","css_li_padding_horizontal":"0","css_inputs_bg_color":"#fff","css_inputs_border_color":"#ddd","css_inputs_border_width":"1","css_inputs_border_trbl":"top right bottom left","css_inputs_border_radius":"0","css_inputs_color":"#4d4d4d","css_inputs_font_size":"13","css_inputs_font_weight":"500","css_inputs_font_family":"Open Sans","css_inputs_line_height":"23","css_inputs_margin_top":"0","css_inputs_margin_bottom":"0","css_inputs_width":"100","css_inputs_padding_vertical":"10","css_inputs_padding_horizontal":"15","css_blockquote_bg_img_repeat":"repeat","css_blockquote_bg_img_attch":"scroll","css_blockquote_bg_img_pos":"top left","css_blockquote_border_width":"0","css_blockquote_border_trbl":"top right bottom left","css_blockquote_border_radius_top":"0","css_blockquote_border_radius_bottom":"0","css_blockquote_font_size":"13","css_blockquote_font_weight":"400","css_blockquote_font_family":"Open Sans","css_blockquote_line_height":"22","css_blockquote_margin_bottom":"0","css_blockquote_margin_left":"0","css_blockquote_padding_vertical":"0","css_blockquote_padding_horizontal":"0","css_blockquote_text_align":"left","css_button_bg_color":"#5890e5","css_button_bg_color_hover":"#5890e5","css_button_border_color":"#5890e5","css_button_border_color_hover":"#5890e5","css_button_border_width":"0","css_button_border_trbl":"top right bottom left","css_button_border_radius":"3","css_button_color":"#fff","css_button_color_hover":"#fff","css_button_font_size":"13","css_button_font_weight":"500","css_button_font_family":"Open Sans","css_button_line_height":"13","css_button_padding_vertical":"10","css_button_padding_horizontal":"15","css_anim":"none","css_anim_delay":"0","css_anim_duration":"650","css_anim_easing":"ease","css_load_preset":"none","module_instance_id":"23a3ab742ca","post_id":533,"dslc_m_size":"12","module_id":"DSLC_Shortcode","element_type":"module","last":"yes","dslc_m_size_last":"yes","module_render_nonajax":true}]}],"dslca-img-url":""}]`
---------------------------------------------

**Comment by xdima92x** [comment]
Hi @menachemshapiro Please check this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/646. I fixed it. Please tell me if it works. I used the plugin Ninja Forms. I recorded a short video - https://drive.google.com/file/d/0B7nJlmCX4yHuTWxIYXZldjZlZ2s/view

**Comment by menachemshapiro** [comment]
@xdima92x I tested it, and it worked. I had to open the module for editing and then resave the page, but you can see that the stylings are now working properly. https://bananabeachcr.com/weddings

**Comment by menachemshapiro** [comment]
Because I'm using a fork, will the plugin automatically update the next time an update is released, or will I have to manually update?

**Comment by xdima92x** [comment]
Hi @menachemshapiro In the next update, you need to delete the fork and install a new LC.
