### ISSUE TITLE
dslc_content_for_search & dslc_code are displayed in every page

### ISSUE THREAD

**Issue by konmavrakis** [live-composer/live-composer-page-builder#647]
In every page I get a new ``<dl class="post-fields">...</div>`` where ``dslc_content_for_search`` and ``dslc_code`` are shown containing information like this:

```
[{"element_type":"row","columns_spacing":"spacing","custom_class":"","show_on":"desktop tablet phone ","section_instance_id":"0a670f0dba9","custom_id":"","type":"wrapper","bg_color":"","bg_image_thumb":"disabled","bg_image":"","bg_image_repeat":"repeat","bg_image_position":"left top","bg_image_attachment":"scroll","bg_image_size":"auto","bg_video":"","bg_video_overlay_color":"#000000","bg_video_overlay_opacity":"0","border_color":"","border_width":"0","border_style":"solid","border":"top right bottom left","margin_h":"0","margin_b":"0","padding":"80","padding_h":"0","content":[{"element_type":"module_area","last":"yes","first":"no","size":"12","content":[{"css_show_on":"desktop tablet phone","content":"[smartslider3 slider=1]","error_proof_mode":"active","css_custom":"disabled","css_main_border_width":"0","css_main_border_trbl":"top right bottom left","css_main_border_radius_top":"0","css_main_border_radius_bottom":"0","css_margin_bottom":"0","css_min_height":"0","css_main_padding_vertical":"0","css_main_padding_horizontal":"0","css_main_font_size":"13","css_main_font_weight":"400","css_main_font_family":"Open Sans","css_main_font_style":...
```

I've truncated the ``<dl class="post-fields">`` with JS but it adds load time to the page.

I'm on: WordPress: 4.7.3 & Live Composer: 1.2.6.

If this is supposed to happen, can someone explain the reason why? 

Thanks a lot in advance.

**Comment by xdima92x** [comment]
Hi @konmavrakis Try do deactivate all the other plugins for a minute and see if LC works as expected?

**Comment by konmavrakis** [comment]
Hey @xdima92x, I'm only using Live Composer and Smart Slider 3. After I've deactivated Smart Slider 3, Live Composer still displayed dslc_content_for_search and dslc_code. Let me know if you need anything else.

**Comment by xdima92x** [comment]
Hi @konmavrakis Maybe do you have a problem with a theme? Try to activate a default WP theme or LC Blank for a minute and see if LC works as expected? Can you record a short video with your problem?

**Comment by konmavrakis** [comment]
Hey @xdima92x, turns out that the theme is causing it. I've used Twenty Fifteen and it doesn't output anything related to the issue. The theme I'm using is [Simplicity by Gavick](https://www.gavick.com/wordpress-themes/simplicity). Here is a screenshot with what I'm getting: 

![image](https://cloud.githubusercontent.com/assets/5990379/24443679/430379d6-146c-11e7-8200-1ba3d171b6db.png)

Notice that I've added a ``display: none`` in order to remove them from the screen. Above DevTools you can see what is outputted in the webpage, right after the main content that has been created with Live Composer.

**Comment by xdima92x** [comment]
Hi @konmavrakis You can ask to contact the theme developer for assistance on this.

**Comment by xdima92x** [comment]
It is a not problem of LC.
