### ISSUE TITLE
Shortcodes are getting converted to html

### ISSUE THREAD

**Issue by urbanimatic** [live-composer/live-composer-page-builder#648]
Hi there,

In tabs module, i click the "Open in WP editor" option because i want to use a shortcode as the content of the tab. It looks fine on the front-end but when i go back to make a change to the shortcode, everything is converted to html.

Here are some screenshots.
The shortcode: https://monosnap.com/file/NZbyX4xI8fta0eHUyo6SX707RUIjcB.png
The result after pressing confirm -> confirm :  https://monosnap.com/file/8dII90hSz8ez94ufpRwGe1eZeDogsg.png
And the "text/html" version: https://monosnap.com/file/ksYHWMQpqw4rznAqPQoK02FzubvYld.png

Any solution to this?

Thanks in advance

**Comment by urbanimatic** [comment]
After updating to 1.2.8 shortcode module appears to have the same issue described above for tabs module...it converts the shortcode to html which is something that makes shortcodes useless...for example in my case i use shortcode for a restaurant menu plugin(by motopress) the plugin uses a custom post type for the menu items, categories etc...if the shortocde is converted to html then any changes made to menu items are not getting updated.

I hope it makes sense

**Comment by xdima92x** [comment]
Hi @urbanimatic Please check this code - https://github.com/live-composer/live-composer-page-builder/tree/issue/677

**Comment by urbanimatic** [comment]
The above issues appear to be fixed in branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/677

The live composer editor seems a bit slower when using branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/677 but i might be wrong.

**Comment by frankcorneliusmartin** [comment]
This bugfix is released in 1.2.9, however I updated the plugin today and i also encounter exactly this issue. Am I missing something?
