### ISSUE TITLE
"Show on" feature is missing from the "Blog module"

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#659]
At this moment is no way to hide the "Blog module" from desktop, tablet or phone. [See this screenshot.](https://www.evernote.com/l/Ajkhgqf6SgRMv5xn_bCXQrG3SsppxAOpVr8)

These options are missing from the module.

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/659
