### ISSUE TITLE
Error message after update to 1.2.8

### ISSUE THREAD

**Issue by jffx2** [live-composer/live-composer-page-builder#675]
Hi,

Since I updated to version 1.2.8 the following message appears at the top of each of my pages in WordPress Admin

Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'lcstickymodules_inactive_notice' not found or invalid function name in /home/speakrightspeakq/public_html/speakrightspeakup.ca/wp-includes/class-wp-hook.php on line 298

However, everything appears to be working fine.

Thanks

**Comment by xdima92x** [comment]
Hi @jffx2 Please check this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/677

**Comment by jffx2** [comment]
Hi,Thanks for responding, however, the link returns a 404 page not found error.Regards,Jeanette


-------- Original Message --------
Subject: Re: [live-composer/live-composer-page-builder] Error message
after update to 1.2.8 (#675)

**Comment by xdima92x** [comment]
Hi @jffx2 I'm sorry. Please to update the LC until a version 1.2.9 and let me know if you have this problem.

**Comment by jffx2** [comment]
Hi Dima,I have updated to LC 1.2.9 and I still have the following message on all of my WordPress Admin screens.Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'lcstickymodules_inactive_notice' not found or invalid function name in /home/speakrightspeakq/public_html/speakrightspeakup.ca/wp-includes/class-wp-hook.php on line 298Thanks.Regards,Jeanette


-------- Original Message --------
Subject: Re: [live-composer/live-composer-page-builder] Error message
after update to 1.2.8 (#675)

**Comment by xdima92x** [comment]
Hi @jffx2 
1) Try do deactivate all the other plugins for a minute and see if LC works as expected? 
2) Try to activate a default WP theme for a minute and see if LC works as expected?

**Comment by jffx2** [comment]
Hi Dima,I have tried your suggestions below.  The error message disappears when I deactivate the LC - Sticky Modules plug-in.Regards,Jeanette


-------- Original Message --------
Subject: Re: [live-composer/live-composer-page-builder] Error message
after update to 1.2.8 (#675)

**Comment by xdima92x** [comment]
Hi @jffx2 It's not problem LC. You need to send a message of developer plugin about this problem. :)

**Comment by jffx2** [comment]
Will do.  ThanksJeanette FiremanAccess Success Data Management Solutions Inc.403-801-2235


-------- Original Message --------
Subject: Re: [live-composer/live-composer-page-builder] Error message
after update to 1.2.8 (#675)
