### ISSUE TITLE
Error message(visible only when using editor) after updating to 1.2.8

### ISSUE THREAD

**Issue by urbanimatic** [live-composer/live-composer-page-builder#676]
Hi there,

After updating to 1.2.8 i have issues with the shortcode module as well, i explain here: https://github.com/live-composer/live-composer-page-builder/issues/648#issuecomment-293473908

Also i just have noticed that when using live composer editor i see this message(twice) at the top: Notice: Undefined index: view in .../wp-content/plugins/mp-restaurant-menu/classes/shortcodes/class-shortcode-item.php on line 38

This message is only visible when editor is vissible, for example if i click the "hide editor" button, tha message disappears as well.

Also when the shortcode module is used in a page/template i'm editing in live composer i cannot publish any changes, for example i can click the confirm button but when i click the "publish changes" it does absolutely nothing

For the moment i will roll back to the previous version of live composer.

**Comment by urbanimatic** [comment]
Sorry for the multiple messages, as an addition that might be helpful, this is what;s on line 38 mentioned above:

`$mprm_view_args['action_path'] = "shortcodes/menu/{$args['view']}/item";`

below is what that line is part of

`	public function render_shortcode(array $args) {
		global $mprm_view_args;
		Media::get_instance()->add_plugin_js('shortcode');
		$mprm_view_args = $args;
		$mprm_view_args['action_path'] = "shortcodes/menu/{$args['view']}/item";
		return View::get_instance()->get_template_html('shortcodes/menu/index', $args);
	}`

**Comment by xdima92x** [comment]
Hi @urbanimatic Please check this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/677

**Comment by urbanimatic** [comment]
Hi @xdima92x this issue appears to be fixed in branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/677

I have one suggestion though...since most shortcodes are provided by third party plugins are already come with styling and most of the times the average user expects to get the styling of the plugin(as shown in demos etc). My suggestions is to have the styling options of the shortcode modules turned of by default and the user will be able to turn on the ones he.she wants to modify.
