### ISSUE TITLE
Download element TEXT color issue

### ISSUE THREAD

**Issue by mozalan** [live-composer/live-composer-page-builder#682]
Download element button text color doesn't work.

![button color](https://cloud.githubusercontent.com/assets/20672449/25065880/4d124974-220f-11e7-9879-43e67ed32287.PNG)

**Comment by xdima92x** [comment]
Hi @mozalan I recorded a short video - https://drive.google.com/file/d/0B7nJlmCX4yHuS0EtSFFmNGoxS2s/view It works. Maybe you have cache issue or the styles are overwritten by your theme or a third-party plugin. Let me know if module works :)

**Comment by mozalan** [comment]
Text color, not the background...

**Comment by mozalan** [comment]
The button content - text, if you want it to display in a different color, it doesn't work.

**Comment by xdima92x** [comment]
Hi @mozalan I recorded a short video - https://drive.google.com/file/d/0B7nJlmCX4yHuR1ZUR19VMmYzZ0E/view It works. Could you send me your website? Try to activate a default WP theme for a minute and see if LC works as expected?

**Comment by mozalan** [comment]
Hi Dima, I've de-activated / re-activated LC and it started working. Another glitch I guess..
