### ISSUE TITLE
Image Element - Custom Text no link?!

### ISSUE THREAD

**Issue by mozalan** [live-composer/live-composer-page-builder#683]
Hi guys, as per title, Image Element Custom Text doesn't have any linking facility. Could you please add that to the element? In example, I'd like to have image pointing to particular page but below custom text to point to another site, so it should really have its own linking.

![image element custom text](https://cloud.githubusercontent.com/assets/20672449/25070764/478a74be-229f-11e7-9530-2e9f63dea93c.PNG)

**Comment by mozalan** [comment]
Having a facility where custom text could have an URL linking, would make life much easier for many. Please don't forget to add it to the next version. Many thanks in advance

**Comment by xdima92x** [comment]
At this moment you can add href ( https://www.w3schools.com/tags/att_a_href.asp ) in custom text. Maybe later we integrate it in the LC. At this moment we work on other improvements for Live Composer.
