### ISSUE TITLE
Images NOT displaying in WP Editor

### ISSUE THREAD

**Issue by tbenci** [live-composer/live-composer-page-builder#686]
When I add images to the WP editor using the ADD MEDIA they appear fine. Closing the editor, saving etc. all work fine and the page displays correctly.

When I go back into the page and open WP editor some (or all) of the images are NOT displaying but have the image icon only.

![missing image](https://cloud.githubusercontent.com/assets/7336557/25309169/1753a6f2-2809-11e7-8d47-38837dad6132.png)

This is really inconvenient. Is is a bug, is there a setting incorrect? It is NOT a ISP or server issue as I have sites on a number of different ISPs and they ALL do it.

Cheers
Tony Benci

**Comment by xdima92x** [comment]
Hi @tbenci,
Thanks for contacting us. Unfortunately, I'm not sure I understand correctly this issue. Please confirm we are talking about live composer page builder. Your screenshot is not explanatory. Looking forward to your answer.

**Comment by tbenci** [comment]
Hi Dima,

As you can see, in normal page edit mode the image is displayed (1). When I load the page in the WP editor the image is NOT displayed (2).

Some do, some don't no pattern I can discern.

Thanks
Tony
![images](https://cloud.githubusercontent.com/assets/7336557/25433831/3a00fdb4-2acd-11e7-9cfa-ec2d823858d6.png)

**Comment by xdima92x** [comment]
Hi, Tony! Thank you for the reply. There are no known reports about this. Please open a ticket on our support system following this link: https://livecomposerplugin.com/support/support-request/. This way your installation can be debugged. If the problem will be related to a plugin bug, we will open again this ticket. Thanks for understanding.
