### ISSUE TITLE
Link Panel NOT closing

### ISSUE THREAD

**Issue by tbenci** [live-composer/live-composer-page-builder#687]
Howdy all,

When you click on a link within WP editor the edit window opens correctly. If you have remained mouse over the link and close the editor the edit window stays open and is a damned nuisance.

![link panel](https://cloud.githubusercontent.com/assets/7336557/25309207/f68d9c10-2809-11e7-8d68-0393857f7f7d.png)

Once again, bug or setting?

Cheers
Tony

**Comment by xdima92x** [comment]
Hi @tbenci,
Looking at your screenshot, I see that you are using a plugin which is not developed by us. We are the developers of the live composer page builder.

**Comment by tbenci** [comment]
Hi Dima,

I installed live composer out of the box... what plugin are you talking about. To the best of my knowledge the install is exactly what you provided.

Cheers
Tony

**Comment by xdima92x** [comment]
Hi, Tony! Thank you for the reply. There are no known reports about this. Please open a ticket on our support system following this link: https://livecomposerplugin.com/support/support-request/. This way your installation can be debugged. If the problem will be related to a plugin bug, we will open again this ticket. Thanks for understanding.
