### ISSUE TITLE
Update to LC Version 4.7.4 removed Wordpress Menus and Widgets

### ISSUE THREAD

**Issue by andymontgomerysweden** [live-composer/live-composer-page-builder#688]
A recent update to LC has removed my Wordpress Menu from Wordpress itself and also my Wordpress Widgets menu. This has also affected the entire site by removing any menus and widget areas.

**Comment by Airinrojas** [comment]
I've also the same problem, both of us are ussing ORAO THEME.

**Comment by xdima92x** [comment]
Hi @andymontgomerysweden and @Airinrojas  Please read this - https://www.facebook.com/groups/livecomposer/permalink/1790538670972911/
