### ISSUE TITLE
The Menu and widgets Areas has dissapeared on LC (ORAO theme)

### ISSUE THREAD

**Issue by Airinrojas** [live-composer/live-composer-page-builder#689]
just updated live composer on a site and the menu dissapeared along with the Wordpress Menu options and Widget Options. Please Help!!!!!

**Comment by xdima92x** [comment]
Hi @Airinrojas Please read this - https://www.facebook.com/groups/livecomposer/permalink/1790538670972911/ If you have more questions about this, please write here. :)
