### ISSUE TITLE
Galleries Grid Button

### ISSUE THREAD

**Issue by jgajera** [live-composer/live-composer-page-builder#698]
Is it possible to get the button icon to move to the right in the Galleries module, similar to how you can choose left/right in the button element module?

<img width="957" alt="github" src="https://cloud.githubusercontent.com/assets/24979618/25461612/23019dec-2aa7-11e7-91ab-9b6a20417da1.PNG">

**Comment by xdima92x** [comment]
Hi @jgajera  https://www.evernote.com/shard/s554/sh/2f1d48b1-e34a-4ac8-8af3-356119a18787/64e219a2d350d9c4 is it?

**Comment by jgajera** [comment]
Hey @xdima92x thanks for the quick reply!

No, that's simply aligning the button. I'm referring to aligning the icon on left or right of the button text (right now, the only option is to keep icon to the left of the button text).

For example, in my screenshot, there is an option for "icon-margin right" because the icon is fixed to stay on the left, requiring a right margin to space things out. The button module has the option for icon left/right with margin right/left, was hoping for a similar feature on the Galleries/Projects modules.

I hope this makes sense!
