### ISSUE TITLE
Parallax effect and animations not working on Internet Explorer

### ISSUE THREAD

**Issue by Greatmind1Admin** [live-composer/live-composer-page-builder#699]
Hi Guys!

My big problem is that the parallex effect and the animations are not working on internet explorer, other browsers work fine.

My site: http://www.greatmind.de

What can I do to fix this?

**Comment by xdima92x** [comment]
Hi @Greatmind1Admin
1) Parallax - It's a not bug of LC. Research on the internet also shows that this bug. Please check this link and let me know if this helps in any way:
https://coderwall.com/p/hlqqia/ie-fix-for-jumpy-fixed-bacground
2) Animations - The animations don't work in the IE.

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
