### ISSUE TITLE
when you are binding the events ? 

### ISSUE THREAD

**Issue by techsaqib** [live-composer/live-composer-page-builder#700]
hi i want to know when and where you are binding the controls to elements for live update and how 
please tell me as soon as possible 

and what this function doeas 			LiveComposer.Builder.UI.loadOptionsDeps();

and what is use of obeservale , why u use that 

please reply as soon as possible

**Comment by FoldingTheme** [comment]
for support please use  https://livecomposerplugin.com/support/support-request/
thank you!
