### ISSUE TITLE
TEXT ELEMENT missing alpha slider

### ISSUE THREAD

**Issue by 5pointDigital** [live-composer/live-composer-page-builder#701]
Guys or guy, I'm guessing only 1 person is left working on this project. I'm at 4 weeks for a response from "Laur" at support, which is unacceptable. Now I'm here. As a marketing professional I suggested many times to again sell Live Composer and stop spending quality coding time embedding advertising in the UI. At only 40k installs (Beaver Builder and Elementor are at 400k +) someone has to realize obnoxious rotating ad revenue ain't gonna sustain this project much longer. Regardless, please consider getting rid of support all together or at least finding another person to help out.

1. On April 3rd I asked about Templates for pages. Laur replied, "This month we intend to release a new extension ('Live Composer - Templates for CPT') which will allow you to create templates for pages." "This month" came and went without even smoke signals.
2. On April 4th I noticed an issue and sent another email; "TEXT ELEMENT > all text element "Text Shadow" (Content, H1, H2, H3, links, etc.) Color settings are missing an alpha slider - see my screen cap. I have to manually add something like, "rgba(255, 255, 255, .75)." Again, crickets.

I've been with LC for about 3 years. Not only do I occasionally contribute to this project in my free time by answering questions on the WordPress plugin page, but I paid twice for the project when it was still on CodeCanyon. As such, I was given the impression support would be hours not months. And I understand the lag if only 1 person is  working on Live Composer, but can I at least get an acknowledgment my support tickets are being read?

![lc-txt-shadow-no-alpha](https://cloud.githubusercontent.com/assets/28401201/25715283/e2b83318-30af-11e7-83c9-9c8bcd3f70a6.png)

**Comment by xdima92x** [comment]
Hi @5pointDigital The color picker works properly on IE. Please check [this screenshot](https://www.evernote.com/shard/s554/sh/f09bee00-c213-43d7-87c4-7778a00edd89/e3a477759f95ce5c). Most likely, you have this issue because there is no room for color picker to show the Alpha field. I recommend you to use a more versatile browser, like Chrome or Safari.

**Comment by 5pointDigital** [comment]
"On April 3rd I asked about Templates for pages..."

*crickets*

As to my request for a missing feature, I haven't used IE since the early days of Windows 7, but I confirmed before posting, the feature is missing when using Vivaldi, Edge, Opera, Chrome, Firefox, Safari, and 3 others.

You are correct, the color picker does work properly, but you probably got confused with another person's post. My suggestion had nothing to do with the H1 color picker, in fact not with any color picker.

I even made a point to emphasize what I was referring to by putting it in quotes, "Text Shadow" - that's farther to the right so you have to drag the scroll bar sideways. And I included a screen cap that shows "Text Shadow" - almost impossible to miss that. 

Just to clarify, your screen cap below isn't showing the "Text Shadow" color picker :)

![lc-txt-element-not-txt-shadow-color-picker](https://user-images.githubusercontent.com/28401201/28212524-aa35e20e-6856-11e7-9970-d84f1f32efdc.png)

Regardless, I appreciate you taking time to comment on this feature request, but I've moved on. I wish you the best with this project.
