### ISSUE TITLE
JavaScript error detected in a third-party plugin

### ISSUE THREAD

**Issue by Gewayne** [live-composer/live-composer-page-builder#702]
Hi 
Im getting this error on all my pages and live composer is the only plugin i have installed on the site.

JavaScript error detected in a third-party plugin
TypeError: t[r].getAttribute(...) is null
File "http://carssa.siterubix.com/hashcash.js", line 64, char 77

Please help

**Comment by xdima92x** [comment]
Hi @Gewayne Try to activate a default WP theme or LC Blank for a minute and see if LC works as expected? This way we can tell if there is a problem with your theme.

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
