### ISSUE TITLE
Shape Divider

### ISSUE THREAD

**Issue by Deanphillips** [live-composer/live-composer-page-builder#703]
Hey guys!

I recently used a builder which allowed shape dividers (https://elementor.com/wp-content/uploads/2017/03/shape-divider-900.png) 

Is this a possible feature than LC could have soon?! 

Thank you

**Comment by arthur-and-ashes** [comment]
#RequestFeature Hi guys, I am going to use Live Composer for all websites of my company. The shape divider option should be a great design improvement.
- Giving some base shape dividers
- The possibility to add a shape divider 

Let us know, we could help providing the basic shapes (SVG)

**Comment by FoldingTheme** [comment]
https://github.com/lumbermandesigns/lc-extensions/issues/64
