### ISSUE TITLE
Contact form 7 shortcode makes live composer not working

### ISSUE THREAD

**Issue by persulla** [live-composer/live-composer-page-builder#704]
Hello,
Every time I insert a shortcode for Contact Form 7, the live composer stops working, I mean I cannot edit any module on the page.
I tried to duplicate the page, but the problem persists.

Is there a way to solve this issue? I really need to use contact form 7 shortcodes.

My website is www.yogaecannella.it (but there is a redirect at the moment - if you need them I will give you the access details)

Thank you
Francesca
![screen shot 2017-05-06 at 00 50 12](https://cloud.githubusercontent.com/assets/5067806/25766936/e7f2cfb8-31f5-11e7-8960-f985b5d1ae9f.png)

**Comment by xdima92x** [comment]
Hi @persulla It works. I recorded a short video - https://drive.google.com/file/d/0B7nJlmCX4yHuOEFFZS1rOVRDcTg/view

1) Try do deactivate all the other plugins for a minute and see if LC and Contact form 7 works as expected?
2) Try to activate a default WP theme or LC Blank for a minute and see if LC works as expected?

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
