### ISSUE TITLE
"Load more items" translate issue

### ISSUE THREAD

**Issue by jaimitoperezg** [live-composer/live-composer-page-builder#705]
Guys, you got an error in your translate file around the 341 line, because when I try to translate the "Load more items" phrase into Spanish, it never works.

Please update that line so in new code updates I don´t have to manually fix this error. Thank you.

Here is a code example from the translated file.

#: ../includes/display-functions.php:1544 ../includes/display-functions.php:1546
msgid "LOAD MORE ITEMS"
msgstr ""

#: ../includes/display-functions.php:1634
#: ../includes/display-functions.php:1636
msgid "Load More Items"
msgstr "Cargar más elementos"

**Comment by xdima92x** [comment]
Hi @jaimitoperezg If you need to translate "Load More Items", please use plugins like Loco Translate.

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
