### ISSUE TITLE
Tabs background

### ISSUE THREAD

**Issue by theodorekall** [live-composer/live-composer-page-builder#707]
Hey guys, 

Terrific job on Live Composer... I am just using this now for my wp sites! 

I have a question in regards to the Tabs module. How can I change the background of the tabs to a different colour? 
http://virginiakerr.ie.cpanel4.webhost.ie/repertoire/ <-- this is the design issue I am having. 

Thanks a mill for your help! :) 

Theo

**Comment by 5pointDigital** [comment]
Well a month with no dev activity on this project can't be a good sign. 

Anyways, did you get your Tabs figured out? If you are using the latest version, 1.3, there should be a background color picker. Click anywhere on the TABS ELEMENT > Styling > General > "**BG Color**" should be the first property. Depending on how you have the element styled, you may want to also adjust the NAVIGATION and NAVIGATION ACTIVE options.

Hope that helps.

**Comment by theodorekall** [comment]
Thanks! I had to sort it with a cuss class white bg :)

**Comment by theodorekall** [comment]
Css not cuss :)

**Comment by xdima92x** [comment]
Please update to the latest version of the Live Composer. It works properly.
