### ISSUE TITLE
Module Shortcode Enable/Disable custom css not present

### ISSUE THREAD

**Issue by lejardindeden** [live-composer/live-composer-page-builder#709]
Hello,

Since few days I've seen the live composer css applied where I don't want. I guess after the last update.

After searching, I have realized in the dslc_code the custom_css option doesn't appear anymore for my shortcode. After adding the option in the custom field manually ("custom_css":"disabled") it works again as expected.

Am I the only one to have this problem ?
There is not the option to Enable/Disable the custom css in the shortcode module. Is it maybe possible to pull a request about it for the next update..

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/709
