### ISSUE TITLE
Next page WordPress shortcode functionality

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#710]
The WordPress  shortcode is not working. Was tested on "Text module" and "Content module".

**Comment by xdima92x** [comment]
Hi @FoldingTheme It's a not bug. You using a theme 'LC Blank'. You using a theme 'LC Blank'. LC Blank don't use this function wp_link_pages. If you will change a theme on 'Twenty Fifteen' it will work.
