### ISSUE TITLE
Wrapper image issue on the "Button module"

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#711]
When an image is uploaded to the button wrapper, it exceeds the margin of the wrapper and has no controls for this. It can be fixed with this style:

.dslc-button {
    background-size: 100%;
}

**Comment by xdima92x** [comment]
You can use this option - https://www.evernote.com/shard/s554/sh/64824f27-48e1-4250-9da8-e51b37836aa2/0fc7db157cb7cc9e
