### ISSUE TITLE
Archive template path notice need to be updated

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#716]
When no archive template is set, the page builder notice still use the old template path. [See this screenshot.](https://www.evernote.com/l/AjljIFW99ltOnKfM8qfi9p6qfSLimzLo4Ig)

**Comment by athineos** [comment]
How can I set an archive template while in the settings menu there is no label "Archives and Search" or "Post archives". Do I have a different edition of Live Composer?
![screenshot settings](https://cloud.githubusercontent.com/assets/29171076/26759238/5a3ee85a-4901-11e7-90dd-a3282041b956.JPG)

**Comment by xdima92x** [comment]
Hi @FoldingTheme It's a not bug of LC. You need to update the last [theme 'Blank'.](https://livecomposerplugin.com/downloads/blank-theme/)

Hi @athineos You [need to open this page](https://www.evernote.com/shard/s554/sh/0298c60a-3931-4c61-8a39-f39cb23d2757/19610d6d25671602) and to create your template 'Archives and Search' and 'Post archives'
