### ISSUE TITLE
Remove the ordering criteria which don't belong to the module

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#717]
For instance when is talking about the "comment count" on testimonials. [See this screenshot](https://www.evernote.com/l/Ajn1G0k43iZJdJM68MR3DXlTNILOYfwSijU). It tend to confuse the customers regarding the custom post usability.

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/717
