### ISSUE TITLE
Uncaught TypeError: Cannot read property 'init' of undefined

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#718]
t: 27777

/wp-content/plugins/live-composer-page-builder/js/builder/builder.settings.panel.functions.js?ver=1.3", line 305, char 49"

The error break the LC functionalities on some installations. It is present on older versions of LC too (1.2.5 to 1.3.1).

**Comment by xdima92x** [comment]
How to fix this bug:

Sometimes is caused by the visual editor disabled, malfunctions on WordPress, etc. 
You need to overwrite the WordPress files over FTP.
