### ISSUE TITLE
Excerpts need formatting options

### ISSUE THREAD

**Issue by MasterPayne** [live-composer/live-composer-page-builder#721]
dslc-blog-post-excerpt

BLOG module (blog element) needs selectors to remain in place.

For years now it renders as plain text inside a DIV - no p, no h1, h2, h3, nothing. Native WP renders selectors fine, why does LC strip this stuff out?

Also needs text-align for each selector like the other modules.

Thanks.

**Comment by xnubian** [comment]
Yes, this is definitely needed!

**Comment by xdima92x** [comment]
If you want to use an excerpt and HTML tags, please put max length to zero
