### ISSUE TITLE
IMAGES module

### ISSUE THREAD

**Issue by lumberman** [live-composer/live-composer-page-builder#722]
Show "No image has been set yet, edit the module to set one." message to site admins only!

**Comment by MasterPayne** [comment]
Thanks for that Vlad. Makes good sense.

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/722

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/722
