### ISSUE TITLE
Uncaught Error: Could not find control by type: wplinkpreview 

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#727]
Lately, a few similar cases on different installation:

JavaScript error detected in a third-party plugin 
Uncaught Error: Could not find control by type: wplinkpreview 
File "http://.../wp-includes/js/tinymce/tinymce.min.js?ver=4603-20170530", line 10, char 22486 

One customer solved this downgrading the WP to 4.7.5

**Comment by xdima92x** [comment]
Such error appear when the editing is forced before browser finish to load all the website resources. The page it should be reloaded and check the loading bar from browser address bar to show the page is loaded
