### ISSUE TITLE
How can I use feature 'tutorial' livecomposer

### ISSUE THREAD

**Issue by buihoang91tin** [live-composer/live-composer-page-builder#732]
Hey guys. I'm exploring livecomposer lastest version. I'd read document about feature tutorial for developers. And I enable this feature in my function.php file in my theme like this article : https://livecomposer.help/…/182-activating-tutorials-in-you….
But I dont see anything and I dont know how to use this feature for guest in my website. So how can I use this feature. Please help me. Looking help from all. Thank you so much..

**Comment by xdima92x** [comment]
Hi @buihoang91tin https://livecomposer.help/article/182-activating-tutorials-in-your-theme - the link is broken. What do you mean enable this feature in my function.php because I don't know about this article? How I know Live Composer have turned off tutorials in the plugin.

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
