### ISSUE TITLE
Making a number of changes quickly can cause the builder to freeze

### ISSUE THREAD

**Issue by senning** [live-composer/live-composer-page-builder#733]
After confirming changes, if you quickly start to edit another component it can cause the builder to freeze. The freeze seems to be caused by the builder making an invalid request to `admin-ajax.php` which never gets a response; the request looks like this:
```
action	"dslc-ajax-add-module"
dslc	"active"
dslc_post_id	"1770"
dslc_preload_preset	"disabled"
dslc_url_vars[page]	"livecomposer_editor"
dslc_url_vars[page_id]	"1770"
```

I think the root cause is that when changes are confirmed, all of the components on the page with the same type get replaced. So if you click to edit a component while it is refreshing, the editing pane loses the component to provide it data. Worse, sometimes the freeze prevents the page from being published or saved as a draft.

I think there are a few ways to fix this, though I don't know where the fixes should be made nor which works the best with other features.

1. Don't refresh other elements of the same type
2. While a component's is updating, disable all edit buttons until every component has been refreshed
3. Set a timeout for AJAX requests, triggering an error or complete callback at the timeout instead of freezing.

**Comment by FoldingTheme** [comment]
tested this on the last plugin version. so such an issue.
