### ISSUE TITLE
500 error on Servers where response body limit is not specified

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#738]
Error: ModSecurity: Output filter: Response body too large (over the limit of 524288, total not specified).

This won't let the LC to be activated. Usually, this is happening on rich content pages (home pages for instance).

https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecResponseBodyLimit

**Comment by xdima92x** [comment]
Take a look at the documentation here https://github.com/SpiderLabs/ModSecurity/wiki/Reference-Manual#SecResponseBodyLimit By default this limit is configured to 512 KB, anything over this limit will be rejected with status code 500 (Internal Server Error). You’ll need to ask your hosting provider to increase the limit to fix the problem.

This should resolve the issue, in case if this doesn’t help, try disabling Mod Security.

Also you can use this article - http://www.viknea.com/2017/03/fix-modsecurity-output-filter-response-body-too-large-over-limit-of-524288-total-not-specified/
