### ISSUE TITLE
in IE11, "Load More" button dissapear issue

### ISSUE THREAD

**Issue by au790000** [live-composer/live-composer-page-builder#741]
POSTS, BLOG module problems in IE 11.
I set PAGINATION to LOAD MORE. 
On the first page, it is properly expressed, and the LOAD MORE button disappears on the second page.

Checked on multiple computers.
Operates normally on EDGE, CHROME.
Not a plug-in conflict, I guess.

Desperately seeking help. 
https://goo.gl/GYqaaa

**Comment by xdima92x** [comment]
Hi @au790000 Please update LC to the last version.

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
