### ISSUE TITLE
woocommerce problem

### ISSUE THREAD

**Issue by rodsbermudez** [live-composer/live-composer-page-builder#745]
after update de cart for woocommerce (using live composer add-on) is generating errors

1. Doesn´t add to cart
2. doesn´t remove itens from cart
3. the green bar for success add on cart doesn´t show

i had to revert do 3.1 to make it work again

**Comment by lumberman** [comment]
Hello, thanks for reporting this.
Please disable LC cache in **WP admin > Live Composer > Settings > Performance > Caching**.
We will make it work with cache soon.
