### ISSUE TITLE
New HTML/CSS cache is not working with Multilanguage plugin by BestWebSoft

### ISSUE THREAD

**Issue by AlainMelsens** [live-composer/live-composer-page-builder#746]
Dear,
The new HTML/CSS caching (object-based cache) is not working with the free Multilanguage plugin by BestWebSoft.
When the cache is enabled, the chosen language doesn't work anymore. No pages in other languages are loading anylonger and also the language navigation bar in the header (designed with Live Composer) is no longer working. The standard homepage is staying in place of other pages.
After disabling the cache, it's working as normal. Maybe the cache is not builded to working with such translate plugins with special navigation widgets?
Thanks in advance to look at it in the near future because this new caching posibility can be important.
Kind Regards,

**Comment by lumberman** [comment]
Thanks for reporting it.
Cache will not touch shortcodes other content get saved as HTML/CSS in the database. I will check the plugin mentioned to see what can be done. Until then, please disable cache on your end.

**Comment by FoldingTheme** [comment]
@AlainMelsens could you let us know if the issue is solved with the last LC version? Thanks.

**Comment by AlainMelsens** [comment]
Hello,
Sorry, but I don't use LC anylonger.
For me this ticket may be closed.
Thanks anyway.
