### ISSUE TITLE
Responsive Padding Values Lost

### ISSUE THREAD

**Issue by theprofessor101** [live-composer/live-composer-page-builder#747]
Within the Text Module under Responsive > Phone, the 'Padding Vertical' and 'Padding Horizontal' values are null (no value shown) by default - instead of a zero value. 

When the value is set to '0', the value remains when saved. When changes are made to the module (this can be any change: font size, padding, etc.) at a later time, the 'Padding Vertical' and 'Padding Horizontal' values have returned to null.

As a result, when viewing this module on a phone, the horizontal and vertical padding is assuming the values assigned in the Styling tab.

**Comment by lumberman** [comment]
@xdima92x please check and find what changes caused it?

**Comment by FoldingTheme** [comment]
The null value or zero is the default padding value. It means no padding will be applied. Any other positive value will be saved properly.
