### ISSUE TITLE
Can no longer edit text within module

### ISSUE THREAD

**Issue by theprofessor101** [live-composer/live-composer-page-builder#748]
The latest update v1.3.2.1 removed the functionality to edit text directly in the module when using Firefox v48 in private browsing mode.

The only way to edit text is to first select "Open in WP Editor".

**Comment by lumberman** [comment]
Hello,
Direct text editing disabled for time being. This feature was causing too much issues and we need time to figure out how to make it work as expected.

**Comment by lukeperrie** [comment]
@lumberman must second this and let you guys know that this is very discouraging. This feature was a huge step forward for the plugin and we have many clients who are now asking why it's not working any more. We never had any issues with it besides the fact that it would lose styling if you selected all the text and tried to type in. What were the major issues?

**Comment by FoldingTheme** [comment]
the feature remain disabled for the moment. meanwhile no other customer request it.
