### ISSUE TITLE
Active Item in Menu not highlighted properly in latest update.

### ISSUE THREAD

**Issue by menachemshapiro** [live-composer/live-composer-page-builder#750]
I brought this up over here: https://www.facebook.com/groups/livecomposer/permalink/1915545185138925/

I just upgraded to the latest version of LC, and noticed an issue with my menu bar. The menu is not correctly displaying the active item. Instead, the first active item is the one that stays active no matter which  item I click.  (it is possible that this issue was around before and I only noticed it now). 

You can see the menu here: https://bananabeachcr.com/ . When I click on the different menu items and go to the page, the active menu item is not the correct menu item. (on my page the active tab changes to blue).

The website in this facebook question also has the same problem.: https://www.facebook.com/groups/livecomposer/permalink/1913971441962966/

It is possible that this bug is connected to the new caching system.

Let me know if you need more information from me.

**Comment by menachemshapiro** [comment]
I disabled LC caching, and the problem went away, so it does seem to be connected to the caching.

**Comment by lumberman** [comment]
Fixed as part of #754
