### ISSUE TITLE
Breaking changes from 1.3.1 to 1.3.2.1

### ISSUE THREAD

**Issue by brizov43** [live-composer/live-composer-page-builder#752]
Running on Ubuntu 16.04 with nginx and php7.0-fpm

After updating the blog element in combination with the "Load more" pagination is broken. The link does not work, and keeps loading the same set of posts over and over again.

A lot of the css styling in different components is broken. When setting values with the sliders they are not applied correctly or not at all.

**Comment by lumberman** [comment]
Thanks for reporting.
See fix in issue #753. In new version it should work as expected (to be released in the end of this week). 

Until then you can disable Live Composer caching in WP ADMIN > Live Composer > Settings > Performance > Caching
