### ISSUE TITLE
Bug: Testimonials / Original report: #744

### ISSUE THREAD

**Issue by Psinergy** [live-composer/live-composer-page-builder#758]
This bug is STILL happening in 1.3.3 --- someone closed the original bug report on this, so creating a new ticket.

I've also tried this as suggested by support:

Open your website for editing in a private/incognito mode. Let me know if it's any different. - Yes, had already tried that. It gives the same issue.
Try to deactivate all the other plugins for a minute and see if LC works as expected? This way we can tell if any other plugins cause the issue. - Yes, had already tried that, and tried it again after updating just now to WP 4.8.1, still same issue.
Try to activate a default WP theme for a minute and see if LC works as expected? This way we can tell if there is a problem with your theme. - Just tried Twenty Seventeen and still same issue.

Module is **Testimonials**.

Basically, if you go to one of the testimonials, like https://test.psinergytech.com/testimonial/hannah-linsk-1222017/ (one of the Testimonials that we have in the Testimonials thing), it 404's.

**Comment by Psinergy** [comment]
PS --- other modules, like Staff and Partners DO work just like they should.

Staff: https://test.psinergytech.com/about-us/our-team/

Partners: https://test.psinergytech.com/recommended-businesses/

**Comment by lumberman** [comment]
Thanks for helping with this.
Can you please go to WP Admin > Live Composer > Settings > Performance and disable caching. Let me know if this clears the issue?

**Comment by Psinergy** [comment]
Yes, tried the disable cache, didn't fix it :( Forgot to mention that,
sorry.


Make it a GREAT Day,
SchaOn Blodgett, CCP, BTAT
Holistic Health Professional


*Psinergy Natural Health & Holistic Wellness | Helping you access your
Awesomeness... Naturally.*
*...a branch of Psinergy LLC*
1553 Como Ave
St Paul, Minnesota 55108
Office: (612) 217-4325
Fax: (612) 217-4325
schaon@psinergyhealth.com
https://www.psinergyhealth.com

This e-mail, including any attachments, is intended solely for the person
or entity to which it is addressed and may contain confidential,
proprietary and/or non-public material.  Except as stated above, any
review, re-transmission dissemination or other use of, or taking of any
action in reliance upon this information by persons or entities other than
an intended recipient is prohibited.  If you receive this in error, please
notify the sender and delete the material from any media and destroy any
printouts or copies. Additionally, this e-mail does not create a
practitioner-client relationship unless a Client Bill of Rights, as
mandated by MN State Law Statute 146A, has been signed by both the client
and responsible practitioner.

--------------------
‎"A man too busy to take care of his health is like a mechanic too busy to
take care of his tools."
Spanish Proverb

**Comment by xdima92x** [comment]
Hi @Psinergy 

1) The module **Testimonials** don't have a button **Continue Reading**. You using the [module Post.](https://www.evernote.com/shard/s554/sh/ab8f438b-beac-4860-b912-1aacd43f96ab/dca58f3c7c7e6502) The module Post have a button **Continue Reading**
2) I recorded [a short video](https://drive.google.com/file/d/0B7nJlmCX4yHuN2dPN3lsUy1CU2s/view) for you. The module Post works.
3) Do you have a template for the type of post?
4) Do you have a plugin of redirection or code on your website?
:)

**Comment by lumberman** [comment]
Dima is right,
Your are using POSTS module to display testimonials: https://cl.ly/0Z1I3Y1T3t3v
Please use TESTIMONIALS module instead. By design Testimonials in LC DOESN'T have a single testimonial page. It supposed that you will show block of testimonials like this: https://cl.ly/393M1f010f3O If you need a separate page with all testimonial, just create a new regular page and place a grid with all testimonials on it. Use TESTIMONIALS module to display all the testimonials you have.

I hope my comment will be useful.
Have a great day.

**Comment by lumberman** [comment]
You can comment and reopen this ticket if needed.
