### ISSUE TITLE
Live Composer not responding

### ISSUE THREAD

**Issue by EarthS2000** [live-composer/live-composer-page-builder#759]
Live Composer plugin with West Theme (by aThemes) on Wordpress. 

LC stopped working - the LC editing dash/page opens, however it is entirely unresponsive. 

Deactivated all other plugins, cleared LC and Wordpress and browser caches - LC still not responsive. Wordpress & all plugins are updated.

Would greatly appreciate any advice etc.

Thanks!

**Comment by lumberman** [comment]
Please open your JavaScript console and copy here the errors you see there. 

https://webmasters.stackexchange.com/questions/8525/how-do-i-open-the-javascript-console-in-different-browsers

Thank you.

**Comment by EarthS2000** [comment]
Sorry not a programmer etc. 

No errors come up inside the Wordpress Dashboard interface. When a page is opened in Live Composer, it loads, however from that point on, all LC interfaces are entirely unresponsive. 

Thanks for your help!

**Comment by jgajera** [comment]
Does it work if you deactivate Jetpack while working on LC pages? Looks
like the JS error is a conflict with Jetpack.

On Mon, Aug 14, 2017 at 12:08 PM, Petar Stojkovikj <notifications@github.com

**Comment by queermk** [comment]
Yes. Deactivating Jetpack solved the issue. I was finally able to edit text modules in the WP Editor.

Thank you.

**Comment by jgajera** [comment]
No worries! It happened to me too, so I still think this is an issue
because Jetpack is a very popular plugin for LC to being conflicting with.
:(

**Comment by EarthS2000** [comment]
Unfortunately, I've still got unresponsive LC :/

Just confirming, all of my plugins, Wordpress version, West Theme are updated as of today.

I've deactivated all other plugins and deleted JetPack

Emptied the caches in both LC, Wordpress and my browser.

:(

**Comment by kaueparmais** [comment]
Having the same issue with SEO WP Theme:

```
Live Composer returned JS error
Uncaught TypeError: Cannot read property 'init' of undefined
File "https://www.mysite.com/wp-content/plugins/live-composer-page-builder/js/builder/builder.settings.panel.functions.js?ver=1.3.4", line 6, char 47
```

**Comment by EarthS2000** [comment]
Just a quick update - I've changed my theme and page builder as I've been pressed for time. 

Thanks for all your help anyway - these issues can get super buggy, but it's all good.

Cheers

**Comment by atlasrise** [comment]
Live Composer returned JS error was this ever resolved
