### ISSUE TITLE
Issue with navigation module subnav styling settings

### ISSUE THREAD

**Issue by BobaWebDev** [live-composer/live-composer-page-builder#760]
In https://github.com/live-composer/live-composer-page-builder/commit/0269c4012c7f394fb1c4a1c915c474b7b9988bb9 the system was changed to apply subnav CSS rules to **ul:before** instead of **ul**

Because of that some of the options no longer work ( for example the padding options ).

**Comment by lumberman** [comment]
Will test and fix it by weekend.

**Comment by BobaWebDev** [comment]
Thanks.

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/760
