### ISSUE TITLE
URGENT: Header/Footer Editing Broken

### ISSUE THREAD

**Issue by theprofessor101** [live-composer/live-composer-page-builder#762]
In the latest 1.3.3 release, you can no longer edit the header/footer separately and have those changes applied to all pages.

Currently, the header/footer appears inline with the current page layout. 

Furthermore, when you duplicate a container in the header/footer, the duplicated container gets moved to the page area and does not remain in the header/footer area.

**Comment by lumberman** [comment]
Can you please disable caching in **WP Admin > Live Composer > Settings > Performance** and let me know if it solves your problem?

**Comment by theprofessor101** [comment]
Unfortunately, no. Disabling caching does not solve the problem.

**Comment by lumberman** [comment]
Ok we will debug it and fix (hopefully tomorrow).
You can download previous version here: https://wordpress.org/plugins/live-composer-page-builder/advanced/ (scroll page down to select the version).

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/762

**Comment by theprofessor101** [comment]
I updated to 1.3.4 but this issue is not fixed. Instead of the overlay with the word "Footer" to edit, I can still edit the header/footer inline.

Here is a screenshot of what I get when I hover the mouse over the footer. 

![footer](https://user-images.githubusercontent.com/30474543/29279984-2c598aba-80df-11e7-8060-03871c073cad.png)
