### ISSUE TITLE
The post sticky option is not working when a category is selected

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#765]
https://www.evernote.com/l/AjlC6saTBj1GlKAWpYECnZUHRtGupo9Az6U

**Comment by xdima92x** [comment]
https://wordpress.stackexchange.com/questions/98187/how-can-i-display-sticky-posts-at-first-in-wp-query

**Comment by xdima92x** [comment]
@FoldingTheme Please check this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/765 It's a beta version
