### ISSUE TITLE
Issue #762 Not Fixed | Header/Footer Editing Broken

### ISSUE THREAD

**Issue by theprofessor101** [live-composer/live-composer-page-builder#766]
Issue #762 was addressed and closed, but not fixed. The problem continues with v1.3.4.

To recap: when editing a page, the header/footer continue to be editable in-line instead of being a separate section to edit. Any edits made do not apply to the header/footer of the other pages as they should.

Furthermore, when editing the header/footer under **Appearance** > **Header/Footer**, making any edits to the existing header/footer, or adding new content, the follow error is received:

![screen shot 2017-08-15 at 7 56 48 am](https://user-images.githubusercontent.com/30474543/29316904-502f057c-818f-11e7-8651-964ebb4714c1.png)

**Comment by xdima92x** [comment]
Hi @theprofessor101 It works. I recorded [a short video](https://drive.google.com/file/d/0B7nJlmCX4yHuMngwaXVlS0h1NW8/view) for you. Do you have a cache? Try do deactivate all the other plugins for a minute and see if LC works as expected? Try to activate a default WP theme for a minute and see if LC works as expected?

**Comment by lumberman** [comment]
@theprofessor101 if you can please create a temporary admin user for your website and send us login details to livecomposerplugin (a) gmail.com Our developer will try to debug it for you.

Thank you.

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
