### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getNode' of undefined

### ISSUE THREAD

**Issue by srcorti** [live-composer/live-composer-page-builder#767]
Updated the plugin to the latest release 1.3.4
Was editing a page in Live Composer when suddenly I can't edit a text in WP Editor

It detects the following error:
> ```
> JavaScript error detected in a third-party plugin
> Uncaught TypeError: Cannot read property 'getNode' of undefined
> File "http://ggforyou.com/wp-includes/js/tinymce/plugins/wpview/plugin.min.js?wp-mce-4603-20170530", line 1, char 956
> ```

Wordpress version 4.8.1

**Comment by jgajera** [comment]
It looks like you have a Javascript conflict with your WPView plugin. Does deactivating that plugin help you edit the Text Modules? If so, then you may want to turn off that plugin whenever you're editing pages.

**Comment by xdima92x** [comment]
Such error appear when the editing is forced before browser finish to load all the website resources. The page it should be reloaded and check the loading bar from browser address bar to show the page is loaded

**Comment by atlasrise** [comment]
Live Composer returned JS error
Uncaught TypeError: Cannot read property 'init' of undefined
File "http://eliteproductbuilders.com/wp-content/plugins/live-composer-page-builder/js/builder/builder.settings.panel.functions.js?ver=1.3.9&nocache=1", line 220, char 50

**Comment by atlasrise** [comment]
Can you please help me I am also receiving this error on the website i am making 

www.eliteproductbuilders.com

**Comment by lumberman** [comment]
Please contact SEOWP theme support for solution: https://themeforest.net/item/seo-wp-online-marketing-seo-social-media-agency/8012838/support/contact

You paid for premium support buying this theme.
