### ISSUE TITLE
Cannot "Open in WP Editor"

### ISSUE THREAD

**Issue by NickNiebling** [live-composer/live-composer-page-builder#768]
LC - v 1.3.4
WP - v4.8.1

Clicking on "Open in WP Editor" doesn't work (nothing happens when clicking)

**Comment by jgajera** [comment]
@NickNiebling does the below thread help?
https://github.com/live-composer/live-composer-page-builder/issues/759

Also, are you seeing any red bug errors or Javascript Console errors? It is possibly a plugin conflict causing the issue where you can't edit the text in your text modules.

**Comment by Tommyfoxy2** [comment]
Been getting the same issue as well.

`Uncaught TypeError: Cannot read property 'getNode' of undefined
File "http://discord.directory/wp-includes/js/tinymce/wp-tinymce.php?c=1&ver=4603-20170530", line 61, char 956`

**Comment by LazzaWA** [comment]
I can second the fact that uninstalling Jetpack fixed my issue with not being able to use the WP editor option. Would be nice to have that compatible again though :) jetpack version 5.2.1 - LC version 1.3.4
