### ISSUE TITLE
Unable to move more than one module

### ISSUE THREAD

**Issue by mrplow057** [live-composer/live-composer-page-builder#769]
I'm trying to format my page that contains a lot of text and shortcode modules, but when I'm trying to move these modules, it only allows me to move one before hiding the bar that allows you to move the modules.  The only way I can move another module is if I refresh the page.  Is there a work around for this?

**Comment by xdima92x** [comment]
Hi @mrplow057 I'm sorry but I cannot understand your problem.Could you create a screencast about your problem?

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
