### ISSUE TITLE
PHP Warning: Invalid argument supplied for foreach() ... css-generation.php

### ISSUE THREAD

**Issue by klarsendesign** [live-composer/live-composer-page-builder#771]
I'm getting tons of errors repedetively on every page:
 PHP Warning: Invalid argument supplied for foreach() ... /plugins/live-composer-page-builder/includes/css-generation.php on line 210

**Comment by xdima92x** [comment]
Hi @klarsendesign if you can please create a temporary admin user for your website and send us login details to [contact support team](https://livecomposerplugin.com/support/support-request/) Our developer will try to debug it for you.

Thank you.
