### ISSUE TITLE
Uncaught TypeError: Cannot read property 'init' of undefined 

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#772]
Live Composer returned JS error 
Uncaught TypeError: Cannot read property 'init' of undefined 
File "http://.../wp-content/plugins/live-composer-page-builder/js/builder.all.min.js", line 3, char 2473

**Comment by xdima92x** [comment]
When we will have a new release I again will do minimization the file 'builder.all.js' ( grunt )
