### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getNode' of undefined 

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#773]
JavaScript error detected in a third-party plugin 
Uncaught TypeError: Cannot read property 'getNode' of undefined 
File ".../wp-includes/js/tinymce/wp-tinymce.php?c=1&ver=4603-20170530", line 61, char 956 

t 28862

**Comment by xdima92x** [comment]
Such error appear when the editing is forced before browser finish to load all the website resources. The page it should be reloaded and check the loading bar from browser address bar to show the page is loaded
