### ISSUE TITLE
Templates losing bindings.

### ISSUE THREAD

**Issue by juslintek** [live-composer/live-composer-page-builder#774]
Templates for Archive Index Templates and Special Page Templates lose their bindings after pages are altered or new ones added as well when templates are updated.

**Comment by xdima92x** [comment]
Hi @juslintek 

I tested it on my server. I don't have this bug.

1) Try do deactivate all the other plugins for a minute and see if LC works as expected?
2) Try to activate a default WP theme for a minute and see if LC works as expected?
3) Not working anyway? > Please contact [support team.](https://livecomposerplugin.com/support/support-request/)

**Comment by juslintek** [comment]
@xdima92x, try changing lets post-type slug or taxonomy slug and then save permalinks, and check out again archive and see if it still has template mapped.

**Comment by xdima92x** [comment]
Please update LC 1.3.6

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
