### ISSUE TITLE
Custom post type and taxonomy template with custom permalink mess up

### ISSUE THREAD

**Issue by lejardindeden** [live-composer/live-composer-page-builder#778]
Hi,

I am trying to create template for my taxonomy. I don't know really if this is possible, but my problem is that my CPT and CT share the same slug because I want to have a permalink as following : 
`mywebsite.com/{custom-post-type}/{taxonomy-parent}/{taxonomy-child}/{post}`

I have created templates for my CPT with the filter `dslc_post_templates_post_types`, one for my archive CPT, another one for my single CPT.

The problem is when accessing my taxonomy, I get my archive CPT template.

Before using Live Composer, I managed to separate my archive CPT and my taxonomy template using the filter `parse_query` and so avoiding to mixed my CPT and CT template. [Check this here](https://wordpress.stackexchange.com/questions/277718/custom-taxonomy-template-not-display/278029#278029)

Using LC template, I came back with the same problem.

So first of all, can I create a taxonomy template ? Secondly, if yes, Is there a way to separate my archive CPT template from my taxonomy ?

Thank you for your help.

EDIT : 
I have problem between my two CPT template, archive and single. When I expect the single template, I get the archive template but when want to edit the template, I get the single template. I have this problem until I update the template. But I get the opposite problem, instead getting my archive template I get my single template until I update again... 
And on top of this mess, sometimes, my single template stay on certain post but not all of them after updating my archive template.

**Comment by xdima92x** [comment]
In WordPress, the slug is the same with permalinks. The WordPress will register a permalink for a single /page/post/ctp etc. If you have more questions about this, please write here.

**Comment by lejardindeden** [comment]
Hi Dima,

The issue was not enough clear apparently.

When I said: my CPT and my CT share the same slug, it is not the original
problem but just to put you in context.
I register my CPT and CT as you can see in
"register_custom_post_type_taxonomy.php".

The main problem is that my LC templates, one for my CPT archive and the
other one for the CPT post, messed up.

Example: When my archive template (ID:191) is updated, I can see the
template correctly accessing the archive page but also the CPT post, and
this should not happen. And it is the same when I update my post template
(ID:192), my archive page get the post template suddenly. (see attached
document).

So I do not know if it mess up because of my URL structure or something
else.

I hope to be clear for you, if you need more information, do not hesitate
to contact me.

Thank you so much for helping me.
Julien.

Julien Ruckebusch

2017-08-29 10:17 GMT+02:00 Dima <notifications@github.com>:

**Comment by xdima92x** [comment]
Please update to the latest version of Live Composer. If need assistance, please open a support ticket on: https://livecomposerplugin.com/support/support-request/
