### ISSUE TITLE
JetPack compatibility

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#779]
The LC get in conflict with multiple JetPack add-ons (Contact Form for instance). Being a popular plugin, get in trouble with the installations of many clients.

**Comment by xdima92x** [comment]
Hi @FoldingTheme It's a no problem in the Live Composer. You can read this article: https://wordpress.org/support/topic/5-2-breaks-text-and-tinymce-widgets/

I see a two way:
1) For anyone having this problem, please add the code below to your theme functions.php file (or even better create a new plugin and paste the code there), it will disable the JetPack “Contact Form” button in TinyMCE on the whole site. This, of course, should be used only as a temporary solution until JetPack developers will fix it properly. 
**Code** - http://snippi.com/s/sk9wrdg
2) You can back to Jetpack 5.1 and everything works again. You can download old version here - https://github.com/Automattic/jetpack/releases
