### ISSUE TITLE
Social Element/Module Icon Addition

### ISSUE THREAD

**Issue by jgajera** [live-composer/live-composer-page-builder#780]
Email please!

**Comment by xdima92x** [comment]
Hi @jgajera https://github.com/live-composer/live-composer-page-builder/tree/issue/780 - is it? :)

**Comment by jgajera** [comment]
Hey Dima, I added two pull requests for the solution yesterday, but I saw you made the change independently. I added a comment because I think you missed a small thing!

**Comment by xdima92x** [comment]
Hi) I fixed
