### ISSUE TITLE
Header and Footers can be accessed directly (not on a page but as a standalone website)

### ISSUE THREAD

**Issue by klickagent** [live-composer/live-composer-page-builder#799]
I do have the problem that when I search on google the following header can be found and accessed as a standalone webpage. This would in fact be the header used on some other websites:
https://prognolite.com/site/dslc_hf/header-de-3-2/

You may google for dslc_hf/header to find further websites using live composer page builder with the same issue. Is there a solution for that issue?

Thanks for your help!

**Comment by lumberman** [comment]
Fixed in the next plugin update. Thanks for help.

**Comment by klickagent** [comment]
Thanks a lot. Looking forward to test it soon.
