### ISSUE TITLE
Website title shown as url

### ISSUE THREAD

**Issue by 101010f** [live-composer/live-composer-page-builder#807]
The website title set in the general section of wp doesn't show in the browser tab. Only the website address is displayed. Any way around this?

**Comment by 101010f** [comment]
This works https://make.wordpress.org/themes/2015/08/25/title-tag-support-now-required/ 
Might want to add it to your blank theme.

**Comment by xdima92x** [comment]
Hi @101010f Thanks) I moved feature request here: https://github.com/live-composer/lc-blank/issues/12
