### ISSUE TITLE
Row - possibility to duplicate row below

### ISSUE THREAD

**Issue by ArekZw** [live-composer/live-composer-page-builder#810]
On pages with lots of content when we add a new row, it added at the bottom. Sometimes user want to add new row below existed row. Now new row is added at the bottom, so it requires dragging by all page. With my proposal user can choose where new row will be add.

My proposal:
Click on duplicate icon -> old action (add at the bottom)
Hover on duplicate icon -> show two actions (look img)

Click "Duplicate at the end" -> same action as clicking duplicate icon
Click "Duplicate below" -> add duplicated row under current

![image](https://user-images.githubusercontent.com/11788346/30886405-1d17d12e-a317-11e7-9b5c-20cb7d13e2eb.png)

**Comment by xdima92x** [comment]
Good point. I will open this ticket when we will work with row in LC. At this moment, we have other improvements and issues with LC
