### ISSUE TITLE
Row - possibility to create new row between other rows

### ISSUE THREAD

**Issue by ArekZw** [live-composer/live-composer-page-builder#811]
Currently only at the bottom page user can create row. If he want create in other place, he must create at the bottom and dragging to selected place. It's tiring on long pages.

My proposal: 
Add button to create row below every row settings bar (look img)

![image](https://user-images.githubusercontent.com/11788346/30887077-1a8bf040-a31a-11e7-923c-7011cab818d5.png)

**Comment by xdima92x** [comment]
Good point. I will open this ticket when we will work with row in LC. At this moment, we have other improvements and issues with LC
