### ISSUE TITLE
Lazy loading Feature

### ISSUE THREAD

**Issue by juslintek** [live-composer/live-composer-page-builder#812]
Just asking if anyone is going to integrate proper lazy load, which involved all the contents in viewport and loading transitions styling.

**Comment by lumberman** [comment]
Are we talking about loading images / modules / sections / single posts in the posts grid or pagination rendered with Live Composer?

**Comment by juslintek** [comment]
Yes about everything, so you could lets say render content in rows item by item if its in the viewport. So like infinite scrolling would exist. I've been doing this a lot in custom projects, because people just like to scroll and read. You save meta of positions and whats been read already and sote old data in localStorage and load new one. So no refresh required and very smooth. You remove old data from viewport to free up ram and then load it back from localStorage when its in viewport again.

**Comment by FoldingTheme** [comment]
#951
