### ISSUE TITLE
Issue with containers in 1.3.6

### ISSUE THREAD

**Issue by thejoepeach** [live-composer/live-composer-page-builder#813]
Hi there, i was using Live Composer while ago and now, i use the containers to keep ordenated some items in the interface, however in version 1.3.6, even if they are empty, they took default space in mobile, leaving me with huge empty spaces and no content... i add some pictures to make clear what i mean...

![header_alone](https://user-images.githubusercontent.com/4389790/31002287-5c3230ea-a4af-11e7-99c3-bd6111452531.jpg)
![header_empty](https://user-images.githubusercontent.com/4389790/31002288-5c6a06a0-a4af-11e7-9fd9-990e0a19db93.jpg)

I wondering if i can downgrade to previous version of plugin so this issue can be fixed... or at least leave it as it was in previous versions

**Comment by xdima92x** [comment]
Hi @thejoepeach Could you send a name your website? I need to check your website.

**Comment by thejoepeach** [comment]
Hi there, I default to 1.3.1 because of this crippling issue and all get
fixed... maybe I’ll try 1.3.7 again in my test site and share results here
with you
-- 


http://freefallmotion.com/
freefallmotion Motion Graphics

**Comment by xdima92x** [comment]
Hi @thejoepeach Ok, Thanks!

**Comment by emingus** [comment]
Having similar issues...was using 1.3.1 forever and finally decided to upgrade because of issues...what can be done? Mobile is spaced too much as indicated by red line - radicalchristianwoman.com

![red](https://user-images.githubusercontent.com/31526173/48798547-7842e900-ecca-11e8-8b87-fb6b55d93f6c.jpg)
