### ISSUE TITLE
No feeds for LC custom posts

### ISSUE THREAD

**Issue by xdima92x** [live-composer/live-composer-page-builder#814]
The LC custom posts lead to 404 page error. Mean, doesn't exist. That lead to multiple 404 dead links in Google Webmaster and other SEO reports.

**Comment by lumberman** [comment]
@xdima92x don't search on how to make feeds works, find a way to disable broken feed link in the HTML code instead.

Feeds support isn't a critical feature for us now, it's important to make sure we are creating no broken links.

**Comment by xdima92x** [comment]
Hi @lumberman Thanks)

**Comment by FoldingTheme** [comment]
The CPT Feeds works properly. Most likely the custom post feeds were called wrongly. The correct path: 
http://www.mysite.com/feed/?post_type=projects

https://core.trac.wordpress.org/ticket/12943
