### ISSUE TITLE
Yoast compatibility for the canonical URL

### ISSUE THREAD

**Issue by xdima92x** [live-composer/live-composer-page-builder#815]
Yoast is not adding the rel=next/prev or the paginated canonical tags to pages of blog. 

Here is the Yoast article for integration: https://kb.yoast.com/kb/is-the-plugin-compatible-with-paginated-content/

**Comment by FoldingTheme** [comment]
@xdima92x tx, but your screencast shows that you are using a page with no Live Composer module. Try to use multiple modules and see if there is nothing wrong with multiple lighbox classes.

**Comment by xdima92x** [comment]
@FoldingTheme 

Unfortunately, it's not possible. But a user can use this code - https://wordpress.stackexchange.com/questions/36800/adding-rel-next-rel-prev-for-paginated-archives

Notice: For get_next_posts_link you need to add a max page ( manually )

**Comment by FoldingTheme** [comment]
@xdima92x 

As discussed, for users with no coding knowledge, write here a fully working function for let's say, 5 pagination content. tx.

**Comment by xdima92x** [comment]
`function rel_next_prev(){
    global $paged;

    if ( get_previous_posts_link() ) { ?>
        <link rel="prev" href="<?php echo get_pagenum_link( $paged - 1 ); ?>" /><?php
    }

    if ( get_next_posts_link( '', 5 ) ) { ?>
        <link rel="next" href="<?php echo get_pagenum_link( $paged +1 ); ?>" /><?php
    }

}
add_action( 'wp_head', 'rel_next_prev' );`

**Comment by xdima92x** [comment]
Unfortunately, it's not possible. But a user can use this code - https://wordpress.stackexchange.com/questions/36800/adding-rel-next-rel-prev-for-paginated-archives

**Notice:** For get_next_posts_link you need to add a max page ( manually )

```
function rel_next_prev(){
    global $paged;

    if ( get_previous_posts_link() ) { ?>
        <link rel="prev" href="<?php echo get_pagenum_link( $paged - 1 ); ?>" /><?php
    }

    if ( get_next_posts_link( '', 5 ) ) { ?>
        <link rel="next" href="<?php echo get_pagenum_link( $paged +1 ); ?>" /><?php
    }

}
add_action( 'wp_head', 'rel_next_prev' );
```
