### ISSUE TITLE
missing child header.php modification

### ISSUE THREAD

**Issue by mdemori** [live-composer/live-composer-page-builder#817]
Hello, 

i just discovered a strange problem, currently I have a Google Tag Manager JS on header of my Wordpress child template. I discover that inside the pages created with Live Composer this tag is missing! seem that the Live composer rendered page don't include default header. All pages except those created with live composer contain the GTM js that is included in my header.php child file.

There is something that i miss?

**Update** 
i did some other test, also including the GTM inside the original theme header.php don't work. Code is missing from live composer pages but exists in all other pages.

thank you

**Comment by lumberman** [comment]
@mdemori Live Composer doesn't use your theme header.php if you choose to create a header in the Live Composer. You need to decide who takes care of your headers: theme or Live Composer.

This https://wordpress.org/plugins/google-tag-manager/ or any similar plugin can be used to insert your GTM code with better precision.

Please, reopen this ticket if you need more help.
Thank you.
