### ISSUE TITLE
[Module Options] New options type - repeater/group

### ISSUE THREAD

**Issue by ArekZw** [live-composer/live-composer-page-builder#819]
Repeater/group is popular field. It allow to create a certain number of elements in one group (array).
Perfectly suited to accordions and tabs and other front-end modified content.
For example, now in accordions nav or content are stored in one text field and Live Composer use dslc_sep to separate one content from other:
$accordion_nav = explode( '(dslc_sep)', trim( $options['accordion_nav'] ) );

But what if we want to add an icon to the accordion nav and edit it field using icon type options? It's impossible now.

My proposition:
![newfield2](https://user-images.githubusercontent.com/11788346/31176551-7ad2d172-a913-11e7-84de-9e57b7b91ee9.png)

Repeater options type allows to easy create new modules and extend existing.

How it works in other plugins:
http://aristath.github.io/kirki/docs/controls/repeater.html
https://carbonfields.net/docs/guides-repeating-groups/?crb_version=2-1-0
https://github.com/CMB2/CMB2/wiki/Field-Types#group

**Comment by lumberman** [comment]
@ArekZw Why don't you follow the method we are using in Tabs/Accordion method? We will invest time into this but only if I see a clear need for that.

**Comment by FoldingTheme** [comment]
#805
