### ISSUE TITLE
Bug\Fix required on Live Composer cache, caches logged in user data

### ISSUE THREAD

**Issue by juslintek** [live-composer/live-composer-page-builder#820]
If you turn on caching of live composer and am logged in. Comments forms is cached and after that when you go with browser into private mode, you can still see your private data. 🔓

**Comment by xdima92x** [comment]
Hi @juslintek I'm not sure if I understand you. I did it how you describe your problem. I don't see a problem. Could you create a screenshot or screencast with your problem?

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
