### ISSUE TITLE
Bug - Fix required. Responsive styles override regular styles.

### ISSUE THREAD

**Issue by juslintek** [live-composer/live-composer-page-builder#821]
For some reason at least on Text Module, if you set responsive styles, like text-align for mobile and tablet. The Desktop version inherits those styles as well. So I think its a bug. Because you cannot do proper responsive styling with this issue.

**Comment by xdima92x** [comment]
Hi @juslintek I checked the option 'text-align' in the module 'Text'. I don't see this bug. It works. Could you create a screenshot or screencast with your problem?

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
