### ISSUE TITLE
Undefined offset: 0 + Trying to get property of non-objec in display-functions.php with custom post type

### ISSUE THREAD

**Issue by GabLeRoux** [live-composer/live-composer-page-builder#822]
Hi there,
First, thanks for this plugin, it really rocks. Been using it for a while and it makes it quite easy to make stunning pages while generating clean html 👍 

## The error

I've updated to `1.0.2` and my dev site which has `define( 'WP_DEBUG', true );` outputs this bellow the title of my custom post types in the custom post type's `archive-[custom_post_type].php` page:

```
Notice: Undefined offset: 0 in /srv/www/mysite/wp-content/plugins/live-composer-page-builder/includes/display-functions.php on line 550

Notice: Trying to get property of non-object in /srv/www/mysite/wp-content/plugins/live-composer-page-builder/includes/display-functions.php on line 550
```

**I'm not using `live-composer` for this custom post type.**

## My custom post type

Inside my `functions.php` I have the following:

```php
// Custom post type
function mytheme_create_post_types()
{
  register_post_type('history',
    array(
      'labels' => array(
        'name' => __('History'),
        'singular_name' => __('event')
      ),
      'public' => true,
      'has_archive' => true,
    )
  );
}

add_action('init', 'mytheme_create_post_types');
```

Here's how my `archive-history.php` looks like:

```php
<?php get_header();

// query
$the_query = new WP_Query(array(
  'post_type' => 'history',
));

?>

<section>
  <?php if ($the_query->have_posts()) : while ($the_query->have_posts()) : $the_query->the_post(); ?>
    <h2><?php the_title(); ?></h2>
    <div class="entry-content">
      <?php the_content(); ?>
    </div>
  <?php endwhile; endif; ?>
</section>

<?php wp_reset_query();   // Restore global post data stomped by the_post(). ?>
<?php get_footer(); ?>
```
_I've removed a few things to reduce noise here, but with the above, I still get the notice ;)_

**Comment by xdima92x** [comment]
Hi @GabLeRoux Which plugin did you update? The Live Composer has current version 1.3.7.

**Comment by GabLeRoux** [comment]
Sorry, I can’t tell, I’m not using live-composer anymore. At the time of writing this, I was using latest version of live-composer available through wordpress updater with error reporting set to the most verbose (for local development).

**Comment by xdima92x** [comment]
Hi @GabLeRoux Ok, Thanks!
