### ISSUE TITLE
Fixed header padding not working

### ISSUE THREAD

**Issue by 101010f** [live-composer/live-composer-page-builder#823]
The fixed header option for additional padding only works for the homepage not the other templates.

Seems the header padding overrides the row padding.

**Comment by xdima92x** [comment]
Hi @101010f I checked it. Can you create a screenshot or screencast with your problem?

**Comment by 101010f** [comment]
The homepage doesn't have this problem but for the rest of the pages I have to add an empty div to compensate for the navigation height.
![capture](https://user-images.githubusercontent.com/20680030/32460142-774ad63a-c33a-11e7-844f-cbe3367f8908.jpg)

**Comment by xdima92x** [comment]
Hi, Could you send me a link to your website?

**Comment by xdima92x** [comment]
Hi @101010f I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
