### ISSUE TITLE
Items per row 5 option missing from all post modules

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#824]
https://www.evernote.com/l/Ajk69sIFebZPToVOpV_kbrc5us9g7Lu4lOk

It jumps from 4 to 6 on Blog, posts, staff, projects and all other CPT modules.

Cheers!

**Comment by ArekZw** [comment]
This is caused by 12 columns grid
12/1 = 12 col element
12/2 = 6 col element
12/3 = 4 col element
12/4 = 3 col element
12/6 = 2 col element

**Comment by FoldingTheme** [comment]
yes, the 12 is not divisible with 5.

**Comment by jgajera** [comment]
You can just use custom CSS with this. Set every column's width to less
than 20%. Give us a live link if you need further customization.
