### ISSUE TITLE
Comments count in the "Blog module" meta

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#829]
Please consider adding a new meta feature to the blog module. The "Comment count" is one of the most used meta in blog listings.

**Comment by xdima92x** [comment]
Example - https://www.evernote.com/shard/s569/sh/1e9a6196-deae-4f18-800e-c0c36614676c/fdb9feaa1826d56d

**Comment by FoldingTheme** [comment]
Dima, works great but need to add a left padding/margin:

![comment](https://user-images.githubusercontent.com/21088706/41456028-f513c4c8-7087-11e8-9e80-302ad2bca0a1.png)
