### ISSUE TITLE
Archive listing issue with the first post (opening unstyled archive instead of the single post)

### ISSUE THREAD

**Issue by emingus** [live-composer/live-composer-page-builder#832]
My first posts are going to the "default" styling. It was an issue that has been fixed a month ago, now it's back with new release!!! :(
![capture](https://user-images.githubusercontent.com/31526173/32572680-f7c6f4fe-c490-11e7-9f27-f4f040535607.PNG)
![1](https://user-images.githubusercontent.com/31526173/32572681-f7d85aa0-c490-11e7-9a99-b5a4891829df.PNG)

**Comment by xdima92x** [comment]
Hi @emingus Please download a branch 'master' and say me if fixed it.

**Comment by emingus** [comment]
Seems like it fixed it. What's the difference between the auto update and the branch master?

**Comment by xdima92x** [comment]
It's a good news. In the master branch, we fixing bugs and preparing a new release of Live Composer for auto update. :)

**Comment by emingus** [comment]
Can you send me an update of when it's fixed. I recently updated via Wordpress (not using branch master) and now the bug doesn't seem to be on the first post was a random post. (Third down if that makes a difference). Maybe i jumped the gun at downloading it before it was fixed. Thanks for all your hard work. I LOVE LC!
