### ISSUE TITLE
Connection between custom posts

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#833]
Please study the possibility to create a connection between custom posts. For instance, in a Project CPT to can use/link/connect a Partner CPT or a Testimonial CPT (and viceversa 💯  )

**Comment by lumberman** [comment]
@FoldingTheme do you have ideas on how it can looks like (UI)?

**Comment by FoldingTheme** [comment]
Maybe something like this:
![idea](https://user-images.githubusercontent.com/21088706/38958161-1bde7d46-4365-11e8-80a5-f64a3c052136.png)

On testimonials, the "Staff" selector is replaced with the "project name", etc.

**Comment by xdima92x** [comment]
It works. It's a beta version - https://github.com/live-composer/live-composer-page-builder/tree/issue/833 Needs testing

**Comment by FoldingTheme** [comment]
great job!
