### ISSUE TITLE
PHP 7.1 Compatibility

### ISSUE THREAD

**Issue by CharlieLivingston** [live-composer/live-composer-page-builder#836]
As also reported [here](https://wordpress.org/support/topic/php-7-1-compatibility-8/), since upgrading to PHP 7.1 we are seeing this in our server error logs:

“PHP message: PHP Warning: Illegal string offset ‘code_version’ in /wp-content/plugins/live-composer-page-builder/includes/display-functions.php on line 964”

**Comment by lumberman** [comment]
We will check it and have update ready soon.

**Comment by xdima92x** [comment]
I fixed it: https://github.com/live-composer/live-composer-page-builder/tree/issue/836
