### ISSUE TITLE
Action hook for css-generation.php

### ISSUE THREAD

**Issue by calvincanas** [live-composer/live-composer-page-builder#838]
Hello guys,

It would be great if you can add a action hook for css-generation.php inside function **_dslc_generate_module_css_** 

Reason for this request is we want to have an option for eligible modules to input an fully-qualified image url for background-image. Unfortunately I can't see a hook where I can add a custom code for that. The prepend and append that the option type 'image' is what I am after.

You can see the prepend and append handling on css-generation.php line 624-627

This is what I have
Plugin Version: 1.3.8.1

**Comment by xdima92x** [comment]
Hi, @calvincanas I added a new hook for css-generation.css. Please check this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/838 and say me if it.

**Comment by calvincanas** [comment]
The hook is on first few lines of the function. Can we add it inside the foreach with the $option_arr as a parameter. That way we can comb through each options. Just an idea.

**Comment by lumberman** [comment]
Instead of the previous action I added two filters:

```php
$module_settings = apply_filters('dslc_module_settings_before_cssgen', $module_settings);
$module_structure = apply_filters('dslc_module_structure_before_cssgen', $module_structure);
```

- **dslc_module_settings_before_cssgen** – used to change the actual settig values
- **dslc_module_structure_before_cssgen** – used to change the settings structure (standard values, etc.)

Let me know if more help needed.
