### ISSUE TITLE
WooCommerce Integration

### ISSUE THREAD

**Issue by jgajera** [live-composer/live-composer-page-builder#840]
I bought and started using the WC plugin yesterday. When I decided I didn't need it for this particular website, it messed up my shop.
*
My shop page and category pages aren't showing up. The product page is okay, cart is fine, but checkout is wonky-looking. Any help here!??!?!?!?! Shortcodes are still in the page content area, so the plugin didn't mess up anything on the back-end. I just can't get LC to get off of my WC pages.
*
I shouldn't have installed the plugin on a site I already polished up... Also, my LC cache is disabled. I reset permalinks. I reset my Shop page selection under WC Settings. Not sure what else I can do?

**Comment by lumberman** [comment]
Please try this version of LC:
[live-composer-page-builder.zip](https://github.com/live-composer/live-composer-page-builder/files/1512180/live-composer-page-builder.zip)
