### ISSUE TITLE
Image Link

### ISSUE THREAD

**Issue by tyleross** [live-composer/live-composer-page-builder#841]
Image elements with link url to domain subdirectory work just fine. But image elements with link url to subdomain do not work. Why is that?

**Comment by jgajera** [comment]
Live link showing the problem?

**Comment by tyleross** [comment]
subdomain works just fine, can type it into the address bar and go right to it. But when I click on the image that links to the subdomain, it redirects me to the domain.

My domain is www.tylerlongfellow.com
I put in the image element to go to largeformat.tylerlongfellow.com and when the image is clicked it tries to take you to www.tylerlongfellow.com/largeformat.tylerlongfellow.com and then redirects to www.tylerlongfellow.com

**Comment by tyleross** [comment]
I fixed it by putting http:// in front of largeformat.tylerlongfellow.com
I don't know why that worked when I didn't have to do that to the other image links

**Comment by jgajera** [comment]
That is what I was going to suggest. It's better to put the whole URL (including http/https) with LC whenever it asks for links!

**Comment by lumberman** [comment]
@xdima92x reproduce this bug.
Add verification: if provided image url with www. but without http(s) >>> add // to the front, so we have //www.subdomain.....
