### ISSUE TITLE
Pre-designed Sections in LC

### ISSUE THREAD

**Issue by lumberman** [live-composer/live-composer-page-builder#842]
Tasks:
- [ ] Activation Workflow Designs
- [ ] Code import workflow
- [ ] Basic Designs
- [ ] Free Designs activation workflow
- [ ] Premium Designs
- [ ] License

Bugs:
- [x] Breaks Live Composer menu in WP Admin

**Comment by ArekZw** [comment]
Look for Qards - https://wordpress.org/plugins/qards-free/

They have awsome predesigned sections workflow - https://ps.w.org/qards-free/assets/screenshot-5.jpg?rev=1785434

Maybe you can get inspiration from this?

**Comment by lumberman** [comment]
Yes, we have already something similar coded. You can check this branch: https://github.com/live-composer/live-composer-page-builder/tree/feature/predesigned-section

Now working on sections designs library.

**Comment by ArekZw** [comment]
Nice! Thank you and xdima92x for great job.

Second place to get inspiration is imcreator.com, where "pre-designed section library" is displayed between two sections:

![image](https://user-images.githubusercontent.com/11788346/34207580-63bf01e0-e58b-11e7-8b3b-8f20aaebea62.png)

**Comment by lumberman** [comment]
Thanks for showing this.
The last example conflicts with Gutenberg UI that we want to adopt latter once it's released.

**Comment by xdima92x** [comment]
I will open this ticket when we will work with Pre-designed Sections in LC. At this moment, we have other improvements and issues with LC
