### ISSUE TITLE
Open graph issues on the post template

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#847]
When the a template is set to "Blog Posts" some of the meta's are gone (image alt and description)
![sharing_debugger_-_facebook_for_developers_and_edit_template_ _test_web_ _wordpress](https://user-images.githubusercontent.com/21088706/33704619-d96cc9f0-db35-11e7-811b-382caffbb8ba.png)

**Comment by lumberman** [comment]
Live Composer has nothing to do with open graph. Normally it's Yoast SEO generates it. 
In the Yoast plugin settings user can set description for author and date archives:
<img width="1054" alt="edit__search_results" src="https://user-images.githubusercontent.com/1384471/33794402-01b09ce4-dc89-11e7-92df-2824db609e20.png">
As for image alt – it get's generated if the image has description in the WP Admin > Media  section.

**Comment by FoldingTheme** [comment]
@lumberman pls check t: 30595

**Comment by lumberman** [comment]
Solved. Wait for fix in the next plugin update.
