### ISSUE TITLE
Author and post archive template and working not correctly

### ISSUE THREAD

**Issue by DS85** [live-composer/live-composer-page-builder#848]
Author and post archive templates are not working correctly. To be sure I made everything again: 
1. Install new WP without any plugins, just LC. 
2. Install new theme (This time used Orao) and data, that comes with it.
3. Create template for author and posts archive.
4. Start clicking on posts, categories and authors. You will find, that in some cases you will see page, that is shown not according to template. As I found - which template works wrong - archive or post - depends on which template you saved last.

**Comment by lumberman** [comment]
Hi there,
Thanks for reporting this, but I can't recreate it.

1) I created a template with the next settings:
<img width="965" alt="edit_template_ _live_composer_ _wordpress" src="https://user-images.githubusercontent.com/1384471/33794219-ccdc5c46-dc84-11e7-8813-704896e50f14.png">

2) Then I placed POSTS module on the template:
<img width="1054" alt="edit__search_results" src="https://user-images.githubusercontent.com/1384471/33794231-ecfc8942-dc84-11e7-97fb-0ab1d5d4586d.png">

As result category listing and author archive listing is working as expected using the template created in the first step. a

Send me a temporary access to your WP admin via [this form](http://livecomposerplugin.com/support/support-request/) and I will try to help you further/

**Comment by lumberman** [comment]
Closing for now. Please, reopen if needed.

**Comment by DS85** [comment]
Hi
I've sent you access to WP admin via [this form](https://livecomposerplugin.com/support/support-request/) with description how to see the problem. Can you see the problem now?
