### ISSUE TITLE
Make element output for mobile and tablet element disabled enabled at php level

### ISSUE THREAD

**Issue by juslintek** [live-composer/live-composer-page-builder#851]
Because elements for tablet and mobile are printed, but not shown. As well this printing causes overhead in response time, because simultaneous repetitive queries are made.

**Comment by lumberman** [comment]
Hi @juslintek I'm afraid there is no way to make it possible.
Server-side browser detection is very limited and it will break even more stuff (like caching). In general it's a good practice to adopt desktop elements to mobile view not duplicate it.

**Comment by juslintek** [comment]
Yes, I know, but there is no proper way in adopting in Live Composer, for example can't change column width on different screens, in order to do that, you have to duplicate the row and change column widths per row and change the visibility of the row. And that causes big load on php because of duplication and seems like live composer has issue with re usability of same cached objects, so made some of my own modules which do multiple checks on chacke first for objects for render, then for the generated render. if generated render exists in cache the skips object and echos the static content render.

**Comment by lumberman** [comment]
If you have caching option enabled in the settings it will not "re-calculate" module each page view. In any case you should have file-based cache enabled. No one can beat it. 

Why don't you create a feature request to have responsive columns instead? It looks like the source of you problem....

**Comment by juslintek** [comment]
Yes, that is one of the problems, other is that live composer cache if turned on shows to public users logged in users info on comments section. I think its a bug.

**Comment by lumberman** [comment]
The comments issue should be fixed now. If not fixed on your side please open the issue and we will investigate. Any "dynamic" content now stored in shortcodes that cache ignores.

**Comment by juslintek** [comment]
Hm, then it probably conflicts with Cache Enabler cache and Redis Object Cache.
