### ISSUE TITLE
Add/Feature Responsive Columns

### ISSUE THREAD

**Issue by juslintek** [live-composer/live-composer-page-builder#853]
Would decrease server response time if this feature would exist, because you wouldn't need to duplicate rows in order to change column width on different screens and wouldn't need to override in theme for specific occasions width changes on wanted screen in order to optimise server response time.

**Comment by lumberman** [comment]
Note: as part of new stylist feature?

**Comment by juslintek** [comment]
Yes, this could be stylist feature. As well if I were you I would change naming as written here: https://medium.com/peergrade-io/structuring-css-in-large-projects-37f1695f5ec8

And would use sass php client minify and ensure re-usability of repeatable elements css. For example on save https://github.com/leafo/scssphp would  preprocess with this lib styles using scss mixins and functions to make sure the output css is as slick as possible.

**Comment by xdima92x** [comment]
I will open this issue when we will optimize the Live Composer
