### ISSUE TITLE
Add/Feature load responsive content via ajax when screen size matches

### ISSUE THREAD

**Issue by juslintek** [live-composer/live-composer-page-builder#854]
I think this would save lots of load time if content for mobile and tablet for desktop would be skipped from processing and only loaded when screen width matches. Here is a library which can properly detect screen size from client header http://mobiledetect.net/

**Comment by juslintek** [comment]
Guess its better to render data via ajax (async). Depending on screen. Like check before render screensize and only then load data. Wonder how would that affect seo. Do search engine bots require content to be prerendered or they can now process javascript.

**Comment by xdima92x** [comment]
Good point. I will open this issue when we will optimize the Live Composer. At this moment, we have other improvements and issues with LC
