### ISSUE TITLE
Make interface looks closer to Gutenberg

### ISSUE THREAD

**Issue by lumberman** [live-composer/live-composer-page-builder#855]
Since Gutenberg is going to be a default page builder we need to inherit their UI to make easier migration / adaptation for new users.

**Comment by lumberman** [comment]
Yes we have plans for that, but until G. released and stable we can't make any moves.

**Comment by epakrat** [comment]
Still waiting for Official WP v5 release? While WP v5.0 will not be coming this year, the Gutenberg plugin is MUCH improved and more stable over what was available in January. There's no longer sufficient reason to not at least begin LC Gutenberg development especially considering many page builders have already completed their compatibility. I for one want to begin testing LC with Gutenberg this year not when v5 comes out early next year.

**Comment by xdima92x** [comment]
I will open this ticket when we will work with Gutenberg and LC
