### ISSUE TITLE
Add/Feature add more hook and actions to completely override css or js remove or rewrite essential functions.

### ISSUE THREAD

**Issue by juslintek** [live-composer/live-composer-page-builder#857]
This would help in lots of projects to override non flexible stages of plugin to work by your custom methods and avoid waiting for feature or issues to be fixed by owners of the project.

**Comment by lumberman** [comment]
You can override CSS now as we have a lot of custom hooks and filters.
I keep this task open so you can add any particular filters / hooks you need.

**Comment by lumberman** [comment]
Please, reopen when needed.
