### ISSUE TITLE
Shouldn't caching work like this?

### ISSUE THREAD

**Issue by juslintek** [live-composer/live-composer-page-builder#858]
I've noticed that you cache options only. You do not cache the render.

Wouldn't it be better if you lets say would cache two things, old key with lets say module name and its id, and the value would be `md5 ( serialize ( $options) ) . ':name_of_module'`.

And next cached item would be the content itself which id would be same `md5 ( serialize ( $options) ) . ':name_of_module'`. So for example when options change and old key doesn't match new key. You flush or update old key with new value and flush content cache using old key to flush old cache and create a new one with newly generated key from $options. In this way, for example if caching is enabled for logged in user. One can see changes in live-composer and it saves resources and as well static cache creation becomes faster.

**Comment by lumberman** [comment]
We cache rendered HTML (except shortcodes): 
https://github.com/live-composer/live-composer-page-builder/blob/master/includes/display-functions.php#L782

we cache calculated CSS: https://github.com/live-composer/live-composer-page-builder/blob/master/includes/css-generation.php#L240

+ we cache used google fonts

Beside all above we have object cache for module settings that used during the same php session.
