### ISSUE TITLE
Latest LC & HQ Tips&Tricks (ecommerce solution) incompatible.

### ISSUE THREAD

**Issue by emingus** [live-composer/live-composer-page-builder#861]
I'm using LC v 1.3.1 because the current version of LC is incompatible with my ecommerce solution (HQ Tips and Tricks WP estore).

All other plugins disabled for testing other than WP estore and LC. Disabled LC and went to Twenty17 and it worked. Installed the previous version of LC (the one I was positive worked was 1.31.) and it works again.

Figured I'd say something since recent updates were to WooCommerce.

Tested on RadicalChristianWoman.com

**Comment by lumberman** [comment]
Hi there,
Can you send a copy of the conflicting plugin to **support [ a t ] livecomposer.io** ?
I will test it on our server and let you know my observations or fix it (if possible).
Thank you.

**Comment by FoldingTheme** [comment]
the customer didn't provide an answer.
