### ISSUE TITLE
The search template query doesn't apply

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#864]
![edit__search_and_ _search_results_ _hel](https://user-images.githubusercontent.com/21088706/34667179-8ed88bc8-f470-11e7-9046-c55c576946c8.png)

Used for test the Blog and Posts modules.

**Comment by xdima92x** [comment]
It works. Please use this option - https://www.evernote.com/shard/s554/sh/3203ff9a-56de-4aa3-9584-7228b0c62a4e/0ec048a7bd9a3155
