### ISSUE TITLE
The default row vertical paddings

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#865]
![live_composer_ _page_builder_ _wordpress](https://user-images.githubusercontent.com/21088706/34712479-95cb83b6-f52b-11e7-9580-b0aa41f312d9.png)

Will be great if the customer can set the default vertical padding of the row. 
This value should be overwrite the row padding option from row options (LC front-end panel)

**Comment by xdima92x** [comment]
@FoldingTheme I added it. You can use this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/865
