### ISSUE TITLE
Bug when removing The Content or Thumbnail modules I get 404 over ajax

### ISSUE THREAD

**Issue by juslintek** [live-composer/live-composer-page-builder#874]
When I turned on debug to see what happening. I get this:

Notice: Undefined index: dslc_module_id in wp-content/plugins/live-composer-page-builder/includes/ajax.php on line 86

**Comment by juslintek** [comment]
Shows up its thumbnails module on page fault. It duplicates content and thumbnail over and over again. Every time you save it.

**Comment by xdima92x** [comment]
Hi @juslintek Could you show me step by step how to get this error? I'm removing the Content or Thumbnail modules and I don't get this error. Could you use [this branch](https://github.com/live-composer/live-composer-page-builder/tree/development) and say me if help?

**Comment by juslintek** [comment]
Hi, sorry forgot about this issue. Will test it out if it still exists. 👍

**Comment by juslintek** [comment]
Its not happening anymore. Solved, guess it was problem of badly written shortcode, which was echoing data instead of returning it.
