### ISSUE TITLE
Issues with new Wordpress Release 4.9.2

### ISSUE THREAD

**Issue by johnpkeek** [live-composer/live-composer-page-builder#876]
Hi Team,

We have been using this wonderful plugin for quite a while now. Unfortunately when we have taken the Wordpress update tp 4.9.2 our Live composer plugin doesn't seem to work properly. We tried updating the plugin to the latest version 1.3.9. But this one also doesn't help. Can you please check.

Thanks
John

**Comment by xdima92x** [comment]
Hi @johnpkeek What do you mean? I don't have this bug.
1) Try do deactivate all the other plugins for a minute and see if LC works as expected?
2) Try to activate a default WP theme for a minute and see if LC works as expected?
3) Do you have [JavaScript error?](https://livecomposer.help/article/233-troubleshooting-javascript-error-detected)

**Comment by xdima92x** [comment]
Hi @johnpkeek I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
