### ISSUE TITLE
Woocommerce shop and product category pages not working

### ISSUE THREAD

**Issue by carlosjtacon** [live-composer/live-composer-page-builder#878]
When installing and enabling livecomposer (greater than 1.3.7) woocommerce stop showing content on its shop and product category default pages.

**Comment by xdima92x** [comment]
Hi @carlosjtacon Did you follow this article? https://livecomposer.help/article/233-troubleshooting-javascript-error-detected

**Comment by carlosjtacon** [comment]
I don't think I have a javascript error. The livecomposer plugin works great but it makes non-livecomposer woocommerce pages blank. Downgrading to 1.3.7 solves the problem.

**Comment by xdima92x** [comment]
H again Carlos Tacón :) You need to contact with [support of team](https://livecomposerplugin.com/support/) to check your website.
