### ISSUE TITLE
Woocommerce The Content

### ISSUE THREAD

**Issue by RobertShippey** [live-composer/live-composer-page-builder#880]
Hi, 

Not sure if this is a problem with LC or the Woocommerce integration plugin, but it doesn't seem to be applying the proper filters to The Content as paragraphs aren't being applied. Viewing the source I can see hard returns are there (as per editor) but viewing the page the text all runs together due to no `<p>`s. 

See here: http://www.8thdimensionaudio.com/product/nativ-audio-disc/

Any help would be appreciated. Thanks.

**Comment by xdima92x** [comment]
Hi @RobertShippey I'm not sure what I understand your question. Module Woo Tabs or Woo Excerpt? Could you create a screenshot of your problem?

**Comment by RobertShippey** [comment]
The LC WooCommerce Tabs Product Description. 

There is three paragraphs in the editor. There are no `<p>` tags being applied to the output so the text is all running together as seen on the page.

You can see from the html that it's simply outputting the content directly without applying the usual filters to sort that out. 

https://pasteboard.co/H5CdjSz.png

**Comment by xdima92x** [comment]
Could you change your theme by default and say me if you have this bug? I don't have this bug.

1) Added <p> tags  - https://www.evernote.com/shard/s554/sh/ebbc73f9-0ac8-42ba-81d7-4c430ac30e1d/fc2c68a3cc8e6323
2) HTML code - https://www.evernote.com/shard/s554/sh/92ebd301-a134-4e0b-a39f-19bd1a2ecc78/1df33268f102bee6

**Comment by RobertShippey** [comment]
I'm using the Live Composer Blank theme. 

You see the "p" tags automatically or you added them manually? The tags aren't added automatically when using the visual editor to enter paragraph text. It's my understanding that they're added via a filter at a later date when wordpress is displaying the post/product via `the_content` function (as described here https://stackoverflow.com/questions/34722742/why-are-p-tags-not-being-added-to-my-wordpress-posts). Am I wrong about that default behaviour?

**Comment by xdima92x** [comment]
You can install this plugin: https://wordpress.org/plugins/tinymce-advanced/ with this setting 
![tinymce_advanced_ _page_builder_ _wordpress](https://user-images.githubusercontent.com/21044637/35725255-5f4f9a2a-0809-11e8-87fd-54aa1386fda4.png)

**Comment by RobertShippey** [comment]
So to be clear, both WordPress and WooCommerce natively support paragraphs in product descriptions (post content), but while using Live Composer with WooCommerce I need to install another plugin to _restore_ that functionality?? 

It seems nonsensical that LC would be removing this functionality for something as basic as paragraphs... on purpose... this **has** to be a bug, surely?

**Comment by xdima92x** [comment]
Yes, you are correct. Until we will provide a fix for this in a future update, please follow the above recommendation. Thanks for understanding.

**Comment by RobertShippey** [comment]
Thanks for your help, and for finding a workaround until the issue is fixed.
