### ISSUE TITLE
Maps not working with enabled cache

### ISSUE THREAD

**Issue by Viktor6713** [live-composer/live-composer-page-builder#881]
Hi, we are using Live Composer with WP Google Maps and there is still an issue as mentioned in #755 . First time map is loaded and displayed normally, on the second page reload no map. After cleaning cache map is displayed first time only, when we disable "Basic HTML/CSS Caching" map is displayed every time.
We've tested other map plugins with the same result.

**Comment by xdima92x** [comment]
Hi @Viktor6713 We had a problem of cache with our [addon Google Maps](https://livecomposerplugin.com/downloads/google-maps-add-on/). ( #755 ) If you using other map plugins then you should disable a cache in the Live Composer or you can use [our addon of Google Map](https://livecomposerplugin.com/downloads/google-maps-add-on/)
