### ISSUE TITLE
Frontend user roles

### ISSUE THREAD

**Issue by xnubian** [live-composer/live-composer-page-builder#883]
It would be really useful to have the opportunity to assign user editing roles to pages and post templates. E.g. I would like an author to be able to edit his/her page but not all the pages.

**Comment by xdima92x** [comment]
At this moment, we can't include in the Live Composer because we have other plans about the plugin. Maybe we add this later but I think you can use this plugin - https://ru.wordpress.org/plugins/user-role-editor/
