### ISSUE TITLE
Headers functionality on a lateral/sidebar position

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#884]
Will be great if the WP Admin > Appearance > Headers/Footers system will allow the usage on a lateral position.

![collection_01_ _the_fold](https://user-images.githubusercontent.com/21088706/36086704-885b2720-0fd6-11e8-8597-0ce2b285b5ea.png)

**Comment by FoldingTheme** [comment]
@xdima92x few examples:

https://themes.muffingroup.com/be/interior4/
https://themes.muffingroup.com/be/thriller/
https://themes.muffingroup.com/be/personaltrainer/
https://themes.muffingroup.com/be/adventure/product/adventure-book/
http://demo.theme.co/restaurant/
https://kriesi.at/themes/enfold-photography/

**Comment by xdima92x** [comment]
At this moment you can use a custom CSS for this issue. Maybe later we will add it.
