### ISSUE TITLE
W3c validation errors caused by LC

### ISSUE THREAD

**Issue by nject** [live-composer/live-composer-page-builder#886]
LC 1.3.11 and WP 4.9.4

I have 2 issues regarding w3c validator.

The 1st being Live Composer is adding an illegal character when calling for Google fonts i believe this is called in class.module.php, attempting to change or remove gives me the white screen of death.

The 2nd is that LC is adding a style of background-image: disabled (should be 'none') which is not an attribute of background-image. I have managed to change this in options.php and this got rid of one error but the rest are all inline classes and cannot for the life of me figure out where this is being called so i can change it from disabled to none or even remove all together?

https://validator.w3.org/nu/?doc=https%3A%2F%2Fnject.co.uk%2F

**Comment by nject** [comment]
![screenshot-error](https://user-images.githubusercontent.com/36449281/36159348-6341e450-10d6-11e8-8419-d5e70add91d2.png)

**Comment by xdima92x** [comment]
Hi, please update the last version plugin and say me if you have the same problem
