### ISSUE TITLE
fail update 1.3.11, i dont see modifications?

### ISSUE THREAD

**Issue by circunovo** [live-composer/live-composer-page-builder#887]
I just upgraded to live composer 1.3.11

Now it does not show me the changes I make in the pages (both in the new ones and in the ones created before).

I attached a video created to see the problem that has appeared with the update: https://youtu.be/HazFLkQ39LE

Thanks for your time and for the plugin, I love it!

**Comment by xdima92x** [comment]
Hi @circunovo Did you try to disable or clear the plugin cache (Live Composer > Performance)?

**Comment by circunovo** [comment]
Hello!!
I have deleted cahe and the history of the browsers, but never before had to delete / deactivate the cache in live composer. In my case I had to deactivate it and it works perfectly !!. A thousand thanks for the quick response. ;)

I have added a new video with the solution provided, for future consultations of other users. ;)
https://youtu.be/PKbHpz78qk0

**Comment by xdima92x** [comment]
You're welcome :)

**Comment by xdima92x** [comment]
We fixed it. Please update the plugin to the last version. Now "published change" work properly.
