### ISSUE TITLE
Missing Translation strings

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#891]
![_31283_re__live_composer_support__request_from_ricardo_amancio_-_ricardo_amancio](https://user-images.githubusercontent.com/21088706/36414274-6528fba6-162a-11e8-9a60-8c19f09c0d00.png)

There are no entries for such strings. Example: 
https://translate.wordpress.org/projects/wp-plugins/live-composer-page-builder/stable/pt-br/default

**Comment by xdima92x** [comment]
Loco Translate is a PO file editor, so only static text inside PO files can be translated.
