### ISSUE TITLE
Issue with publishing the content (West Wordpress Theme)

### ISSUE THREAD

**Issue by justurban** [live-composer/live-composer-page-builder#893]
Is anyone facing the same problem: after the last update I cannot publish the changes on 2 websites I am now working on. All changes are visible in the Wordpress admin panel, but after I close the Composer, I can see only the old version of the website.
Thanks for any advice!
Justyna

**Comment by neilschnabs** [comment]
Having the same issue

**Comment by neilschnabs** [comment]
FYI @justurban I resolved this issue. Under the live composer settings in the back end, go to the performance tab and clear the cache. Worked for me.
![capture](https://user-images.githubusercontent.com/36942379/36824812-50a820e0-1cd2-11e8-8157-758575bcd262.JPG)

**Comment by xdima92x** [comment]
Please read this article - https://livecomposer.help/article/276-my-changes-are-not-displayed-on-front-end

**Comment by xdima92x** [comment]
We fixed it. Please update the plugin to the last version. Now "published change" work properly.
