### ISSUE TITLE
cache problem with recent update

### ISSUE THREAD

**Issue by rodsbermudez** [live-composer/live-composer-page-builder#894]
I'm having some problems with cache on 3 websites with the new version of the plugin
I disabled alll the cache plugins and server and I´m still having the problem

Onde I update on Live Composer it takes forever to update on live website
But if I duplicate the page the new page apears with the change.
Só for now im doing this and then changing the slug

But I need this fixed, it is impossible to work like this

**Comment by jgajera** [comment]
Did you also disable cache in WP Admin > Live Composer > Cache > Disable >
Save?

**Comment by xdima92x** [comment]
Please read this article - https://livecomposer.help/article/276-my-changes-are-not-displayed-on-front-end

**Comment by xdima92x** [comment]
We fixed it. Please update the plugin to the last version. Now "published change" work properly.
