### ISSUE TITLE
The row icons cannot be selected when no padding are used

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#895]
![fullscreen_02_03_2018__12_32](https://user-images.githubusercontent.com/21088706/36895009-fc89c154-1e15-11e8-9eb0-300ca8fb008f.png)

When the module and the row doesn't have vertical paddings/margins, the row icons cannot be selected. Are flickering and changing with the module ones.

**Comment by xdima92x** [comment]
Duplicate: https://github.com/live-composer/live-composer-page-builder/issues/869
