### ISSUE TITLE
When Duplicating DSLC_Posts css_filter_border_radius looses its state

### ISSUE THREAD

**Issue by juslintek** [live-composer/live-composer-page-builder#897]
What I mean after duplication border-radius becomes turned off and usually value goes back to 3. Seems like on duplication for some reason this value is not copied.

**Comment by xdima92x** [comment]
Hi @juslintek I'm not sure I understand you. Could you create a screencast or screenshot of your problem? I don't have this problem. You can see here - https://drive.google.com/file/d/1IBWd5NwnoyRDqsZvkPuMyM6n1zAnrlMp/view

**Comment by FoldingTheme** [comment]
https://github.com/live-composer/live-composer-page-builder/issues/879
