### ISSUE TITLE
Takes too long to respond

### ISSUE THREAD

**Issue by nzukie** [live-composer/live-composer-page-builder#899]
I need help with updating my webpages..I cant see my changes immediately..How do I sort this out? because they take a maximum of 1 day to appear and some dont appear at all.

**Comment by xdima92x** [comment]
Hi @nzukie Please read this article - https://livecomposer.help/article/276-my-changes-are-not-displayed-on-front-end

**Comment by nzukie** [comment]
Thank You Dima It worked..much appreciated

*Nonzukiso Mafuya*

**Comment by xdima92x** [comment]
We fixed it. Please update the plugin to the last version. Now "published change" work properly.

**Comment by nzukie** [comment]
Thanks once again I updated to the latest version

*Nonzukiso Mafuya*
