### ISSUE TITLE
Header not updating?

### ISSUE THREAD

**Issue by aschutt12** [live-composer/live-composer-page-builder#900]
Even after the header is "published" it's not updating when I view it outside of the editor - it's actually getting even more screwed up and making the menu vertical as you can see in the picture.  Does anyone know why this is happening/how to remedy this?

![header error](https://user-images.githubusercontent.com/37485530/37559420-2fb36c0a-29fc-11e8-92b0-8528b925d6ff.png)

**Comment by xdima92x** [comment]
Hi @aschutt12 Did you try clear a cache in the Live Composer?

**Comment by aschutt12** [comment]
I just tried that and it worked!
  

  
Thanks!
  
  
  
 --
  
  
  
  
  
  
  
  
Andrew Schutt
  
www.ElevatedWebMarketing.com (http://www.ElevatedWebMarketing.com)
  
(607) 725 - 1007 (tel:(607)%20725%20-%201007)
  
  
  
  
  
  
  
  
  
  
  

  
  
>

**Comment by xdima92x** [comment]
We fixed it. Please update the plugin to the last version. Now "published change" work properly.
