### ISSUE TITLE
Cache not flushing on ajax save action.

### ISSUE THREAD

**Issue by lumberman** [live-composer/live-composer-page-builder#901]

**Comment by xdima92x** [comment]
I checked this issue. It works.

**Comment by FoldingTheme** [comment]
the problem still remain. need more testings.

**Comment by FoldingTheme** [comment]
it seems the problem is related to some third-party plugins (Master Slider). Try to reset the cache every time the page requested by the site admin.

**Comment by FoldingTheme** [comment]
Let's stick together all the cache issues.

**Comment by xdima92x** [comment]
Hi) I will reopen an issue #904 because of it is [PHPUnit Test](https://make.wordpress.org/core/handbook/testing/automated-testing/phpunit/). It's a new feature but not a bug :)

**Comment by FoldingTheme** [comment]
The Master Slider cache issue fixed!
