### ISSUE TITLE
Add PHPUnit Test ( Cache )

### ISSUE THREAD

**Issue by xdima92x** [live-composer/live-composer-page-builder#904]
**Doc:**
1. https://github.com/inpsyde/wordpress-dev/blob/master/tests/phpunit/tests/option/option.php
2. https://pippinsplugins.com/unit-tests-wordpress-plugins-writing-tests/
3. https://pippinsplugins.com/unit-tests-for-wordpress-plugins-the-factory/
4. https://make.wordpress.org/core/handbook/testing/automated-testing/writing-phpunit-tests/
5. http://richardsweeney.com/testing-integrations/

**Comment by xdima92x** [comment]
https://github.com/inpsyde/wordpress-dev/blob/master/tests/phpunit/tests/option/option.php

**Comment by xdima92x** [comment]
https://pippinsplugins.com/unit-tests-wordpress-plugins-writing-tests/

**Comment by xdima92x** [comment]
https://pippinsplugins.com/unit-tests-for-wordpress-plugins-the-factory/

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/904

**Comment by FoldingTheme** [comment]
#901

**Comment by xdima92x** [comment]
Hi) I will reopen an issue #904 because of it is PHPUnit Test. It's a new feature but not a bug :)
