### ISSUE TITLE
Sticky option

### ISSUE THREAD

**Issue by xdima92x** [live-composer/live-composer-page-builder#908]

**Comment by xdima92x** [comment]
1) ‘Can be adjusted/copied the way the module animation work (onload)?’ - I checked an animation code. Don’t have a code for a sticky option.
2) ‘The plugin already render the CSS styles on the page. Cannot be used the power of this instead using js?’ - It’s not a possibility. We need to use extra Javascript.

**Comment by FoldingTheme** [comment]
@xdima92x 

I know the animations js doesn't hv sticky feature. The thing is that if we can use the core of the library to adapt it to the sticky feature.

On tests, there are few issues with the present sticky feature:

- No smooth transition on the header. 

- Is jumping before to get in the position
https://www.dropbox.com/s/qjxzx3gbm6us3iw/sticky-jumping.mp4?dl=0

- When two sticky rows are used in the header, the second one takes the sticky position even is not already in place. For instance, when the first row become sticky on scroll, automatically, the second row receive the sticky class and have the same behavior, even is not already in the position of the browser top. Please check again the above scenarios.

**Comment by xdima92x** [comment]
@FoldingTheme 

1) Please use and update this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/908_2
2) I don't have a bug with headers - https://drive.google.com/file/d/1i6hEMU8HvCTlb1ypokcavbZ1gtGrrPJg/view
3) I don't have a bug with headers - https://drive.google.com/file/d/1qYbOJELR7Lur7w0gS5fd7HwdjCRukmuF/view
4) Ok, I will try to add a smooth transition

**Comment by FoldingTheme** [comment]
@xdima92x 

1. Check the 16 second of your first record. The second header should not have the sticky feature applied just because the first row reach the browser top. 
2. Still render the same jumping issue displayed in the above screencast. Try to use zero paddings on sticky to have the problem more visible.

Thank you!

**Comment by xdima92x** [comment]
@FoldingTheme 

I added a smooth transition but we have a problem when header and body sticky or two headers sticky - https://drive.google.com/file/d/1pivZ2NHpoKIE8nk92ienktaJp3Rx0x1J/view I don't have an idea how to fix it.

**Comment by FoldingTheme** [comment]
@xdima92x 

Let's keep the feature without transition at this time. It can be added later.

**Comment by FoldingTheme** [comment]
@xdima92x 

We have a z-index problem when more many drop-downs are used in header sticky rows:
https://www.dropbox.com/s/5uu0ksqpxs45y73/sticky-top-menu-z-index.mp4?dl=0

**Comment by FoldingTheme** [comment]
the z-index problem is present in the body too. 
![01_sticky](https://user-images.githubusercontent.com/21088706/39257434-2be7f5fa-48ba-11e8-918f-7c34c15d1947.png)

**Comment by xdima92x** [comment]
@FoldingTheme 

I fixed it. Please use these branches:

1) Live Composer - https://github.com/live-composer/live-composer-page-builder/tree/issue/908_2
2) LC Extensions - https://github.com/lumbermandesigns/lc-extensions/tree/stick_option

**Comment by FoldingTheme** [comment]
This branch break the installation:

![lc_sticky_bug](https://user-images.githubusercontent.com/21088706/39346415-b32a44cc-49f6-11e8-9f61-2501eab5073a.png)

**Comment by xdima92x** [comment]
@FoldingTheme 

Please check if it works a properly. You should use these branches:

1) Live Composer - https://github.com/live-composer/live-composer-page-builder/tree/issue/908_2
2) LC Extensions - https://github.com/lumbermandesigns/lc-extensions/tree/issue/20

**Comment by FoldingTheme** [comment]
![z-index-issue](https://user-images.githubusercontent.com/21088706/39448732-7b8156e8-4cce-11e8-961c-6ff815183bd1.png)

@xdima92x  
we have a z-index issue on the header, on columns option panel.

**Comment by FoldingTheme** [comment]
Please check and https://github.com/lumbermandesigns/lc-extensions/issues/38
