### ISSUE TITLE
Problem with styling presets on TEXT ELEMENT

### ISSUE THREAD

**Issue by mozalan** [live-composer/live-composer-page-builder#909]
Getting JavaError:

JavaScript error detected in a third-party plugin
Uncaught TypeError: Cannot read property 'trim' of null

Presets don't get applied properly, keeps gettings corrupted and if you don't want to save it to try again, it saves automatically and applies the same preset to all others.

Also, on Text Element box styles, doesn't get applied to others when using the same preset.

Please check it - there must be a bug and unfortunately it just wasted few hours of work... 

Have to do it all again tomorrow...

**Comment by FoldingTheme** [comment]
We haven't seen this problem on other users website, so I think it's somehow linked to your server or other plugins. Please check this article: https://livecomposer.help/article/196-basic-debugging-process

If still need assistance after debug, please open a support ticket and provide an admin access: https://livecomposerplugin.com/support/support-request/
