### ISSUE TITLE
Download Button?

### ISSUE THREAD

**Issue by mozalan** [live-composer/live-composer-page-builder#911]
Does anyone now what the "download button" element is for?! - There is no link functionality in its properties, you can't browse to the file you'd like to link it to or anything close... so the question is, what's the purpose of having it?.. 

Please check, must be a bug.

Thanks in advance,

**Comment by FoldingTheme** [comment]
The download button call one of the download link from the WP Admin > Downloads > Your download post:

![download](https://user-images.githubusercontent.com/21088706/38718151-4365ed7e-3ef4-11e8-8347-dfdd4924491d.png)

For more assistance, please open a support ticket: https://livecomposerplugin.com/support/support-request/
