### ISSUE TITLE
Fatal Error: Call to undefined function is_user_logged_in() on Line 51

### ISSUE THREAD

**Issue by penguin2111** [live-composer/live-composer-page-builder#914]
Hi there,

I am new to Github so hopefully I have posted this in the correct format to receive help. 

My website recently got this error and it has essentially broken my site for the time being. Anytime I visit my domain I get this error:

**Fatal error: Call to undefined function is_user_logged_in() in /home/penguin2111/public_html/100voice.com/wp-content/plugins/live-composer-page-builder/includes/class-dslc-cache.php on line 51**

Sorry if I didn't post this correctly. Please let me know if any other details are needed to help resolve this issue. 

If it matters, I have Wp-Super Cache enabled on my website. 

Thanks in advance.

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.
