### ISSUE TITLE
Button module Styling options

### ISSUE THREAD

**Issue by mozalan** [live-composer/live-composer-page-builder#916]
It's missing the Top & Bottom Margins section where you can adjust it in order to keep buttons in a row.

![lc button styling](https://user-images.githubusercontent.com/20672449/38864923-241ad54a-4234-11e8-91e6-cc5aa45dd54f.jpg)

**Comment by mozalan** [comment]
IT would also be a very nice feature to add a SEPARATOR between the TITLE & BUTTON... Just sayin'

**Comment by juslintek** [comment]
I think it would be better to remake grid system to use bootstrap or at least implement flex-grid, so you can vertically position each element where you want. :-)

**Comment by FoldingTheme** [comment]
The top/bottom margins for button style added, but for a proper alignment when the title has different length, is needed to use custom CSS.
