### ISSUE TITLE
Just displaying (short)code

### ISSUE THREAD

**Issue by bestuurmebiose** [live-composer/live-composer-page-builder#917]
I have transfered my website with from one URL to another on my multisite and now most of the pages made with Live Composer just display the code that should make up the page, instead of the actual lay-out. Yet there is one page which does correctly display the lay-out I want. I am guessing this is some kind of bug, yet I have been unable to find what causes it and more importantly how to fix it.

**Comment by FoldingTheme** [comment]
Hi there,

Most likely you migrated wrongly the installation. If need assistance, please open a support ticket and provide an admin access: https://livecomposerplugin.com/support/support-request/

Thank you!
