### ISSUE TITLE
All my style preset gone

### ISSUE THREAD

**Issue by mujibski** [live-composer/live-composer-page-builder#919]
All my saved style preset gone and I can't save my new style preset as well.  I've installed newest update of the plugin.

**Comment by FoldingTheme** [comment]
We haven't seen this problem on other users website, so I think it's somehow linked to your server or other plugins. On our tests, there is no such an issue. If still need assistance, please open a support ticket and provide an admin access: https://livecomposerplugin.com/support/support-request/

Thank you!
