### ISSUE TITLE
Add filters to override default module outputs (for cases where it would take too long replace all module in all templates)

### ISSUE THREAD

**Issue by juslintek** [live-composer/live-composer-page-builder#920]
I think these filter would be great addition for developers. I've overridden entire `dslc_module_front` shortcode, in order to do this:
```php
		// Code before module output.
		ob_start();
			$module_instance->module_before( $settings );
			$output_start = ob_get_contents();
		ob_end_clean();

		// Module output.
		ob_start();
            if (did_action($module_id . '_output') > 0) {
                do_action($module_id . '_output', $settings, $module_instance, $dslc_active);
            } else {
                $module_instance->output($settings);
            }
			$output_body = ob_get_contents();
		ob_end_clean();

		// Code after module output.
		ob_start();
			$module_instance->module_after( $settings );
			$output_end = ob_get_contents();
		ob_end_clean();
```
on https://github.com/live-composer/live-composer-page-builder/blob/master/includes/display-functions.php#L1101

P.S. Shortcodes are bad for performance, because of high amount of regex used.

**Comment by FoldingTheme** [comment]
Hi there,

Do you mind if elaborate the purpose of this and why will be a great addition for developers?

Thanks.

**Comment by juslintek** [comment]
You wouldn't need to recreate templates and layouts built using existing modules, with your personal ones, instead you could override, the output code, by applying hook, and instead of returning the output from base  module it would return from the one added to the hook. So you you could prevent lots of manual labor.

**Comment by plumib** [comment]
@FoldingTheme you create extensibility, like in #951 & #952 , where lazyloading is implemented by filtering the image module's output.
