### ISSUE TITLE
New Type Images

### ISSUE THREAD

**Issue by felipedeboni** [live-composer/live-composer-page-builder#921]
Is there any plan to add a new type for multiple images?

I tried to make it work, but I am having problems with the "Confirm", on the preview everything works just fine, but as soon as the page is refreshed, the customization is lost.

**Comment by FoldingTheme** [comment]
Please check this article: https://livecomposer.help/article/196-basic-debugging-process

Also try clear the plugin cache from WP Admin > Live Composer > Settings > Performance? If still have issues, try to disable it. 

If still need assistance after debug, please open a support ticket and provide an admin access: https://livecomposerplugin.com/support/support-request/
