### ISSUE TITLE
The "Load more" button label from pagination cannot be translated

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#922]
The "load more"string is not available in the pot file.

**Comment by xdima92x** [comment]
I checked it. I installed the plugin 'Loco Translate'. I changed the [language to Spanish.](https://prnt.sc/jsiux9).  I don't have [this bug](http://prntscr.com/jsj73r). Could you again check it?

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/922

**Comment by FoldingTheme** [comment]
I still have the issues.

**Comment by FoldingTheme** [comment]
It seems it depends on where the translation file is stored. The translation need to use the "system" path (the LC path) and not the Loco plugin path.
