### ISSUE TITLE
Option to disable the lighbox script in Live Composer

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#924]
Consider adding a backend option for this. Many customers uses third-party gallery plugins which load a lightbox script which almost all of the time causes conflicts or weird issues like this:

![double_lightbox](https://user-images.githubusercontent.com/21088706/40320483-8dc81596-5d34-11e8-8b43-5fb1c5704190.png)

**Comment by FoldingTheme** [comment]
@xdima92x pls check this client scenario:

How can I change, that Live Composer/Page Builder is adding "image" to the class attribute of links to images, when parsing the output of shortcode-inserts? I don't want the lightbox-effect, which is triggered because of the "image" value of the class attribute. I do use the "folder-gallery" which is inserted via shortcode like this: [foldergallery folder="wp-content/uploads/chronik" title="Bilder aus der Chronik"], which uses easy-fancybox as a lightbox-plugin.
On pages which didn't use the Live Composer everything is fine, but on pages using Live-Composer, this "image"-value is added to the 'class="fancybox"'.

https://wordpress.org/plugins/folder-gallery/

**Comment by xdima92x** [comment]
@FoldingTheme It works a properly. I recorded [a short video](https://drive.google.com/file/d/1wuZkVBUVL_0-spJALHlCvRNiKE6MYf1Z/view).

**Comment by FoldingTheme** [comment]
@xdima92x tx,  Try to use multiple modules in that page and see if there is nothing wrong with multiple lighbox classes.

**Comment by xdima92x** [comment]
@FoldingTheme Yes, I have this bug when I will use the module 'image'. But it's a not problem with the Live Composer. If a user wants to use another a plugin for instance as easy-fancybox he needs to use these settings ( below )
![1](https://user-images.githubusercontent.com/21044637/44139324-6ab13770-a07f-11e8-9241-7ea63aa1a449.jpg)
