### ISSUE TITLE
Improvements for Tab and Accordion modules

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#927]
Check the possibility to have these module working with more complex content users can have in the WordPress editor (shortcodes, complex styled content, etc)

**Comment by xdima92x** [comment]
Notice:

At this moment, many plugins with shortcodes don't work in tabs. For instance work in the first tab but not in second or, ensure the complex styles added in wordpress editor are properly displayed in all the tabs.

**Comment by FoldingTheme** [comment]
@xdima92x I found the iframes still have issues when are not loaded by first tab.

Please make tests with such an example:

<iframe src="https://www.doogal.co.uk/StravaRoute.php?id=https://www.strava.com/routes/14904362&embed=true&segments=false&title=false&streetView=false" width="950" height="850" frameborder="0"></iframe>

**Comment by xdima92x** [comment]
@FoldingTheme Do you mean this error?
![_ _081718_123233_pm](https://user-images.githubusercontent.com/21044637/44259247-aa4f3580-a219-11e8-9bdd-0cf190d42b3b.jpg)

I have the error with google map but it's not the iframe

**Comment by xdima92x** [comment]
@FoldingTheme Hi) I checked other iframes with Google Maps. It works properly.
