### ISSUE TITLE
Still an issue: Bug: Testimonials #744

### ISSUE THREAD

**Issue by Psinergy** [live-composer/live-composer-page-builder#928]
Please see the original thread. This should have never been closed.

Also, now someone else commented that they are also having the issue (they probably just noticed the issue on their site)... so, obviously, we are not the only ones who have used this function in that way.

**Comment by FoldingTheme** [comment]
Hi there. The Testimonials, have a dedicated module and is not designed to be used with continue reading button. Please use the dedicated module. Was a mistake from our side to not remove from beginning the custom post from the post module. This option will be removed on the next update to avoid this confusion.

Thanks for understanding.

**Comment by Psinergy** [comment]
What is the dedicated module?

Next... with the Testimonials module, it honestly made sense to have the "continue reading" button. Soooooooooo, how can that be reconsidered to have it brought back?

Next... what option will be removed in the next update? Also, do you have any suggestion on how to easily move Testimonials from where they are to something that actually supports it (without having to redo every single one)?
