### ISSUE TITLE
Table-editor in content-element-editor?

### ISSUE THREAD

**Issue by NavyCL** [live-composer/live-composer-page-builder#932]
Is it possible to get Table-editor in content-element-editor ?
Thanks.

**Comment by FoldingTheme** [comment]
Hi there,

The Content module load the post/page content, where you have the WordPress editor. Check more on https://livecomposer.help/article/128-modules

If still need assistance please open a support ticket and provide an admin access: https://livecomposerplugin.com/support/support-request/

Best regards.
