### ISSUE TITLE
live composer Issue 

### ISSUE THREAD

**Issue by TSARL** [live-composer/live-composer-page-builder#933]
Hey guys, 
 i nstalled this plugin and after when i edit a page i can't save it 
JavaScript error detected in a third-party plugin
Uncaught SyntaxError: Unexpected token in JSON at position 1458
this is the bug 
this is the screen  it alaways reloading 

![image](https://user-images.githubusercontent.com/39091698/41783313-df1037f0-763c-11e8-93bc-f0a6f4df611b.png)

**Comment by FoldingTheme** [comment]
We haven't seen this problem on other users website, so I think it's somehow linked to your server or other plugins. On our tests, there is no such an issue. Please check this article: https://livecomposer.help/article/196-basic-debugging-process

If still need assistance after debug, please open a support ticket and provide an admin access: https://livecomposerplugin.com/support/support-request/
