### ISSUE TITLE
Sticky row does not work with smooth scrolling plugin

### ISSUE THREAD

**Issue by thehervy** [live-composer/live-composer-page-builder#935]
Not sure if this is bug on LC side, or "Easy Smooth Scroll Links". 
Link to that plugin: https://wordpress.org/plugins/easy-smooth-scroll-links/

Bug:
When you set a sticky row on the page -> the smooth scrolling stops working and sticky feature of LC as well. I had to deactivate the other plugin and then the sticky row works fine. Or I tried stop using sticky feature and the scrolling works then fine.

Tried on several sites and result is the same.

Latest wordpress.

**Comment by xdima92x** [comment]
Hi, yes, you are right. We have a conflict with the plugin "Easy Smooth Scroll Links".
I fixed it. You can use this branch: https://github.com/live-composer/live-composer-page-builder/tree/issue/935
