### ISSUE TITLE
URGENT: SyntaxError: JSON.parse: bad escaped character at line 1 column 7449 of the JSON data

### ISSUE THREAD

**Issue by gracevillarino** [live-composer/live-composer-page-builder#940]
Error Detected on Live Composer
via Live Composer returned JS error
SyntaxError: JSON.parse: bad escaped character at line 1 column 7449 of the JSON data
File "https://www.osageambulances.com/wp-content/plugins/live-composer-page-builder/js/builder/builder.codegeneration.functions.js?ver=1.3.16", line 275, char 23

Using the latest version of the plugin with premium extension.
URL - https://www.osageambulances.com
WP version -  4.9.7
PHP version -  5.6.36
Theme used - LC Blank

**Comment by FoldingTheme** [comment]
We haven't seen this problem on other users website, so I think it's somehow linked to your server or other plugins. On our tests, there is no such an issue. Please check this article: https://livecomposer.help/article/196-basic-debugging-process

If still need assistance after debug, please open a support ticket and provide an admin access: https://livecomposerplugin.com/support/support-request/
