### ISSUE TITLE
Update from SEOWP has created an error JavaScript error detected in a third-party plugin Uncaught Reference Error: tinymce is not defined File "https://www.URL.co.uk/?dslc", line 1216, char 46

### ISSUE THREAD

**Issue by RackpointDev** [live-composer/live-composer-page-builder#943]
Please advice on the recommended action to resolve this issue - I have tried everything!

[Rackpoint](https://www.rackpoint.co.uk)

**Comment by RackpointDev** [comment]
Error JavaScript error detected in a third-party plugin
Uncaught ReferenceError: tinymce is not defined
File "https://www.rackpoint.co.uk/ ?dslc", line 1216, char 46

After latest update.

**Comment by FoldingTheme** [comment]
Hi there. This is not a support forum. Contact the premium theme developer. Thanks for understanding.
