### ISSUE TITLE
Add lightbox option for content module images

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#944]
This will allow the customers to open their images from blog posts in a Lighbox.

**Comment by xdima92x** [comment]
@FoldingTheme 

I added for modules:

- Blog
- Posts
- Projects
- Partners
- Downloads

Every module has this option: 
![_ _082018_025653_pm](https://user-images.githubusercontent.com/21044637/44339231-492d9900-a489-11e8-949e-718ee6a48e2c.jpg)

**Comment by xdima92x** [comment]
https://github.com/live-composer/live-composer-page-builder/tree/issue/944

**Comment by FoldingTheme** [comment]
@xdima92x it works great. please add this option to the "Content module" too. This way an uploaded image to the post content won't opening in a blank page:

example: 

`<a href="http://localhost:8888/pagebuilder/wp-content/uploads/2018/04/placeholder-1.jpg"><img src="http://localhost:8888/pagebuilder/wp-content/uploads/2018/04/placeholder-1.jpg" alt="" class="alignnone size-full wp-image-53" /></a>`

![edit_post_ _page_builder_ _wordpress](https://user-images.githubusercontent.com/21088706/44400488-fb319780-a553-11e8-9bab-f0e39d7cab5c.png)

**Comment by xdima92x** [comment]
Please add the class 'dslc-lightbox-image' for tag 'a' and the lightbox will work.
