### ISSUE TITLE
On CTP modules is no separator thickness option for responsive devices

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#945]
Such an option provide more flexibility to the client. For instance, the row separator can be hidden on mobiles adjusting the thickness to zero.

![separator](https://user-images.githubusercontent.com/21088706/44446570-0df8aa80-a5ee-11e8-9cb3-519fe10a01e8.png)

**Comment by xdima92x** [comment]
@FoldingTheme I added it. You can this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/945
