### ISSUE TITLE
"Hide on sticky row" option for modules

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#950]
When the row is set as sticky, some customers need to hide certain modules. This is needed in special for headers where the sticky position should take less room space.

![screenshot_091218_103919_am](https://user-images.githubusercontent.com/21088706/45409541-1cc7ff80-b678-11e8-8a7f-0f61490fe154.jpg)

**Comment by xdima92x** [comment]
Hi @FoldingTheme I'm not sure if it will be a properly to add "Hide on sticky row" option for all modules. I think we need to add this option for modules:

Live Composer:
- HTML
- Shortcode
- Text
- Image
- Button
- Icon
- Social
- Widgets
- Navigation
- Logo

LC Extensions:
- Mega Main Menu

What do you think about it?

**Comment by FoldingTheme** [comment]
Great job! pls add animation when hiding.
