### ISSUE TITLE
Enable lazy loading by filtering the image module

### ISSUE THREAD

**Issue by plumib** [live-composer/live-composer-page-builder#951]
I'm not entirely familiar with the backend of the project, but if you use the Image module as a building block for all image-related modules, you could add a filter to the resulting image HTML, similar to [post_thumbnail_html](https://developer.wordpress.org/reference/hooks/post_thumbnail_html/) and by doing so, enabling lazyloading in the entire project.

The hook is needed to transform `src` and `srcset` into `data-src` and `data-srcset` which is a requirement of almost [every popular lazyloading library](https://github.com/verlok/lazyload).

What do you think?

**Comment by xdima92x** [comment]
@plumib Hi, I checked this code. We will have some bug. But I added apply_filter (dslc_image_render) for the module image. You can use this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/951

**Comment by plumib** [comment]
Hi @xdima92x , i appreciate it, if it does produce a bug let me know. I'm interested in getting this merged as soon as possible. How long do you think that would take?

**Comment by xdima92x** [comment]
I'm sorry, but I can't say when we will have a new release
