### ISSUE TITLE
Gallery module Lightbox enabled on mobile devices too

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#953]
The Lightbox feature is disabled for the gallery module on mobile. It open the gallery page. This involve multiple pages loaded on mobile which is not good for UIX.

33108 - "While scrolling through the list you want to fast check few foto from one gallery, later from other and so on. On desktop its possible - you click and gets an lightbox. Then you can close it and freely see the rest of the page where you've just been."

**Comment by xdima92x** [comment]
@FoldingTheme Hi, I tested it on mobile - http://seowp.crazymink.com/test/ It works :)
