### ISSUE TITLE
Make the coment form GDPR Compliance

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#958]
https://www.wpbeginner.com/wp-themes/how-to-add-a-gdpr-comment-privacy-opt-in-checkbox-in-wordpress/

![the_ultimate_guide_to_wordpress_and_gdpr_compliance__in_plain_english__and_hello_world____seowp](https://user-images.githubusercontent.com/21088706/46602752-bfe62a80-caf9-11e8-8abf-b169028f5dc2.png)

Eventually, this can be an option in the comment form module as done by this plugin: https://wordpress.org/plugins/wp-gdpr-compliance/

**Comment by xdima92x** [comment]
@FoldingTheme Please check it. You can use this branch - https://github.com/live-composer/live-composer-page-builder/tree/issue/958

**Comment by FoldingTheme** [comment]
![is_search_engine_submission_necessary____seowp](https://user-images.githubusercontent.com/21088706/46853632-56bb2b80-ce07-11e8-9b55-f02dfeec961f.png)
