### ISSUE TITLE
CONFLICT: Intelly Inline Related Posts 

### ISSUE THREAD

**Issue by emingus** [live-composer/live-composer-page-builder#962]
Using Intelly's Inline Related Posts and it seems that LC (and also another builder I tested) is having issues with:

- NOT recognizing categories (it's supposed to pull of "marriage" posts when I'm in the "marriage" category...but currently it's pulling up random, not specific posts)

- NOT listening to my rules (I say only pull 2 posts, it pulls 5 - I say put them 500 words apart, it puts them 25 words apart)

I've disabled all plugins except LC and it's still acting funky.

Messaging plugin owner as well. Happens with FREE and PREMIUM versions.

**Comment by xdima92x** [comment]
I'm sorry but I'm not sure if I understand your question. The Live Composer doesn't have the module 'Related Posts'. Can you create a screenshot or video with your problem?

**Comment by emingus** [comment]
https://youtu.be/USZK0bNQERg
And a small issue i forgot to mention here> https://youtu.be/pgMN2r9J0rg
