### ISSUE TITLE
Footer content in RSS problem

### ISSUE THREAD

**Issue by FoldingTheme** [live-composer/live-composer-page-builder#964]
Lately, more many customers complain about having footer content in the RSS:

![preview-full-screen-shot-2018-11-15-at-2_17_00-pm_png_614x318_pixels](https://user-images.githubusercontent.com/21088706/49066201-0cf89a00-f229-11e8-97bb-0e127f4e55cc.png)

The RSS should display just the posts/pages and not the footer.

**Comment by xdima92x** [comment]
How can I check it? Do you know what server I can use for it?
