### ISSUE TITLE
Live Composer modifying Main Query causing conflict with Polylang

### ISSUE THREAD

**Issue by rbperrie** [live-composer/live-composer-page-builder#971]
The issue is due to a bug in Live Composer. When visiting the archives product categories, the main query parameters $wp_query->query should be like:
Array
(
[product_cat] => food
[lang] => en
)

These parameters must not be modified.

But Live Composer modifies this main query by adding a lot of parameters (see the enclosed debug.log file). Live Composer must not modify the main query parameters otherwise plugins such as Polylang don't have the right information about the current page being visited. If Live Composer needs to modify the query behavior, they should modify $wp_query->query_vars but not not $wp_query->query.

For the Live Composer team information, I used the Query Monitor plugin to identify this bug: https://wordpress.org/plugins/query-monitor/. This plugin clearly demonstrates the bug (even when Polylang is not active) as it shows that the conditional is_search is true on your product category page, when it should be false (it is false when we deactivate Live Composer).

They can contact us at support@polylang.pro if they need more explanation on this issue.

**Comment by xdima92x** [comment]
I don't find a bug with Polylang. I recommend only use the plugin 'WPML'. You can read the article here: https://livecomposer.help/article/146-how-to-translate-page-content
