### ISSUE TITLE
Getting blank pages after update

### ISSUE THREAD

**Issue by ETLleida** [live-composer/live-composer-page-builder#973]
Hello,
I'm using live composer and after the update I got all the pages blank. When LC is not activated, the webpage works fine (except for those created with LC, of course.
Any tips on how to solve it for a newbie?

Thanks.

**Comment by Berkelium0** [comment]
Same problem here... any solutions?

**Comment by ETLleida** [comment]
I had to go back to the previoua s version of LC. Now it seems to be
working fine but I can't update....

**Comment by Berkelium0** [comment]
Yep that solved it, thanks! Hope this gets fixed soon...

**Comment by ETLleida** [comment]
Glad to hear that! Thanks :-)

**Comment by xdima92x** [comment]
Hi @ETLleida @Berkelium0 :) Could you send me error logs? Do you have a problem with JS?

**Comment by rbperrie** [comment]
We are seeing the blank pages after update often on sites that are still running PHP 5.6 or older, if that is your case updating PHP to 7.2 should solve your issue. As always but especially when updating core files like PHP we STRONGLY recommend that you backup your site before updating.

**Comment by xdima92x** [comment]
I will close this issue at this moment. Let me know if you again will have this problem
