### ISSUE TITLE
İmage element ReSize

### ISSUE THREAD

**Issue by mozalan** [live-composer/live-composer-page-builder#974]
Latest update, Image Element resizing doesn't work, when you assign hight / widght, not changing the size of the image. Please look into it ASAP.

Thanks in advance!

**Comment by thehervy** [comment]
Same here. I had to manually change them. Really unexpected. Thank you for future fix!

**Comment by xdima92x** [comment]
Hi guys @mozalan @thehervy It works for me. You can see this video - https://drive.google.com/file/d/1MrII5WOE7AsCdzJOtKBhGaeqn7qZx35h/view Do you have js error? Could you send me your error log?

**Comment by xdima92x** [comment]
I will close this issue because so far, we don't have any additional information. If you have more questions about this, please write here.

**Comment by thehervy** [comment]
There is issue described here https://github.com/live-composer/live-composer-page-builder/issues/963

But it is really critical, I have tons of images resized just by width and now they do not work... I am really surprised that this is "normal" behavior, that you have to insert both dimensions.. 👎
