### ISSUE TITLE
Container options not accessible (focus on element instead)

### ISSUE THREAD

**Issue by thehervy** [live-composer/live-composer-page-builder#977]
Hi, I had an issue with options of container inside row. I cannot click on the options, drag it etc..
Screenshot:
![image](https://user-images.githubusercontent.com/40669580/52160428-2e6b7b80-26db-11e9-9dfb-5bbafbfb5f8c.png)

Steps to reproduce:

1. Set row type: Full
2. Add any element into the container
3. Now hover the area where the options for container are.. Focus will get always the element, and no the container options

Workaround:
1. set row back to "wrapped", edit container and then set back row to full.

**Comment by menachemshapiro** [comment]
I have also seen this issue. The workaround works.

**Comment by lumberman** [comment]
What theme is that?
Can't recreate it on my end.

**Comment by menachemshapiro** [comment]
I use lc-blank theme.

**Comment by lumberman** [comment]
Fixed in the next update.
Thanks for reporting this.
