### ISSUE TITLE
Error loading a page (tp_meta)

### ISSUE THREAD

**Issue by jkkoenig** [live-composer/live-composer-page-builder#981]
We are using WP 4.9.9. and Live Composer 1.4.1 and PHP 5.6. 

On some pages we get an error:
Warning: in_array() expects parameter 2 to be array, string given in /www/htdocs/.../wp-content/plugins/live-composer-page-builder/modules/tp-meta/module.php on line 672

If I change into Edit-Mode there will be again the warning and some standard content, like:
this is an example of heading 1
this is an example of heading 2
this is an example of heading 3
...

I tried to update to Live Composer 1.4.2 and PHP 7.2 - no change.

I do not want to Update Wordpress, because I am using some Plugins, which are not prepared to WP 5.1

Do you habe nay suggestion how to solve this?

Example page: https://www.eu-china-twinning.org/2018/08/shenzhen-zero-waste-environmental-public-interest-development-center-and-energy-justice-association-2018/

Thanks,
Jürgen

**Comment by lumberman** [comment]
Fixed in the next update
