### ISSUE TITLE
1.4.2 Update hides all my Live Composer Content

### ISSUE THREAD

**Issue by Pockitz** [live-composer/live-composer-page-builder#983]
Since updating the Live Composer from 1.4.0 to 1.4.2 the images and text boxes that I have placed in Live Composer have completely disappeared. I have checked for a conflict with other plugins but it is caused by Live Composer. I have reinstalled the 1.4.0 plugin and the problem still occurs. Is there a setting that I need to activate in order to reset the plugin and view my content again?

**Comment by Pockitz** [comment]
Since updating the Live Composer from 1.4.0 to 1.4.2 the images and text boxes that I have placed in Live Composer have completely disappeared. I have checked for a conflict with other plugins but it is caused by Live Composer. I have reinstalled the 1.4.0 plugin and the problem still occurs. Is there a setting that I need to activate in order to reset the plugin and view my content again?

**Comment by bandicootmarketing** [comment]
Hi @Pockitz - this is obviously not normal behavior for Live Composer and we have had thousands of successful upgrades from 1.4.0 to 1.4.2 with no issues. Unfortunately, as Live Composer is a free and open source product we are unable to provide free premium support at this time. Please visit https://livecomposerplugin.com/support to see the Free support options. Alternatively, you can purchase any one of our paid products and we would be more than happy to log into your site and suss out the issues with you. Cheers and thanks!

**Comment by Pockitz** [comment]
I reverted back to 1.3.18 and all the problems disappeared.
