### ISSUE TITLE
"Edit in Live Composer" displays rows in wrapped, not full type

### ISSUE THREAD

**Issue by menachemshapiro** [live-composer/live-composer-page-builder#997]
I just started noticing this recently, so I'm not sure when this started. I have rows with the type set to "full". They display in full. When I enter edit mode, the rows are displayed as wrapped. I make the edits, save and exit edit mode, and the display reverts to full.

Please let me know if you need any specific information from me.

I have WordPress 5.2.2 running LC Blank (1.0.2) theme.

Live Composer Version 1.4.7

**Comment by lumberman** [comment]
Fixed in the next update.
Thanks for reporting!
