### ISSUE TITLE
Issue with Live Composer breaking Yoast

### ISSUE THREAD

**Issue by xboxsimpson** [live-composer/live-composer-page-builder#998]
I believe there is an issue with Live Composer breaking Yoast SEO. I asked for support from Yoast, and they provided the following (please not that I use Live Composer for my header and Elementor for the body of all my pages):

"We reviewed the edit screen of your post and found an error in the browser's console (see screenshot below). The error references the Live Composer page builder which brakes the Yoast analysis on posts. We've been able to reproduce this error in our testing environment. As soon as we install and activate Live Composer, the error shows up on posts and the Yoast analysis doesn't return any results. Disabling Live Composer fixes the problem. Note that this error doesn't occur on pages where the Yoast analysis works as expected. 

Please, reach out to the Live Composer team and bring this issue to them. They'll be able to investigate why their plugin is breaking the Yoast analysis on posts and not on pages."

![live composer yoast](https://user-images.githubusercontent.com/52107324/60671720-b2b85b00-9e41-11e9-834f-4a8628557174.png)

**Comment by menachemshapiro** [comment]
I didn't do any research into this issue, but have you tried disabling "Basic HTML/CSS Caching" in the Live Composer settings? I've found that solves a lot of issues.

**Comment by xboxsimpson** [comment]
Hello,

My Live Composer is already set to disable Basic HTML / CSS Catching, so
that is likely not the issue.

**Comment by lumberman** [comment]
Can you please check if the latest update of the plugin solved your problem?

**Comment by xboxsimpson** [comment]
Hello,

I checked and the update has not fixed the issue. Thank you.

**Comment by lumberman** [comment]
By any chance, you can create a screenshot of the problem again?
Looking at plugin code I can't see how it's possible. We check for the variable to be defined before working with it, so it can't be 'undefined' anymore.

**Comment by xboxsimpson** [comment]
Hello,

As of this morning, the issue seems to have been resolved.
