### ISSUE TITLE
Style 'dslc-css-ie' delcares using a missing 'dslc-main-css' dependency

### ISSUE THREAD

**Issue by tristanleboss** [live-composer/live-composer-page-builder#999]
In `includes/scripts.php`, at line 94, you enqueue a style for IE:

```
wp_enqueue_style( 'dslc-css-ie', DS_LIVE_COMPOSER_URL . 'css/ie.css', array( 'dslc-main-css' ), DS_LIVE_COMPOSER_VER );
```

The problem is that you says it depends on a style `dslc-main-css` which is nowhere to be found (I did a search for this slug in the whole codebase).

Query Monitor detects this problem and tells you a dependency is missing.

![image](https://user-images.githubusercontent.com/1431508/61172111-6cb97080-a580-11e9-96b9-a6df8ebf2b69.png)

**Comment by lumberman** [comment]
Fixed in the next update.
Thanks for reporting this.
